module.exports = {
  apps: [
    {
      name: 'smart-wing-storefront',
      cwd: '/opt/smart-wing/apps/storefront-web',
      script: '/opt/smart-wing/node_modules/vinext/dist/cli.js',
      args: 'start',
      node_args: ['--env-file=/opt/smart-wing/.env.production'],
      interpreter: '/usr/bin/node',
      // The public storefront is a production payment boundary. Test fixtures
      // and simulated payment routes must never be enabled in this process.
      env: { NODE_ENV: 'production', PORT: '3000', APP_ENV: 'production', AUTH_MODE: 'membership' },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      restart_delay: 3000,
      max_restarts: 5,
      min_uptime: '10s',
      error_file: '/var/log/pm2/smart-wing-storefront-error.log',
      out_file: '/var/log/pm2/smart-wing-storefront-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'smart-wing-admin-api',
      cwd: '/opt/smart-wing',
      script: 'services/commerce-api/dist/admin-server.cjs',
      node_args: ['--env-file=/opt/smart-wing/.env.production'],
      interpreter: '/usr/bin/node',
      env: { NODE_ENV: 'production', PORT: '3001' },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '768M',
      restart_delay: 3000,
      max_restarts: 5,
      min_uptime: '10s',
      error_file: '/var/log/pm2/smart-wing-admin-error.log',
      out_file: '/var/log/pm2/smart-wing-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'smart-wing-auth-web',
      cwd: '/opt/smart-wing/apps/auth-web',
      script: '/opt/smart-wing/node_modules/vite/bin/vite.js',
      args: 'preview --host 127.0.0.1 --port 3010 --strictPort',
      interpreter: '/usr/bin/node',
      env: { NODE_ENV: 'production' },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      restart_delay: 3000,
      max_restarts: 5,
      min_uptime: '10s',
      error_file: '/var/log/pm2/smart-wing-auth-error.log',
      out_file: '/var/log/pm2/smart-wing-auth-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
