export type PermissionRisk = 'low' | 'elevated' | 'high' | 'critical';

export const PERMISSIONS = {
  profileReadSelf: 'profile.read.self',
  profileUpdateSelf: 'profile.update.self',
  credentialPasswordChangeSelf: 'credential.password.change.self',
  credentialPhoneChangeSelf: 'credential.phone.change.self',
  credentialPasswordResetOther: 'credential.password.reset.other',
  credentialPhoneResetOther: 'credential.phone.reset.other',
  sessionReadSelf: 'session.read.self',
  sessionRevokeSelf: 'session.revoke.self',
  sessionRevokeOther: 'session.revoke.other',
  catalogRead: 'catalog.read',
  commercialResourceRead: 'commercial_resource.read',
  commercialResourceManage: 'commercial_resource.manage',
  entitlementRead: 'entitlement.read',
  entitlementManage: 'entitlement.manage',
  purchaseLimitRead: 'purchase_limit.read',
  purchaseLimitManage: 'purchase_limit.manage',
  employeeQualificationRead: 'employee_qualification.read',
  employeeQualificationManage: 'employee_qualification.manage',
  qualificationApprove: 'qualification.approve',
  productCreate: 'product.create',
  productUpdate: 'product.update',
  productPublish: 'product.publish',
  productDelete: 'product.delete',
  priceReadCost: 'price.read.cost',
  priceUpdate: 'price.update',
  inventoryRead: 'inventory.read',
  inventoryUpdate: 'inventory.update',
  orderCreate: 'order.create',
  orderRead: 'order.read',
  orderCancel: 'order.cancel',
  orderShip: 'order.ship',
  orderExport: 'order.export',
  afterSaleRead: 'aftersale.read',
  afterSaleHandle: 'aftersale.handle',
  orderRefund: 'order.refund',
  voucherRead: 'voucher.read',
  voucherCreate: 'voucher.create',
  voucherIssue: 'voucher.issue',
  voucherActivate: 'voucher.activate',
  voucherDisable: 'voucher.disable',
  voucherExtend: 'voucher.extend',
  voucherVoid: 'voucher.void',
  voucherExport: 'voucher.export',
  financeRead: 'finance.read',
  financeReconcile: 'finance.reconcile',
  financePaymentConfigure: 'finance.payment.configure',
  financeWithdraw: 'finance.withdraw',
  financeSettlementApprove: 'finance.settlement.approve',
  financeInvoiceManage: 'finance.invoice.manage',
  financeExport: 'finance.export',
  analyticsRead: 'analytics.read',
  analyticsExport: 'analytics.export',
  memberRead: 'member.read',
  memberPiiRead: 'member.pii.read',
  memberInvite: 'member.invite',
  memberUpdate: 'member.update',
  memberDisable: 'member.disable',
  memberOffboard: 'member.offboard',
  memberImport: 'member.import',
  memberExport: 'member.export',
  memberCodeVerify: 'member_code.verify',
  roleRead: 'role.read',
  roleCreate: 'role.create',
  roleUpdate: 'role.update',
  roleDelete: 'role.delete',
  roleGrant: 'role.grant',
  scopeGrant: 'scope.grant',
  organizationRead: 'organization.read',
  organizationManage: 'organization.manage',
  mallRead: 'mall.read',
  mallManage: 'mall.manage',
  mallDecorate: 'mall.decorate',
  mallPublish: 'mall.publish',
  supplierRead: 'supplier.read',
  supplierManage: 'supplier.manage',
  storeRead: 'store.read',
  storeManage: 'store.manage',
  customerServiceRead: 'customer_service.read',
  customerServiceHandle: 'customer_service.handle',
  customerServiceManage: 'customer_service.manage',
  auditRead: 'audit.read',
  auditExport: 'audit.export',
  securityPolicyManage: 'security.policy.manage',
  integrationRead: 'integration.read',
  integrationManageSecrets: 'integration.secrets.manage',
  tenantManage: 'tenant.manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export interface PermissionDefinition {
  code: Permission;
  name: string;
  category: string;
  risk: PermissionRisk;
  mvp: boolean;
}

const p = (code: Permission, name: string, category: string, risk: PermissionRisk = 'low', mvp = true): PermissionDefinition => ({ code, name, category, risk, mvp });

/** UI labels are data, so new business modules do not require access-engine rewrites. */
export const PERMISSION_CATALOG: readonly PermissionDefinition[] = [
  p(PERMISSIONS.profileReadSelf, '查看本人资料', '账号安全'),
  p(PERMISSIONS.profileUpdateSelf, '修改本人资料', '账号安全'),
  p(PERMISSIONS.credentialPasswordChangeSelf, '修改本人密码', '账号安全', 'elevated'),
  p(PERMISSIONS.credentialPhoneChangeSelf, '修改本人手机', '账号安全', 'high'),
  p(PERMISSIONS.credentialPasswordResetOther, '重置他人密码', '账号安全', 'critical'),
  p(PERMISSIONS.credentialPhoneResetOther, '重置他人手机', '账号安全', 'critical'),
  p(PERMISSIONS.sessionReadSelf, '查看本人会话', '账号安全'),
  p(PERMISSIONS.sessionRevokeSelf, '退出本人其他会话', '账号安全', 'elevated'),
  p(PERMISSIONS.sessionRevokeOther, '强制退出他人会话', '账号安全', 'critical'),
  p(PERMISSIONS.catalogRead, '查看商品池', '商品'),
  p(PERMISSIONS.commercialResourceRead, '查看商业资源关系', '商业资源'),
  p(PERMISSIONS.commercialResourceManage, '管理商业资源关系', '商业资源', 'high'),
  p(PERMISSIONS.entitlementRead, '查看员工资格策略', '员工资格'),
  p(PERMISSIONS.entitlementManage, '管理员工资格策略', '员工资格', 'high'),
  p(PERMISSIONS.purchaseLimitRead, '查看限售模板', '员工资格'),
  p(PERMISSIONS.purchaseLimitManage, '管理限售模板', '员工资格', 'high'),
  p(PERMISSIONS.employeeQualificationRead, '查看员工福利资格事实', '员工资格'),
  p(PERMISSIONS.employeeQualificationManage, '维护员工福利资格事实', '员工资格', 'high'),
  p(PERMISSIONS.qualificationApprove, '审批高风险资格变更', '员工资格', 'critical'),
  p(PERMISSIONS.productCreate, '新增商品', '商品'),
  p(PERMISSIONS.productUpdate, '编辑商品', '商品', 'elevated'),
  p(PERMISSIONS.productPublish, '上下架商品', '商品', 'high'),
  p(PERMISSIONS.productDelete, '删除未交易商品', '商品', 'critical'),
  p(PERMISSIONS.priceReadCost, '查看成本价', '商品', 'high'),
  p(PERMISSIONS.priceUpdate, '修改价格', '商品', 'critical'),
  p(PERMISSIONS.inventoryRead, '查看库存', '商品'),
  p(PERMISSIONS.inventoryUpdate, '调整库存', '商品', 'high'),
  p(PERMISSIONS.orderCreate, '创建订单', '订单'),
  p(PERMISSIONS.orderRead, '查看订单', '订单'),
  p(PERMISSIONS.orderCancel, '取消订单', '订单', 'high'),
  p(PERMISSIONS.orderShip, '订单发货', '订单', 'high'),
  p(PERMISSIONS.orderExport, '导出订单', '订单', 'high'),
  p(PERMISSIONS.afterSaleRead, '查看售后', '售后'),
  p(PERMISSIONS.afterSaleHandle, '处理售后', '售后', 'high'),
  p(PERMISSIONS.orderRefund, '执行退款', '售后', 'critical'),
  p(PERMISSIONS.voucherRead, '查看卡券', '卡券'),
  p(PERMISSIONS.voucherCreate, '创建卡券', '卡券', 'high'),
  p(PERMISSIONS.voucherIssue, '发放卡券', '卡券', 'critical'),
  p(PERMISSIONS.voucherActivate, '激活卡券', '卡券', 'high'),
  p(PERMISSIONS.voucherDisable, '禁用卡券', '卡券', 'high'),
  p(PERMISSIONS.voucherExtend, '延期卡券', '卡券', 'high'),
  p(PERMISSIONS.voucherVoid, '作废卡券', '卡券', 'critical'),
  p(PERMISSIONS.voucherExport, '导出卡券', '卡券', 'critical'),
  p(PERMISSIONS.financeRead, '查看财务', '财务', 'elevated'),
  p(PERMISSIONS.financeReconcile, '财务对账', '财务', 'high'),
  p(PERMISSIONS.financePaymentConfigure, '配置支付渠道', '财务', 'critical'),
  p(PERMISSIONS.financeWithdraw, '申请或执行提现', '财务', 'critical'),
  p(PERMISSIONS.financeSettlementApprove, '审批结算', '财务', 'critical'),
  p(PERMISSIONS.financeInvoiceManage, '管理发票', '财务', 'high'),
  p(PERMISSIONS.financeExport, '导出财务数据', '财务', 'critical'),
  p(PERMISSIONS.analyticsRead, '查看数据统计', '数据'),
  p(PERMISSIONS.analyticsExport, '导出统计数据', '数据', 'high'),
  p(PERMISSIONS.memberRead, '查看会员', '会员'),
  p(PERMISSIONS.memberPiiRead, '查看会员敏感信息', '会员', 'high'),
  p(PERMISSIONS.memberInvite, '邀请会员', '会员', 'high'),
  p(PERMISSIONS.memberUpdate, '编辑会员', '会员', 'high'),
  p(PERMISSIONS.memberDisable, '停用会员', '会员', 'critical'),
  p(PERMISSIONS.memberOffboard, '移除会员', '会员', 'critical'),
  p(PERMISSIONS.memberImport, '批量导入会员', '会员', 'high'),
  p(PERMISSIONS.memberExport, '导出会员', '会员', 'critical'),
  p(PERMISSIONS.memberCodeVerify, '核验会员码', '会员码', 'high'),
  p(PERMISSIONS.roleRead, '查看角色权限', '权限'),
  p(PERMISSIONS.roleCreate, '创建角色', '权限', 'high'),
  p(PERMISSIONS.roleUpdate, '编辑角色', '权限', 'critical'),
  p(PERMISSIONS.roleDelete, '删除角色', '权限', 'critical'),
  p(PERMISSIONS.roleGrant, '授予或撤销角色', '权限', 'critical'),
  p(PERMISSIONS.scopeGrant, '授予数据范围', '权限', 'critical'),
  p(PERMISSIONS.organizationRead, '查看组织', '组织'),
  p(PERMISSIONS.organizationManage, '管理组织部门', '组织', 'high'),
  p(PERMISSIONS.mallRead, '查看商城', '商城'),
  p(PERMISSIONS.mallManage, '管理商城', '商城', 'high'),
  p(PERMISSIONS.mallDecorate, '装修商城', '商城', 'elevated'),
  p(PERMISSIONS.mallPublish, '发布商城版本', '商城', 'high'),
  p(PERMISSIONS.supplierRead, '查看供应商', '供应商'),
  p(PERMISSIONS.supplierManage, '管理供应商', '供应商', 'high'),
  p(PERMISSIONS.storeRead, '查看门店', '门店'),
  p(PERMISSIONS.storeManage, '管理门店', '门店', 'high'),
  p(PERMISSIONS.customerServiceRead, '查看客服记录', '客服'),
  p(PERMISSIONS.customerServiceHandle, '处理客服会话', '客服', 'elevated'),
  p(PERMISSIONS.customerServiceManage, '配置客服规则', '客服', 'high'),
  p(PERMISSIONS.auditRead, '查看审计', '安全'),
  p(PERMISSIONS.auditExport, '导出审计', '安全', 'critical'),
  p(PERMISSIONS.securityPolicyManage, '管理安全策略', '安全', 'critical'),
  p(PERMISSIONS.integrationRead, '查看接口配置', '接口', 'high'),
  p(PERMISSIONS.integrationManageSecrets, '管理接口密钥', '接口', 'critical'),
  p(PERMISSIONS.tenantManage, '管理平台租户', '平台', 'critical'),
];
