import { defineModuleManifest } from '@shop/kernel';
import { NOTIFICATION_CAPABILITIES } from './01_public_gongkai/NotificationCapabilities';

export const notificationManifest = defineModuleManifest({
  id: 'notification',
  version: '1.0.0',
  kind: 'business',
  provides: [NOTIFICATION_CAPABILITIES.read, NOTIFICATION_CAPABILITIES.manage],
  requires: ['identity', 'order', 'support'],
  operations: [
    'notification.notifications.read',
    'notification.preferences.read',
    'notification.preferences.manage',
    'notification.endpoints.manage',
    'notification.templates.manage',
    'notification.templates.read',
    'notification.announcements.read',
    'notification.announcements.manage',
  ],
  publishes: ['notification.delivered'],
  consumes: [
    'payment.succeeded',
    'payment.refunded',
    'payment.late.detected',
    'payment.autorefund.requested',
    'payment.recovery.opened',
    'fulfillment.shipped',
    'voucher.issue.failed',
    'voucher.import.failed',
    'voucher.status.failed',
    'benefit.granted',
    'benefit.expired',
    'benefit.expiry.reminded',
    'benefit.revoked',
    'benefit.grant.failed',
    'benefit.revoke.failed',
    'benefit.expiry.failed',
    'finance.reconciliation.difference',
    'finance.settlement.approved',
    'finance.settlement.adjusted',
    'finance.period.closed',
    'finance.withdrawal.paid',
    'finance.withdrawal.uncertain',
    'invoice.issued',
    'invoice.red.issued',
    'support.message.sent',
    'support.ticket.assigned',
    'support.sla.escalated',
    'channel.refund.changed',
    'catalog.listing.unpublished',
    'risk.case.opened',
    'risk.case.resolved',
    'risk.transaction.blocked',
    'extension.degraded',
  ],
  publicEntry: './index.ts',
  layers: ['public', 'domain', 'application', 'adapters', 'interface', 'tests'],
  entrypoints: {
    http: ['notificationRoutes', 'notificationOperatorReadOperations'],
    jobs: ['notification', 'identitynotification'],
  },
});
