import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { parse } from 'yaml';
import { parseNavigation, type NavigationNode } from './NavigationSchema';
import { validateNavigation, type OperationReference } from './NavigationValidator';

export async function generateNavigation(root: string, check: boolean): Promise<{ readonly hash: string; readonly nodes: number }> {
  const input = await readFile(resolve(root, 'config/navigation.yml'), 'utf8');
  const operations = parse(await readFile(resolve(root, 'packages/contract/definitions/operations.yml'), 'utf8'), { merge: true }) as { readonly operations?: readonly OperationReference[] };
  if (!Array.isArray(operations.operations)) throw new Error('NAVIGATION_OPERATION_CATALOG_INVALID');
  const document = parseNavigation(parse(input));
  const nodes = validateNavigation(document, operations.operations);
  const canonical = JSON.stringify({ version: document.version, nodes });
  const hash = createHash('sha256').update(canonical).digest('hex');
  const outputs = new Map<string, string>([
    [resolve(root, 'services/commerce/src/modules/navigation/infrastructure/catalog/NavigationCatalog.ts'), serverSource(nodes, hash)],
    [
      resolve(root, 'apps/console/src/generated/NavigationBinding.ts'),
      bindingSource(
        nodes.filter(({ surface }) => surface === 'console'),
        hash
      ),
    ],
    [
      resolve(root, 'apps/storefront/src/generated/NavigationBinding.ts'),
      bindingSource(
        nodes.filter(({ surface }) => surface === 'storefront'),
        hash
      ),
    ],
    [resolve(root, 'evidence/navigation/catalog.json'), `${JSON.stringify({ version: 1, hash, nodes }, null, 2)}\n`],
  ]);
  for (const [path, content] of outputs) await emit(path, content, check);
  return Object.freeze({ hash, nodes: nodes.length });
}

function serverSource(nodes: readonly NavigationNode[], hash: string): string {
  return `// Generated by @shop/navigationgen. Do not edit.\nexport const NAVIGATION_CATALOG_HASH = '${hash}' as const;\nconst SOURCE = ${JSON.stringify(nodes, null, 2)} as const;\nexport const NAVIGATION_CATALOG = Object.freeze(SOURCE.map((node) => Object.freeze({ ...node, permissions: Object.freeze([...node.permissions]), capabilities: Object.freeze([...node.capabilities]), requirements: Object.freeze([...node.requirements]) })));\nexport type NavigationNode = typeof NAVIGATION_CATALOG[number];\nexport type NavigationId = NavigationNode['id'];\nexport const NAVIGATION_BY_ID: ReadonlyMap<NavigationId, NavigationNode> = new Map(NAVIGATION_CATALOG.map((node) => [node.id, node]));\n`;
}

function bindingSource(nodes: readonly NavigationNode[], hash: string): string {
  const ids = unique(nodes.map(({ id }) => id));
  const components = unique(nodes.map(({ component }) => component));
  const routes = unique(nodes.map(({ route }) => route));
  const byComponent = Object.fromEntries(nodes.map(({ component, route }) => [component, route]));
  return `// Generated by @shop/navigationgen. Do not edit.\nexport const NAVIGATION_CATALOG_HASH = '${hash}' as const;\nexport const NAVIGATION_IDS = ${JSON.stringify(ids)} as const;\nexport type NavigationId = typeof NAVIGATION_IDS[number];\nexport const COMPONENT_KEYS = ${JSON.stringify(components)} as const;\nexport type ComponentKey = typeof COMPONENT_KEYS[number];\nexport const ROUTE_KEYS = ${JSON.stringify(routes)} as const;\nexport type RouteKey = typeof ROUTE_KEYS[number];\nexport const NAVIGATION_ROUTES = Object.freeze(${JSON.stringify(byComponent)}) as Readonly<Record<ComponentKey, RouteKey>>;\n`;
}

function unique(values: readonly string[]): readonly string[] {
  return [...new Set(values)].sort();
}
async function emit(path: string, content: string, check: boolean): Promise<void> {
  if (check) {
    const current = await readFile(path, 'utf8').catch(() => '');
    if (current !== content) throw new Error(`GENERATED_NAVIGATION_DRIFT:${path}`);
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, 'utf8');
}
