import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, extname, resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { parse } from 'yaml';
import { parseNavigation, type NavigationNode, type RouteDefinition } from './NavigationSchema';
import { validateNavigation, type OperationReference } from './NavigationValidator';

export async function generateNavigation(root: string, check: boolean): Promise<{ readonly hash: string; readonly nodes: number; readonly routes: number }> {
  const input = await readFile(resolve(root, 'config/navigation.yml'), 'utf8');
  const operations = parse(await readFile(resolve(root, 'packages/contract/definitions/operations.yml'), 'utf8'), { merge: true }) as { readonly operations?: readonly OperationReference[] };
  if (!Array.isArray(operations.operations)) throw new Error('NAVIGATION_OPERATION_CATALOG_INVALID');
  const document = parseNavigation(parse(input));
  const validated = validateNavigation(document, operations.operations);
  const canonical = JSON.stringify({ version: document.version, routes: validated.routes, nodes: validated.nodes });
  const hash = createHash('sha256').update(canonical).digest('hex');
  const routeById = new Map(validated.routes.map((route) => [route.id, route]));
  const resolvedNodes = validated.nodes.map((node) => resolveNode(node, routeById));
  const outputs = new Map<string, string>([
    [resolve(root, 'services/commerce/src/modules/navigation/infrastructure/registry/NavigationCatalog.ts'), serverSource(resolvedNodes, hash)],
    [resolve(root, 'apps/auth/src/generated/RouteBinding.ts'), routeBindingSource(validated.routes.filter(({ surface }) => surface === 'auth'), hash)],
    [resolve(root, 'apps/console/src/generated/NavigationBinding.ts'), navigationBindingSource(validated.nodes.filter(({ surface }) => surface === 'console'), routeById, hash)],
    [resolve(root, 'apps/console/src/generated/RouteBinding.ts'), routeBindingSource(validated.routes.filter(({ surface }) => surface === 'console'), hash)],
    [resolve(root, 'apps/storefront/src/generated/NavigationBinding.ts'), navigationBindingSource(validated.nodes.filter(({ surface }) => surface === 'storefront'), routeById, hash)],
    [resolve(root, 'apps/storefront/src/generated/RouteBinding.ts'), routeBindingSource(validated.routes.filter(({ surface }) => surface === 'storefront'), hash)],
    [resolve(root, 'packages/config/src/RouteCatalog.ts'), sharedRouteCatalogSource(validated.routes, hash)],
    [resolve(root, 'evidence/navigation/catalog.json'), `${JSON.stringify({ version: 2, hash, routes: validated.routes, nodes: resolvedNodes }, null, 2)}\n`],
  ]);
  for (const [path, content] of outputs) {
    const generated = extname(path) === '.ts' ? await format(content, { ...(await resolveConfig(path)), parser: 'typescript' }) : content;
    await emit(path, generated, check);
  }
  return Object.freeze({ hash, nodes: validated.nodes.length, routes: validated.routes.length });
}

interface ResolvedNode extends NavigationNode {
  readonly route: string;
  readonly component: string;
}

function resolveNode(node: NavigationNode, routeById: ReadonlyMap<string, RouteDefinition>): ResolvedNode {
  const route = routeById.get(node.routeid);
  if (route === undefined) throw new Error(`NAVIGATION_ROUTE_UNKNOWN:${node.routeid}`);
  return Object.freeze({ ...node, route: route.path, component: route.feature });
}

function serverSource(nodes: readonly ResolvedNode[], hash: string): string {
  return `// Generated by @shop/navigationgen. Do not edit.\nexport const NAVIGATION_CATALOG_HASH = '${hash}' as const;\nconst SOURCE = ${JSON.stringify(nodes, null, 2)} as const;\nexport const NAVIGATION_CATALOG = Object.freeze(SOURCE.map((node) => Object.freeze({ ...node, permissions: Object.freeze([...node.permissions]), capabilities: Object.freeze([...node.capabilities]), requirements: Object.freeze([...node.requirements]) })));\nexport type NavigationNode = typeof NAVIGATION_CATALOG[number];\nexport type NavigationId = NavigationNode['id'];\nexport const NAVIGATION_BY_ID: ReadonlyMap<NavigationId, NavigationNode> = new Map(NAVIGATION_CATALOG.map((node) => [node.id, node]));\n`;
}

function navigationBindingSource(nodes: readonly NavigationNode[], routeById: ReadonlyMap<string, RouteDefinition>, hash: string): string {
  const ids = unique(nodes.map(({ id }) => id));
  const features = unique(nodes.map(({ routeid }) => requiredRoute(routeById, routeid).feature));
  const routeids = unique(nodes.map(({ routeid }) => routeid));
  const byFeature = Object.fromEntries(nodes.map(({ routeid }) => {
    const route = requiredRoute(routeById, routeid);
    return [route.feature, route.path];
  }));
  return `// Generated by @shop/navigationgen. Do not edit.\nexport const NAVIGATION_CATALOG_HASH = '${hash}' as const;\nexport const NAVIGATION_IDS = ${JSON.stringify(ids)} as const;\nexport type NavigationId = typeof NAVIGATION_IDS[number];\nexport const COMPONENT_KEYS = ${JSON.stringify(features)} as const;\nexport type ComponentKey = typeof COMPONENT_KEYS[number];\nexport const NAVIGATION_ROUTE_IDS = ${JSON.stringify(routeids)} as const;\nexport type NavigationRouteId = typeof NAVIGATION_ROUTE_IDS[number];\nexport const NAVIGATION_ROUTES = Object.freeze(${JSON.stringify(byFeature)}) as Readonly<Record<ComponentKey, string>>;\n`;
}

function routeBindingSource(routes: readonly RouteDefinition[], hash: string): string {
  const entries = Object.fromEntries(routes.map(({ id, path }) => [id, path]));
  const requirements = Object.fromEntries(routes.map(({ id, requirements: ids }) => [id, ids]));
  const features = Object.fromEntries(routes.map(({ id, feature }) => [id, feature]));
  return `// Generated by @shop/navigationgen. Do not edit.\nexport const ROUTE_CATALOG_HASH = '${hash}' as const;\nexport const ROUTES = ${JSON.stringify(entries)} as const;\nexport type RouteId = keyof typeof ROUTES;\nexport type RoutePath = (typeof ROUTES)[RouteId];\nexport const ROUTE_REQUIREMENTS = Object.freeze(${JSON.stringify(requirements)}) as Readonly<Record<RouteId, readonly string[]>>;\nexport const ROUTE_FEATURES = Object.freeze(${JSON.stringify(features)}) as Readonly<Record<RouteId, string>>;\nexport function routePath(route: RouteId): RoutePath { return ROUTES[route]; }\n`;
}

function sharedRouteCatalogSource(routes: readonly RouteDefinition[], hash: string): string {
  return `// Generated by @shop/navigationgen. Do not edit.\nexport const ROUTE_CATALOG_HASH = '${hash}' as const;\nexport const ROUTE_CATALOG = Object.freeze(${JSON.stringify(routes, null, 2)}.map((route) => Object.freeze({ ...route, requirements: Object.freeze([...route.requirements]) })));\nexport type RouteDefinition = (typeof ROUTE_CATALOG)[number];\nexport type RouteId = RouteDefinition['id'];\nexport const ROUTE_BY_ID: ReadonlyMap<RouteId, RouteDefinition> = new Map(ROUTE_CATALOG.map((route) => [route.id, route]));\n`;
}

function requiredRoute(routes: ReadonlyMap<string, RouteDefinition>, id: string): RouteDefinition {
  const route = routes.get(id);
  if (route === undefined) throw new Error(`NAVIGATION_ROUTE_UNKNOWN:${id}`);
  return route;
}

function unique(values: readonly string[]): readonly string[] {
  return [...new Set(values)].sort();
}

async function emit(path: string, content: string, check: boolean): Promise<void> {
  if (check) {
    const current = await readFile(path, 'utf8').catch(() => '');
    if (current !== content) throw new Error(`GENERATED_NAVIGATION_DRIFT:${path}`);
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, 'utf8');
}
