import { array, literal, null as nullSchema, optional, strictObject, string, union } from 'zod/mini';
import { catalogListingsBatchInput, catalogListingsBatchOutput } from './CatalogBatchSchema';
import { importCreated, importInput, importRead } from './ImportSchema';
import { ContractJsonValueSchema } from './JsonSchema';
import { ImageAssetInputSchema, ImageAssetUploadInputSchema, ImageAssetUploadOutputSchema } from './ObjectSchema';
import { isoUtc, pageOutput, pageQuery, unsigned, version as entityVersion } from './Primitives';
import {
  category,
  dependency,
  detailSection,
  facet,
  integer,
  listing,
  listingPrice,
  listingRead,
  listingRecord,
  nullableText,
  pool,
  poolBinding,
  poolRead,
  price,
  product,
  productChannel,
  productMedia,
  productPool,
  productQualification,
  productTimeline,
  sku,
  sourceRead,
  stock,
  text,
} from './CatalogEntitySchema';
export const CATALOG_QUERY_SCHEMAS = {
  CatalogPoolsReadInput: strictObject(pageQuery),
  CatalogCategoriesReadInput: strictObject({ ...pageQuery, q: optional(string()) }),
  CatalogProductDetailReadInput: strictObject({ section: detailSection }),
  CatalogListingsReadInput: strictObject({
    ...pageQuery,
    q: optional(string()),
    category: optional(string()),
    product: optional(string()),
    pool: optional(string()),
    supplier: optional(string()),
    mall: optional(string()),
    status: optional(string()),
  }),
  CatalogFacetsReadInput: strictObject({ q: optional(string()) }),
  CatalogImportsReadInput: strictObject({}),
} as const;

export const CATALOG_BODY_SCHEMAS = {
  CatalogPoolsAttachInput: strictObject({}),
  CatalogPoolsDetachInput: strictObject({}),
  CatalogPoolsAllocateInput: strictObject({ scope: string(), kind: optional(literal(['channel', 'markup'])), name: string() }),
  CatalogCategoriesCreateInput: strictObject({ name: string(), parent: optional(union([string(), nullSchema()])), sort: optional(unsigned) }),
  CatalogProductsCreateInput: strictObject({
    owner: optional(union([string(), nullSchema()])),
    brand: optional(union([string(), nullSchema()])),
    category: string(),
    title: string(),
    type: optional(literal(['physical', 'virtual', 'service', 'voucher'])),
    attributes: optional(ContractJsonValueSchema),
    image: optional(ImageAssetInputSchema),
  }),
  CatalogProductsUpdateInput: strictObject({
    title: optional(string()),
    category: optional(string()),
    attributes: optional(ContractJsonValueSchema),
    image: optional(union([ImageAssetInputSchema, nullSchema()])),
    status: optional(literal(['draft', 'review', 'active', 'archived'])),
  }),
  CatalogMediauploadsCreateInput: ImageAssetUploadInputSchema,
  CatalogProductsArchiveInput: strictObject({}),
  CatalogListingsPublishInput: strictObject({}),
  CatalogListingsUnpublishInput: strictObject({}),
  CatalogListingsPriceSetInput: strictObject({ amountMinor: unsigned, currency: optional(literal('CNY')) }),
  CatalogListingsPoolSetInput: strictObject({ pool: nullableText }),
  CatalogListingsBatchInput: catalogListingsBatchInput,
  CatalogImportsCreateInput: importInput,
} as const;

export const CATALOG_OUTPUT_SCHEMAS = {
  CatalogPoolsReadOutput: pageOutput(poolRead),
  CatalogCategoriesReadOutput: pageOutput(category),
  CatalogCategoriesCreateOutput: category,
  CatalogPoolsAttachOutput: poolBinding,
  CatalogPoolsDetachOutput: poolBinding,
  CatalogPoolsAllocateOutput: pool,
  CatalogProductDetailReadOutput: strictObject({
    section: detailSection,
    id: text,
    title: text,
    description: nullableText,
    product_type: literal(['physical', 'virtual', 'service', 'voucher']),
    status: literal(['draft', 'review', 'active', 'archived']),
    version: integer,
    category_id: text,
    category_name: text,
    brand_id: nullableText,
    brand_name: nullableText,
    owner_partner_id: nullableText,
    owner_partner_name: nullableText,
    cover_url: nullableText,
    subtitle: nullableText,
    createdAt: isoUtc,
    updatedAt: isoUtc,
    skus: array(sku),
    listings: array(listing),
    media: array(productMedia),
    channels: array(productChannel),
    pools: array(productPool),
    timeline: array(productTimeline),
    inventory: array(stock),
    prices: array(price),
    qualifications: array(productQualification),
    dependencies: strictObject({ catalog: dependency, inventory: dependency, pricing: dependency, qualification: dependency }),
    gaps: array(strictObject({ dependency: literal(['inventory', 'pricing', 'qualification']), code: text })),
  }),
  CatalogProductsCreateOutput: product,
  CatalogProductsUpdateOutput: product,
  CatalogMediauploadsCreateOutput: ImageAssetUploadOutputSchema,
  CatalogProductsArchiveOutput: product,
  CatalogListingsReadOutput: pageOutput(union([listingRead, sourceRead])),
  CatalogFacetsReadOutput: strictObject({ categories: array(facet), suppliers: array(facet), malls: array(facet), statuses: array(facet) }),
  CatalogListingsPublishOutput: listingRecord,
  CatalogListingsUnpublishOutput: listingRecord,
  CatalogListingsPriceSetOutput: listingPrice,
  CatalogListingsPoolSetOutput: listingRecord,
  CatalogListingsBatchOutput: catalogListingsBatchOutput,
  CatalogImportsCreateOutput: importCreated,
  CatalogImportsReadOutput: importRead,
} as const;
