import { array, boolean, discriminatedUnion, literal, minLength, optional, strictObject, string, union } from 'zod/mini';
import { FINANCE_RECONCILIATION_STATES, FINANCE_REPAIR_DECISIONS } from '../Vocabulary';
import { adjustment, backfill, exportResult, financePolicy, hold, period, periodClose, settlement, settlementRead, withdrawal } from './FinanceSettlementSchema';
import { importCreated, importInput, importRead } from './ImportSchema';
import { ContractJsonValueSchema } from './JsonSchema';
import { currency, expectedVersion, id, integer, isoUtc, pageOutput, pageQuery, unsigned, version } from './Primitives';
import {
  auditEvidence,
  auditEvent,
  auditFact,
  auditReference,
  entry,
  facetGroup,
  ledgerEntry,
  nullableTime,
  overview,
  policy,
  policyDraft,
  providerFacetGroup,
  reconciliation,
  reconciliationRead,
  repair,
  repairDraft,
  repairReason,
  repairStatus,
  resolvedItem,
  statement,
} from './FinanceEntitySchema';
export const FINANCE_QUERY_SCHEMAS = {
  FinanceOverviewReadInput: strictObject({}),
  FinanceFacetsReadInput: strictObject({}),
  FinanceAuditReadInput: strictObject({ reference: auditReference }),
  FinanceEntriesReadInput: strictObject(pageQuery),
  FinanceStatementsReadInput: strictObject(pageQuery),
  FinanceStatementimportsReadInput: strictObject({}),
  FinanceReconciliationsReadInput: strictObject({
    ...pageQuery,
    period: optional(string()),
    provider: optional(string()),
    mall: optional(string()),
    state: optional(literal(FINANCE_RECONCILIATION_STATES)),
    differenceType: optional(string()),
  }),
  FinanceSettlementsReadInput: strictObject(pageQuery),
  FinanceWithdrawalsReadInput: strictObject(pageQuery),
  FinanceHoldsReadInput: strictObject(pageQuery),
  FinancePeriodsReadInput: strictObject(pageQuery),
  FinanceBackfillsReadInput: strictObject(pageQuery),
  FinancePoliciesReadInput: strictObject({ ...pageQuery, status: optional(literal(['draft', 'active', 'retired'])) }),
  FinanceReconciliationrepairsReadInput: strictObject({ ...pageQuery, status: optional(repairStatus), statementId: optional(id<'statement'>()) }),
} as const;

export const FINANCE_BODY_SCHEMAS = {
  FinanceStatementimportsCreateInput: strictObject({ ...importInput.shape, provider: string(), partnerId: string(), periodStart: string(), periodEnd: string(), currency, openingMinor: integer, closingMinor: integer }),
  FinanceStatementsExportInput: strictObject({ periodStart: optional(string()), periodEnd: optional(string()), currency: optional(currency), state: optional(literal(['draft', 'final'])) }),
  FinanceReconciliationsManageInput: discriminatedUnion('action', [
    strictObject({ action: literal('retry'), reason: string(), evidence: optional(ContractJsonValueSchema) }),
    strictObject({ action: literal(['resolve', 'approveitem']), item: string(), reason: string(), evidence: optional(ContractJsonValueSchema) }),
    strictObject({ action: literal('approve'), reason: string(), evidence: optional(ContractJsonValueSchema) }),
  ]),
  FinanceSettlementsDecideInput: strictObject({ decision: literal(['approved', 'rejected']), reason: string(), evidence: optional(ContractJsonValueSchema) }),
  FinanceSettlementsAdjustInput: discriminatedUnion('action', [
    strictObject({ action: literal('request'), line: string(), direction: literal(['increase', 'decrease']), amountMinor: unsigned, taxMinor: optional(unsigned), reason: string(), evidence: optional(ContractJsonValueSchema) }),
    strictObject({ action: literal(['approve', 'reject']), adjustment: string(), reason: string(), evidence: optional(ContractJsonValueSchema) }),
  ]),
  FinanceWithdrawalsCreateInput: strictObject({ settlement: string(), amountMinor: unsigned, destinationRef: string(), reason: string(), evidence: optional(ContractJsonValueSchema) }),
  FinanceWithdrawalsDecideInput: strictObject({ decision: literal(['approved', 'rejected']), reason: string(), evidence: optional(ContractJsonValueSchema) }),
  FinanceWithdrawalsRecoverInput: strictObject({ reason: string(), evidence: optional(ContractJsonValueSchema) }),
  FinancePeriodsManageInput: strictObject({ action: literal(['request', 'approve', 'reject']), reason: string(), evidence: optional(ContractJsonValueSchema) }),
  FinanceBackfillsDecideInput: strictObject({ decision: literal(['approved', 'rejected']), reason: string(), evidence: optional(ContractJsonValueSchema) }),
  FinancePoliciesManageInput: strictObject({ kind: string(), rule: ContractJsonValueSchema }),
  FinancePoliciesPreviewInput: strictObject({ ...policyDraft, expectedVersion, sampleFrom: isoUtc, sampleTo: isoUtc }),
  FinanceReconciliationrepairsPreviewInput: strictObject(repairDraft),
  FinanceReconciliationrepairsSubmitInput: strictObject({ previewToken: string(), previewHash: string(), expectedVersion }),
  FinanceReconciliationrepairsDecideInput: discriminatedUnion('decision', [
    strictObject({ decision: literal(FINANCE_REPAIR_DECISIONS[0]), approvalProof: string().check(minLength(1)), expectedVersion, reason: repairReason }),
    strictObject({ decision: literal(FINANCE_REPAIR_DECISIONS[1]), expectedVersion, reason: repairReason }),
  ]),
  FinanceReconciliationrepairsReverseInput: strictObject({ expectedVersion, reason: repairReason }),
} as const;

export const FINANCE_OUTPUT_SCHEMAS = {
  FinanceOverviewReadOutput: strictObject({ items: array(overview) }),
  FinanceFacetsReadOutput: strictObject({ periods: facetGroup, providers: providerFacetGroup, malls: facetGroup, states: facetGroup, differenceTypes: facetGroup, watermark: nullableTime }),
  FinanceAuditReadOutput: strictObject({ reference: auditReference, facts: array(auditFact), events: array(auditEvent), records: array(auditEvidence), watermark: nullableTime }),
  FinanceEntriesReadOutput: pageOutput(ledgerEntry),
  FinanceStatementsReadOutput: pageOutput(statement),
  FinanceStatementimportsCreateOutput: importCreated,
  FinanceStatementimportsReadOutput: importRead,
  FinanceStatementsExportOutput: exportResult,
  FinanceReconciliationsManageOutput: union([reconciliation, resolvedItem]),
  FinanceReconciliationsReadOutput: pageOutput(reconciliationRead),
  FinanceSettlementsReadOutput: pageOutput(settlementRead),
  FinanceSettlementsDecideOutput: settlement,
  FinanceSettlementsAdjustOutput: adjustment,
  FinanceWithdrawalsReadOutput: pageOutput(withdrawal),
  FinanceWithdrawalsCreateOutput: withdrawal,
  FinanceWithdrawalsDecideOutput: withdrawal,
  FinanceWithdrawalsRecoverOutput: withdrawal,
  FinanceHoldsReadOutput: pageOutput(hold),
  FinancePeriodsReadOutput: pageOutput(period),
  FinancePeriodsManageOutput: periodClose,
  FinanceBackfillsReadOutput: pageOutput(backfill),
  FinanceBackfillsDecideOutput: backfill,
  FinancePoliciesManageOutput: financePolicy,
  FinancePoliciesReadOutput: pageOutput(policy),
  FinancePoliciesPreviewOutput: strictObject({ policy, balanced: boolean(), affectedCount: unsigned, sampleEntries: array(entry), previewToken: string(), previewHash: string(), expiresAt: isoUtc }),
  FinanceReconciliationrepairsReadOutput: pageOutput(repair),
  FinanceReconciliationrepairsPreviewOutput: strictObject({ repair, balanced: boolean(), previewToken: string(), previewHash: string(), expiresAt: isoUtc }),
  FinanceReconciliationrepairsSubmitOutput: repair,
  FinanceReconciliationrepairsDecideOutput: repair,
  FinanceReconciliationrepairsReverseOutput: repair,
} as const;
