import { SECURITY_OUTPUT_SCHEMAS } from './AccessSchema';
import { AUDIT_OUTPUT_SCHEMAS, AUDIT_QUERY_SCHEMAS } from './AuditSchema';
import { BENEFIT_BODY_SCHEMAS, BENEFIT_OUTPUT_SCHEMAS, BENEFIT_QUERY_SCHEMAS } from './BenefitSchema';
import { CART_BODY_SCHEMAS, CART_OUTPUT_SCHEMAS, CART_QUERY_SCHEMAS } from './CartSchema';
import { CHANNEL_BODY_SCHEMAS, CHANNEL_OUTPUT_SCHEMAS, CHANNEL_QUERY_SCHEMAS } from './ChannelSchema';
import { CATALOG_BODY_SCHEMAS, CATALOG_OUTPUT_SCHEMAS, CATALOG_QUERY_SCHEMAS } from './CatalogSchema';
import { CHECKOUT_BODY_SCHEMAS, CHECKOUT_OUTPUT_SCHEMAS, CHECKOUT_QUERY_SCHEMAS } from './CheckoutSchema';
import { EXPERIENCE_BODY_SCHEMAS, EXPERIENCE_OUTPUT_SCHEMAS, EXPERIENCE_QUERY_SCHEMAS } from './ExperienceSchema';
import { EXTENSION_OUTPUT_SCHEMAS, EXTENSION_QUERY_SCHEMAS } from './ExtensionSchema';
import { FINANCE_BODY_SCHEMAS, FINANCE_OUTPUT_SCHEMAS, FINANCE_QUERY_SCHEMAS } from './FinanceSchema';
import { FULFILLMENT_BODY_SCHEMAS, FULFILLMENT_OUTPUT_SCHEMAS, FULFILLMENT_QUERY_SCHEMAS } from './FulfillmentSchema';
import { IDENTITY_OUTPUT_SCHEMAS } from './IdentitySchema';
import { INVENTORY_BODY_SCHEMAS, INVENTORY_OUTPUT_SCHEMAS, INVENTORY_QUERY_SCHEMAS } from './InventorySchema';
import { INVOICE_BODY_SCHEMAS, INVOICE_OUTPUT_SCHEMAS, INVOICE_QUERY_SCHEMAS } from './InvoiceSchema';
import { MARKETING_OUTPUT_SCHEMAS, MARKETING_QUERY_SCHEMAS } from './MarketingSchema';
import { MEMBER_BODY_SCHEMAS, MEMBER_OUTPUT_SCHEMAS, MEMBER_QUERY_SCHEMAS } from './MemberSchema';
import { NOTIFICATION_BODY_SCHEMAS, NOTIFICATION_OUTPUT_SCHEMAS, NOTIFICATION_QUERY_SCHEMAS } from './NotificationSchema';
import { OBSERVABILITY_BODY_SCHEMAS, OBSERVABILITY_OUTPUT_SCHEMAS, OBSERVABILITY_QUERY_SCHEMAS } from './ObservabilitySchema';
import { ORGANIZATION_BODY_SCHEMAS, ORGANIZATION_OUTPUT_SCHEMAS, ORGANIZATION_QUERY_SCHEMAS } from './OrganizationSchema';
import { ORDER_BODY_SCHEMAS, ORDER_OUTPUT_SCHEMAS, ORDER_QUERY_SCHEMAS } from './OrderSchema';
import { PAYMENT_BODY_SCHEMAS, PAYMENT_OUTPUT_SCHEMAS, PAYMENT_QUERY_SCHEMAS } from './PaymentSchema';
import { PARTNER_BODY_SCHEMAS, PARTNER_OUTPUT_SCHEMAS, PARTNER_QUERY_SCHEMAS } from './PartnerSchema';
import { QUALIFICATION_BODY_SCHEMAS, QUALIFICATION_OUTPUT_SCHEMAS, QUALIFICATION_QUERY_SCHEMAS } from './QualificationSchema';
import { PRICING_BODY_SCHEMAS, PRICING_OUTPUT_SCHEMAS, PRICING_QUERY_SCHEMAS } from './PricingSchema';
import { REFERRAL_BODY_SCHEMAS, REFERRAL_OUTPUT_SCHEMAS, REFERRAL_QUERY_SCHEMAS } from './ReferralSchema';
import { REPORTING_BODY_SCHEMAS, REPORTING_OUTPUT_SCHEMAS, REPORTING_QUERY_SCHEMAS } from './ReportingSchema';
import { RISK_BODY_SCHEMAS, RISK_OUTPUT_SCHEMAS, RISK_QUERY_SCHEMAS } from './RiskSchema';
import { RUNTIME_OUTPUT_SCHEMAS, RUNTIME_QUERY_SCHEMAS } from './RuntimeSchema';
import { SUPPORT_BODY_SCHEMAS, SUPPORT_OUTPUT_SCHEMAS, SUPPORT_QUERY_SCHEMAS } from './SupportSchema';
import { VOUCHER_BODY_SCHEMAS, VOUCHER_OUTPUT_SCHEMAS, VOUCHER_QUERY_SCHEMAS } from './VoucherSchema';
import { VERIFICATION_BODY_SCHEMAS, VERIFICATION_OUTPUT_SCHEMAS, VERIFICATION_QUERY_SCHEMAS } from './VerificationSchema';
import { STOREFRONT_OUTPUT_SCHEMAS, STOREFRONT_QUERY_SCHEMAS } from './StorefrontSchema';

export const OPERATION_BODY_SCHEMAS = Object.freeze({
  ...BENEFIT_BODY_SCHEMAS,
  ...CART_BODY_SCHEMAS,
  ...CATALOG_BODY_SCHEMAS,
  ...CHANNEL_BODY_SCHEMAS,
  ...CHECKOUT_BODY_SCHEMAS,
  ...EXPERIENCE_BODY_SCHEMAS,
  ...FINANCE_BODY_SCHEMAS,
  ...FULFILLMENT_BODY_SCHEMAS,
  ...INVENTORY_BODY_SCHEMAS,
  ...INVOICE_BODY_SCHEMAS,
  ...MEMBER_BODY_SCHEMAS,
  ...NOTIFICATION_BODY_SCHEMAS,
  ...OBSERVABILITY_BODY_SCHEMAS,
  ...ORGANIZATION_BODY_SCHEMAS,
  ...ORDER_BODY_SCHEMAS,
  ...PARTNER_BODY_SCHEMAS,
  ...PAYMENT_BODY_SCHEMAS,
  ...PRICING_BODY_SCHEMAS,
  ...QUALIFICATION_BODY_SCHEMAS,
  ...REFERRAL_BODY_SCHEMAS,
  ...REPORTING_BODY_SCHEMAS,
  ...RISK_BODY_SCHEMAS,
  ...SUPPORT_BODY_SCHEMAS,
  ...VERIFICATION_BODY_SCHEMAS,
  ...VOUCHER_BODY_SCHEMAS,
});
export const OPERATION_QUERY_SCHEMAS = Object.freeze({
  ...STOREFRONT_QUERY_SCHEMAS,
  ...AUDIT_QUERY_SCHEMAS,
  ...BENEFIT_QUERY_SCHEMAS,
  ...CART_QUERY_SCHEMAS,
  ...CATALOG_QUERY_SCHEMAS,
  ...CHANNEL_QUERY_SCHEMAS,
  ...CHECKOUT_QUERY_SCHEMAS,
  ...EXPERIENCE_QUERY_SCHEMAS,
  ...EXTENSION_QUERY_SCHEMAS,
  ...FINANCE_QUERY_SCHEMAS,
  ...FULFILLMENT_QUERY_SCHEMAS,
  ...INVENTORY_QUERY_SCHEMAS,
  ...INVOICE_QUERY_SCHEMAS,
  ...MARKETING_QUERY_SCHEMAS,
  ...MEMBER_QUERY_SCHEMAS,
  ...NOTIFICATION_QUERY_SCHEMAS,
  ...OBSERVABILITY_QUERY_SCHEMAS,
  ...ORGANIZATION_QUERY_SCHEMAS,
  ...ORDER_QUERY_SCHEMAS,
  ...PARTNER_QUERY_SCHEMAS,
  ...PAYMENT_QUERY_SCHEMAS,
  ...PRICING_QUERY_SCHEMAS,
  ...QUALIFICATION_QUERY_SCHEMAS,
  ...REFERRAL_QUERY_SCHEMAS,
  ...REPORTING_QUERY_SCHEMAS,
  ...RISK_QUERY_SCHEMAS,
  ...RUNTIME_QUERY_SCHEMAS,
  ...SUPPORT_QUERY_SCHEMAS,
  ...VERIFICATION_QUERY_SCHEMAS,
  ...VOUCHER_QUERY_SCHEMAS,
});
export const OPERATION_OUTPUT_SCHEMAS = Object.freeze({
  ...STOREFRONT_OUTPUT_SCHEMAS,
  ...SECURITY_OUTPUT_SCHEMAS,
  ...AUDIT_OUTPUT_SCHEMAS,
  ...CATALOG_OUTPUT_SCHEMAS,
  ...CHANNEL_OUTPUT_SCHEMAS,
  ...EXPERIENCE_OUTPUT_SCHEMAS,
  ...EXTENSION_OUTPUT_SCHEMAS,
  ...IDENTITY_OUTPUT_SCHEMAS,
  ...INVENTORY_OUTPUT_SCHEMAS,
  ...INVOICE_OUTPUT_SCHEMAS,
  ...MARKETING_OUTPUT_SCHEMAS,
  ...MEMBER_OUTPUT_SCHEMAS,
  ...NOTIFICATION_OUTPUT_SCHEMAS,
  ...OBSERVABILITY_OUTPUT_SCHEMAS,
  ...ORGANIZATION_OUTPUT_SCHEMAS,
  ...PARTNER_OUTPUT_SCHEMAS,
  ...PRICING_OUTPUT_SCHEMAS,
  ...QUALIFICATION_OUTPUT_SCHEMAS,
  ...RUNTIME_OUTPUT_SCHEMAS,
  ...BENEFIT_OUTPUT_SCHEMAS,
  ...CART_OUTPUT_SCHEMAS,
  ...CHECKOUT_OUTPUT_SCHEMAS,
  ...FINANCE_OUTPUT_SCHEMAS,
  ...FULFILLMENT_OUTPUT_SCHEMAS,
  ...ORDER_OUTPUT_SCHEMAS,
  ...PAYMENT_OUTPUT_SCHEMAS,
  ...REFERRAL_OUTPUT_SCHEMAS,
  ...REPORTING_OUTPUT_SCHEMAS,
  ...RISK_OUTPUT_SCHEMAS,
  ...SUPPORT_OUTPUT_SCHEMAS,
  ...VERIFICATION_OUTPUT_SCHEMAS,
  ...VOUCHER_OUTPUT_SCHEMAS,
});
