// Generated from config/clients.yml and definitions/operations.yml. Do not edit.
import { ApiClient } from './ApiClient';
import { FetchTransport } from './FetchTransport';
import type { OperationExecutor } from './OperationDescriptor';
import type { AuthSurfaceClient } from './SurfaceCatalog';
import { bindSessionsCreate as bindIdentitySessionsCreate, bindSessionsComplete as bindIdentitySessionsComplete, bindTicketsExchange as bindIdentityTicketsExchange, bindSessionRead as bindIdentitySessionRead, bindSessionDelete as bindIdentitySessionDelete, bindSessionsRead as bindIdentitySessionsRead, bindSessionsRevoke as bindIdentitySessionsRevoke, bindMembershipsRead as bindIdentityMembershipsRead, bindMembershipsSwitch as bindIdentityMembershipsSwitch, bindChallengesCreate as bindIdentityChallengesCreate, bindMobileChallengesCreate as bindIdentityMobileChallengesCreate, bindInvitationsResolve as bindIdentityInvitationsResolve, bindEnrollmentsRead as bindIdentityEnrollmentsRead, bindEnrollmentsComplete as bindIdentityEnrollmentsComplete, bindPasswordChange as bindIdentityPasswordChange, bindPasswordVerify as bindIdentityPasswordVerify, bindPasswordReset as bindIdentityPasswordReset, bindMobileManage as bindIdentityMobileManage, bindStepupStart as bindIdentityStepupStart, bindStepupComplete as bindIdentityStepupComplete, bindStepupDisable as bindIdentityStepupDisable, bindBootstrapRead as bindIdentityBootstrapRead, bindProvidersRead as bindIdentityProvidersRead, bindFederationsStart as bindIdentityFederationsStart, bindFederationsCallback as bindIdentityFederationsCallback, bindFederationsSelectionRead as bindIdentityFederationsSelectionRead, bindFederationsComplete as bindIdentityFederationsComplete, bindLinksRead as bindIdentityLinksRead, bindLinksCreate as bindIdentityLinksCreate, bindLinksRevoke as bindIdentityLinksRevoke } from './operations/identity';

export function createAuthClient(executor: OperationExecutor): AuthSurfaceClient {
  return Object.freeze({
    identity: Object.freeze({ sessionsCreate: bindIdentitySessionsCreate(executor), sessionsComplete: bindIdentitySessionsComplete(executor), ticketsExchange: bindIdentityTicketsExchange(executor), sessionRead: bindIdentitySessionRead(executor), sessionDelete: bindIdentitySessionDelete(executor), sessionsRead: bindIdentitySessionsRead(executor), sessionsRevoke: bindIdentitySessionsRevoke(executor), membershipsRead: bindIdentityMembershipsRead(executor), membershipsSwitch: bindIdentityMembershipsSwitch(executor), challengesCreate: bindIdentityChallengesCreate(executor), mobileChallengesCreate: bindIdentityMobileChallengesCreate(executor), invitationsResolve: bindIdentityInvitationsResolve(executor), enrollmentsRead: bindIdentityEnrollmentsRead(executor), enrollmentsComplete: bindIdentityEnrollmentsComplete(executor), passwordChange: bindIdentityPasswordChange(executor), passwordVerify: bindIdentityPasswordVerify(executor), passwordReset: bindIdentityPasswordReset(executor), mobileManage: bindIdentityMobileManage(executor), stepupStart: bindIdentityStepupStart(executor), stepupComplete: bindIdentityStepupComplete(executor), stepupDisable: bindIdentityStepupDisable(executor), bootstrapRead: bindIdentityBootstrapRead(executor), providersRead: bindIdentityProvidersRead(executor), federationsStart: bindIdentityFederationsStart(executor), federationsCallback: bindIdentityFederationsCallback(executor), federationsSelectionRead: bindIdentityFederationsSelectionRead(executor), federationsComplete: bindIdentityFederationsComplete(executor), linksRead: bindIdentityLinksRead(executor), linksCreate: bindIdentityLinksCreate(executor), linksRevoke: bindIdentityLinksRevoke(executor) }),
  });
}

export function createFetchAuth(baseUrl: string): AuthSurfaceClient {
  return createAuthClient(new ApiClient(baseUrl, new FetchTransport()));
}
