// Generated from config/clients.yml and definitions/operations.yml. Do not edit.
import { ApiClient } from './ApiClient';
import { FetchTransport } from './FetchTransport';
import type { OperationExecutor } from './OperationDescriptor';
import type { StoreSurfaceClient } from './SurfaceCatalog';
import { bindSessionsCreate as bindIdentitySessionsCreate, bindSessionsComplete as bindIdentitySessionsComplete, bindTicketsExchange as bindIdentityTicketsExchange, bindSessionRead as bindIdentitySessionRead, bindSessionDelete as bindIdentitySessionDelete, bindHandoversRead as bindIdentityHandoversRead, bindHandoversCreate as bindIdentityHandoversCreate, bindSessionsRead as bindIdentitySessionsRead, bindSessionsRevoke as bindIdentitySessionsRevoke, bindMembershipsRead as bindIdentityMembershipsRead, bindMembershipsSwitch as bindIdentityMembershipsSwitch, bindChallengesCreate as bindIdentityChallengesCreate, bindMobileChallengesCreate as bindIdentityMobileChallengesCreate, bindInvitationsResolve as bindIdentityInvitationsResolve, bindEnrollmentsRead as bindIdentityEnrollmentsRead, bindEnrollmentsComplete as bindIdentityEnrollmentsComplete, bindPasswordChange as bindIdentityPasswordChange, bindPasswordVerify as bindIdentityPasswordVerify, bindPasswordReset as bindIdentityPasswordReset, bindMobileManage as bindIdentityMobileManage, bindStepupStart as bindIdentityStepupStart, bindStepupComplete as bindIdentityStepupComplete, bindStepupDisable as bindIdentityStepupDisable, bindBootstrapRead as bindIdentityBootstrapRead, bindProvidersRead as bindIdentityProvidersRead, bindFederationsStart as bindIdentityFederationsStart, bindFederationsCallback as bindIdentityFederationsCallback, bindFederationsSelectionRead as bindIdentityFederationsSelectionRead, bindFederationsComplete as bindIdentityFederationsComplete, bindLinksRead as bindIdentityLinksRead, bindLinksCreate as bindIdentityLinksCreate, bindLinksRevoke as bindIdentityLinksRevoke } from './operations/identity';
import { bindLayersRead as bindOrganizationLayersRead, bindStoresRead as bindOrganizationStoresRead } from './operations/organization';
import { bindAssignmentsRead as bindCapabilityAssignmentsRead } from './operations/capability';
import { bindProfileRead as bindMemberProfileRead } from './operations/member';
import { bindOffersRead as bindPricingOffersRead } from './operations/pricing';
import { bindAvailabilityRead as bindInventoryAvailabilityRead, bindAdjustmentsRead as bindInventoryAdjustmentsRead, bindAdjustmentsCreate as bindInventoryAdjustmentsCreate } from './operations/inventory';
import { bindPublishedRead as bindExperiencePublishedRead } from './operations/experience';
import { bindOrdersCancel as bindOrderOrdersCancel, bindOrdersRead as bindOrderOrdersRead, bindDetailRead as bindOrderDetailRead, bindRemindersCreate as bindOrderRemindersCreate, bindAftersalesRead as bindOrderAftersalesRead, bindOrdersReceive as bindOrderOrdersReceive } from './operations/order';
import { bindWorkitemsRead as bindFulfillmentWorkitemsRead, bindWorkitemsTransition as bindFulfillmentWorkitemsTransition, bindReturnsRead as bindFulfillmentReturnsRead, bindShipmentsCreate as bindFulfillmentShipmentsCreate, bindReturnsReceive as bindFulfillmentReturnsReceive, bindReturnsInspect as bindFulfillmentReturnsInspect } from './operations/fulfillment';
import { bindChallengesIssue as bindVerificationChallengesIssue, bindChallengesVerify as bindVerificationChallengesVerify, bindHistoryRead as bindVerificationHistoryRead, bindDevicesRead as bindVerificationDevicesRead, bindDevicesManage as bindVerificationDevicesManage } from './operations/verification';
import { bindRefundsRequest as bindPaymentRefundsRequest, bindRecoveriesRead as bindPaymentRecoveriesRead, bindRecoveriesResolve as bindPaymentRecoveriesResolve } from './operations/payment';
import { bindSearchRead as bindVoucherSearchRead, bindActivationsSecret as bindVoucherActivationsSecret, bindActivationsNumbersecret as bindVoucherActivationsNumbersecret, bindVouchersBind as bindVoucherVouchersBind, bindVouchersUnbind as bindVoucherVouchersUnbind, bindVouchersGet as bindVoucherVouchersGet, bindVouchersGetbynumber as bindVoucherVouchersGetbynumber, bindVouchersTimeline as bindVoucherVouchersTimeline, bindRedemptionsQuote as bindVoucherRedemptionsQuote, bindTenderholdsCreate as bindVoucherTenderholdsCreate, bindTenderholdsConsume as bindVoucherTenderholdsConsume, bindTenderholdsRelease as bindVoucherTenderholdsRelease, bindRedemptionsCreate as bindVoucherRedemptionsCreate, bindRefundsCreate as bindVoucherRefundsCreate, bindRedemptionsGet as bindVoucherRedemptionsGet } from './operations/voucher';
import { bindCasesRead as bindSupportCasesRead, bindMessagesSend as bindSupportMessagesSend, bindMessagesRead as bindSupportMessagesRead, bindAttachmentsCreate as bindSupportAttachmentsCreate, bindEventsRead as bindSupportEventsRead, bindReadstatesManage as bindSupportReadstatesManage } from './operations/support';
import { bindTreeRead as bindNavigationTreeRead, bindCatalogRead as bindNavigationCatalogRead } from './operations/navigation';
import { bindMembersApply as bindReferralMembersApply, bindBindingsRead as bindReferralBindingsRead, bindBindingsCreate as bindReferralBindingsCreate, bindEarningsRead as bindReferralEarningsRead, bindLinksRead as bindReferralLinksRead, bindWithdrawalsRead as bindReferralWithdrawalsRead, bindWithdrawalsCreate as bindReferralWithdrawalsCreate } from './operations/referral';

export function createStoreClient(executor: OperationExecutor): StoreSurfaceClient {
  return Object.freeze({
    identity: Object.freeze({ sessionsCreate: bindIdentitySessionsCreate(executor), sessionsComplete: bindIdentitySessionsComplete(executor), ticketsExchange: bindIdentityTicketsExchange(executor), sessionRead: bindIdentitySessionRead(executor), sessionDelete: bindIdentitySessionDelete(executor), handoversRead: bindIdentityHandoversRead(executor), handoversCreate: bindIdentityHandoversCreate(executor), sessionsRead: bindIdentitySessionsRead(executor), sessionsRevoke: bindIdentitySessionsRevoke(executor), membershipsRead: bindIdentityMembershipsRead(executor), membershipsSwitch: bindIdentityMembershipsSwitch(executor), challengesCreate: bindIdentityChallengesCreate(executor), mobileChallengesCreate: bindIdentityMobileChallengesCreate(executor), invitationsResolve: bindIdentityInvitationsResolve(executor), enrollmentsRead: bindIdentityEnrollmentsRead(executor), enrollmentsComplete: bindIdentityEnrollmentsComplete(executor), passwordChange: bindIdentityPasswordChange(executor), passwordVerify: bindIdentityPasswordVerify(executor), passwordReset: bindIdentityPasswordReset(executor), mobileManage: bindIdentityMobileManage(executor), stepupStart: bindIdentityStepupStart(executor), stepupComplete: bindIdentityStepupComplete(executor), stepupDisable: bindIdentityStepupDisable(executor), bootstrapRead: bindIdentityBootstrapRead(executor), providersRead: bindIdentityProvidersRead(executor), federationsStart: bindIdentityFederationsStart(executor), federationsCallback: bindIdentityFederationsCallback(executor), federationsSelectionRead: bindIdentityFederationsSelectionRead(executor), federationsComplete: bindIdentityFederationsComplete(executor), linksRead: bindIdentityLinksRead(executor), linksCreate: bindIdentityLinksCreate(executor), linksRevoke: bindIdentityLinksRevoke(executor) }),
    organization: Object.freeze({ layersRead: bindOrganizationLayersRead(executor), storesRead: bindOrganizationStoresRead(executor) }),
    capability: Object.freeze({ assignmentsRead: bindCapabilityAssignmentsRead(executor) }),
    member: Object.freeze({ profileRead: bindMemberProfileRead(executor) }),
    pricing: Object.freeze({ offersRead: bindPricingOffersRead(executor) }),
    inventory: Object.freeze({ availabilityRead: bindInventoryAvailabilityRead(executor), adjustmentsRead: bindInventoryAdjustmentsRead(executor), adjustmentsCreate: bindInventoryAdjustmentsCreate(executor) }),
    experience: Object.freeze({ publishedRead: bindExperiencePublishedRead(executor) }),
    order: Object.freeze({ ordersCancel: bindOrderOrdersCancel(executor), ordersRead: bindOrderOrdersRead(executor), detailRead: bindOrderDetailRead(executor), remindersCreate: bindOrderRemindersCreate(executor), aftersalesRead: bindOrderAftersalesRead(executor), ordersReceive: bindOrderOrdersReceive(executor) }),
    fulfillment: Object.freeze({ workitemsRead: bindFulfillmentWorkitemsRead(executor), workitemsTransition: bindFulfillmentWorkitemsTransition(executor), returnsRead: bindFulfillmentReturnsRead(executor), shipmentsCreate: bindFulfillmentShipmentsCreate(executor), returnsReceive: bindFulfillmentReturnsReceive(executor), returnsInspect: bindFulfillmentReturnsInspect(executor) }),
    verification: Object.freeze({ challengesIssue: bindVerificationChallengesIssue(executor), challengesVerify: bindVerificationChallengesVerify(executor), historyRead: bindVerificationHistoryRead(executor), devicesRead: bindVerificationDevicesRead(executor), devicesManage: bindVerificationDevicesManage(executor) }),
    payment: Object.freeze({ refundsRequest: bindPaymentRefundsRequest(executor), recoveriesRead: bindPaymentRecoveriesRead(executor), recoveriesResolve: bindPaymentRecoveriesResolve(executor) }),
    voucher: Object.freeze({ searchRead: bindVoucherSearchRead(executor), activationsSecret: bindVoucherActivationsSecret(executor), activationsNumbersecret: bindVoucherActivationsNumbersecret(executor), vouchersBind: bindVoucherVouchersBind(executor), vouchersUnbind: bindVoucherVouchersUnbind(executor), vouchersGet: bindVoucherVouchersGet(executor), vouchersGetbynumber: bindVoucherVouchersGetbynumber(executor), vouchersTimeline: bindVoucherVouchersTimeline(executor), redemptionsQuote: bindVoucherRedemptionsQuote(executor), tenderholdsCreate: bindVoucherTenderholdsCreate(executor), tenderholdsConsume: bindVoucherTenderholdsConsume(executor), tenderholdsRelease: bindVoucherTenderholdsRelease(executor), redemptionsCreate: bindVoucherRedemptionsCreate(executor), refundsCreate: bindVoucherRefundsCreate(executor), redemptionsGet: bindVoucherRedemptionsGet(executor) }),
    support: Object.freeze({ casesRead: bindSupportCasesRead(executor), messagesSend: bindSupportMessagesSend(executor), messagesRead: bindSupportMessagesRead(executor), attachmentsCreate: bindSupportAttachmentsCreate(executor), eventsRead: bindSupportEventsRead(executor), readstatesManage: bindSupportReadstatesManage(executor) }),
    navigation: Object.freeze({ treeRead: bindNavigationTreeRead(executor), catalogRead: bindNavigationCatalogRead(executor) }),
    referral: Object.freeze({ membersApply: bindReferralMembersApply(executor), bindingsRead: bindReferralBindingsRead(executor), bindingsCreate: bindReferralBindingsCreate(executor), earningsRead: bindReferralEarningsRead(executor), linksRead: bindReferralLinksRead(executor), withdrawalsRead: bindReferralWithdrawalsRead(executor), withdrawalsCreate: bindReferralWithdrawalsCreate(executor) }),
  });
}

export function createFetchStore(baseUrl: string): StoreSurfaceClient {
  return createStoreClient(new ApiClient(baseUrl, new FetchTransport()));
}
