// Generated from config/clients.yml and definitions/operations.yml. Do not edit.
import { ApiClient } from './ApiClient';
import { FetchTransport } from './FetchTransport';
import type { OperationExecutor } from './OperationDescriptor';
import type { SupplierSurfaceClient } from './SurfaceCatalog';
import { bindUploadsCreate as bindRuntimeUploadsCreate } from './operations/runtime';
import { bindSessionsCreate as bindIdentitySessionsCreate, bindSessionsComplete as bindIdentitySessionsComplete, bindTicketsExchange as bindIdentityTicketsExchange, bindSessionRead as bindIdentitySessionRead, bindSessionDelete as bindIdentitySessionDelete, bindSessionsRead as bindIdentitySessionsRead, bindSessionsRevoke as bindIdentitySessionsRevoke, bindMembershipsRead as bindIdentityMembershipsRead, bindMembershipsSwitch as bindIdentityMembershipsSwitch, bindChallengesCreate as bindIdentityChallengesCreate, bindMobileChallengesCreate as bindIdentityMobileChallengesCreate, bindInvitationsResolve as bindIdentityInvitationsResolve, bindEnrollmentsRead as bindIdentityEnrollmentsRead, bindEnrollmentsComplete as bindIdentityEnrollmentsComplete, bindPasswordChange as bindIdentityPasswordChange, bindPasswordVerify as bindIdentityPasswordVerify, bindPasswordReset as bindIdentityPasswordReset, bindMobileManage as bindIdentityMobileManage, bindStepupStart as bindIdentityStepupStart, bindStepupComplete as bindIdentityStepupComplete, bindStepupDisable as bindIdentityStepupDisable, bindBootstrapRead as bindIdentityBootstrapRead, bindProvidersRead as bindIdentityProvidersRead, bindFederationsStart as bindIdentityFederationsStart, bindFederationsCallback as bindIdentityFederationsCallback, bindFederationsSelectionRead as bindIdentityFederationsSelectionRead, bindFederationsComplete as bindIdentityFederationsComplete, bindLinksRead as bindIdentityLinksRead, bindLinksCreate as bindIdentityLinksCreate, bindLinksRevoke as bindIdentityLinksRevoke } from './operations/identity';
import { bindLayersRead as bindOrganizationLayersRead } from './operations/organization';
import { bindAssignmentsRead as bindCapabilityAssignmentsRead } from './operations/capability';
import { bindPartnersRead as bindPartnerPartnersRead } from './operations/partner';
import { bindProfileRead as bindMemberProfileRead } from './operations/member';
import { bindPoolsRead as bindCatalogPoolsRead, bindProductDetailRead as bindCatalogProductDetailRead, bindMediauploadsCreate as bindCatalogMediauploadsCreate, bindProductsCreate as bindCatalogProductsCreate, bindProductsUpdate as bindCatalogProductsUpdate, bindListingsRead as bindCatalogListingsRead, bindFacetsRead as bindCatalogFacetsRead, bindListingsPriceSet as bindCatalogListingsPriceSet, bindImportsCreate as bindCatalogImportsCreate, bindImportsRead as bindCatalogImportsRead } from './operations/catalog';
import { bindOffersRead as bindPricingOffersRead } from './operations/pricing';
import { bindAvailabilityRead as bindInventoryAvailabilityRead, bindImportsCreate as bindInventoryImportsCreate, bindImportsRead as bindInventoryImportsRead } from './operations/inventory';
import { bindPublishedRead as bindExperiencePublishedRead } from './operations/experience';
import { bindOrdersCancel as bindOrderOrdersCancel, bindOrdersRead as bindOrderOrdersRead, bindDetailRead as bindOrderDetailRead, bindRemindersCreate as bindOrderRemindersCreate, bindAftersalesRead as bindOrderAftersalesRead, bindOrdersReceive as bindOrderOrdersReceive } from './operations/order';
import { bindWorkitemsRead as bindFulfillmentWorkitemsRead, bindWorkitemsTransition as bindFulfillmentWorkitemsTransition, bindReturnsRead as bindFulfillmentReturnsRead, bindShipmentsCreate as bindFulfillmentShipmentsCreate, bindReturnsReceive as bindFulfillmentReturnsReceive, bindReturnsInspect as bindFulfillmentReturnsInspect } from './operations/fulfillment';
import { bindSearchRead as bindVoucherSearchRead, bindActivationsSecret as bindVoucherActivationsSecret, bindActivationsNumbersecret as bindVoucherActivationsNumbersecret, bindVouchersGet as bindVoucherVouchersGet, bindVouchersTimeline as bindVoucherVouchersTimeline, bindRedemptionsGet as bindVoucherRedemptionsGet } from './operations/voucher';
import { bindOverviewRead as bindFinanceOverviewRead, bindEntriesRead as bindFinanceEntriesRead, bindStatementsRead as bindFinanceStatementsRead, bindStatementsExport as bindFinanceStatementsExport, bindReconciliationsRead as bindFinanceReconciliationsRead, bindSettlementsRead as bindFinanceSettlementsRead } from './operations/finance';
import { bindRequestsRead as bindInvoiceRequestsRead } from './operations/invoice';
import { bindCasesRead as bindSupportCasesRead, bindMessagesSend as bindSupportMessagesSend, bindMessagesRead as bindSupportMessagesRead, bindAttachmentsCreate as bindSupportAttachmentsCreate, bindEventsRead as bindSupportEventsRead, bindReadstatesManage as bindSupportReadstatesManage } from './operations/support';
import { bindConnectionsRead as bindChannelConnectionsRead, bindConnectionsTest as bindChannelConnectionsTest, bindSyncrunsRead as bindChannelSyncrunsRead, bindOperationsRead as bindChannelOperationsRead } from './operations/channel';
import { bindTreeRead as bindNavigationTreeRead, bindCatalogRead as bindNavigationCatalogRead } from './operations/navigation';
import { bindMembersApply as bindReferralMembersApply, bindBindingsRead as bindReferralBindingsRead, bindBindingsCreate as bindReferralBindingsCreate, bindEarningsRead as bindReferralEarningsRead, bindLinksRead as bindReferralLinksRead, bindWithdrawalsRead as bindReferralWithdrawalsRead, bindWithdrawalsCreate as bindReferralWithdrawalsCreate } from './operations/referral';

export function createSupplierClient(executor: OperationExecutor): SupplierSurfaceClient {
  return Object.freeze({
    runtime: Object.freeze({ uploadsCreate: bindRuntimeUploadsCreate(executor) }),
    identity: Object.freeze({ sessionsCreate: bindIdentitySessionsCreate(executor), sessionsComplete: bindIdentitySessionsComplete(executor), ticketsExchange: bindIdentityTicketsExchange(executor), sessionRead: bindIdentitySessionRead(executor), sessionDelete: bindIdentitySessionDelete(executor), sessionsRead: bindIdentitySessionsRead(executor), sessionsRevoke: bindIdentitySessionsRevoke(executor), membershipsRead: bindIdentityMembershipsRead(executor), membershipsSwitch: bindIdentityMembershipsSwitch(executor), challengesCreate: bindIdentityChallengesCreate(executor), mobileChallengesCreate: bindIdentityMobileChallengesCreate(executor), invitationsResolve: bindIdentityInvitationsResolve(executor), enrollmentsRead: bindIdentityEnrollmentsRead(executor), enrollmentsComplete: bindIdentityEnrollmentsComplete(executor), passwordChange: bindIdentityPasswordChange(executor), passwordVerify: bindIdentityPasswordVerify(executor), passwordReset: bindIdentityPasswordReset(executor), mobileManage: bindIdentityMobileManage(executor), stepupStart: bindIdentityStepupStart(executor), stepupComplete: bindIdentityStepupComplete(executor), stepupDisable: bindIdentityStepupDisable(executor), bootstrapRead: bindIdentityBootstrapRead(executor), providersRead: bindIdentityProvidersRead(executor), federationsStart: bindIdentityFederationsStart(executor), federationsCallback: bindIdentityFederationsCallback(executor), federationsSelectionRead: bindIdentityFederationsSelectionRead(executor), federationsComplete: bindIdentityFederationsComplete(executor), linksRead: bindIdentityLinksRead(executor), linksCreate: bindIdentityLinksCreate(executor), linksRevoke: bindIdentityLinksRevoke(executor) }),
    organization: Object.freeze({ layersRead: bindOrganizationLayersRead(executor) }),
    capability: Object.freeze({ assignmentsRead: bindCapabilityAssignmentsRead(executor) }),
    partner: Object.freeze({ partnersRead: bindPartnerPartnersRead(executor) }),
    member: Object.freeze({ profileRead: bindMemberProfileRead(executor) }),
    catalog: Object.freeze({ poolsRead: bindCatalogPoolsRead(executor), productDetailRead: bindCatalogProductDetailRead(executor), mediauploadsCreate: bindCatalogMediauploadsCreate(executor), productsCreate: bindCatalogProductsCreate(executor), productsUpdate: bindCatalogProductsUpdate(executor), listingsRead: bindCatalogListingsRead(executor), facetsRead: bindCatalogFacetsRead(executor), listingsPriceSet: bindCatalogListingsPriceSet(executor), importsCreate: bindCatalogImportsCreate(executor), importsRead: bindCatalogImportsRead(executor) }),
    pricing: Object.freeze({ offersRead: bindPricingOffersRead(executor) }),
    inventory: Object.freeze({ availabilityRead: bindInventoryAvailabilityRead(executor), importsCreate: bindInventoryImportsCreate(executor), importsRead: bindInventoryImportsRead(executor) }),
    experience: Object.freeze({ publishedRead: bindExperiencePublishedRead(executor) }),
    order: Object.freeze({ ordersCancel: bindOrderOrdersCancel(executor), ordersRead: bindOrderOrdersRead(executor), detailRead: bindOrderDetailRead(executor), remindersCreate: bindOrderRemindersCreate(executor), aftersalesRead: bindOrderAftersalesRead(executor), ordersReceive: bindOrderOrdersReceive(executor) }),
    fulfillment: Object.freeze({ workitemsRead: bindFulfillmentWorkitemsRead(executor), workitemsTransition: bindFulfillmentWorkitemsTransition(executor), returnsRead: bindFulfillmentReturnsRead(executor), shipmentsCreate: bindFulfillmentShipmentsCreate(executor), returnsReceive: bindFulfillmentReturnsReceive(executor), returnsInspect: bindFulfillmentReturnsInspect(executor) }),
    voucher: Object.freeze({ searchRead: bindVoucherSearchRead(executor), activationsSecret: bindVoucherActivationsSecret(executor), activationsNumbersecret: bindVoucherActivationsNumbersecret(executor), vouchersGet: bindVoucherVouchersGet(executor), vouchersTimeline: bindVoucherVouchersTimeline(executor), redemptionsGet: bindVoucherRedemptionsGet(executor) }),
    finance: Object.freeze({ overviewRead: bindFinanceOverviewRead(executor), entriesRead: bindFinanceEntriesRead(executor), statementsRead: bindFinanceStatementsRead(executor), statementsExport: bindFinanceStatementsExport(executor), reconciliationsRead: bindFinanceReconciliationsRead(executor), settlementsRead: bindFinanceSettlementsRead(executor) }),
    invoice: Object.freeze({ requestsRead: bindInvoiceRequestsRead(executor) }),
    support: Object.freeze({ casesRead: bindSupportCasesRead(executor), messagesSend: bindSupportMessagesSend(executor), messagesRead: bindSupportMessagesRead(executor), attachmentsCreate: bindSupportAttachmentsCreate(executor), eventsRead: bindSupportEventsRead(executor), readstatesManage: bindSupportReadstatesManage(executor) }),
    channel: Object.freeze({ connectionsRead: bindChannelConnectionsRead(executor), connectionsTest: bindChannelConnectionsTest(executor), syncrunsRead: bindChannelSyncrunsRead(executor), operationsRead: bindChannelOperationsRead(executor) }),
    navigation: Object.freeze({ treeRead: bindNavigationTreeRead(executor), catalogRead: bindNavigationCatalogRead(executor) }),
    referral: Object.freeze({ membersApply: bindReferralMembersApply(executor), bindingsRead: bindReferralBindingsRead(executor), bindingsCreate: bindReferralBindingsCreate(executor), earningsRead: bindReferralEarningsRead(executor), linksRead: bindReferralLinksRead(executor), withdrawalsRead: bindReferralWithdrawalsRead(executor), withdrawalsCreate: bindReferralWithdrawalsCreate(executor) }),
  });
}

export function createFetchSupplier(baseUrl: string): SupplierSurfaceClient {
  return createSupplierClient(new ApiClient(baseUrl, new FetchTransport()));
}
