import { FileText, Package, Truck } from 'lucide-react';
import type { useOrderViewModel } from '../viewmodel/OrderViewModel';
import { formatMinor } from '../../../shared/format/Money';
import { orderStatusText, paymentStateText } from '../model/OrderText';

export function OrderPage({ viewmodel }: Readonly<{ viewmodel: ReturnType<typeof useOrderViewModel> }>) {
  const tabs = [{id:'all',name:'全部订单'},{id:'pending_payment',name:'待付款'},{id:'shipping',name:'配送中'},{id:'completed',name:'已完成'},{id:'after_sale',name:'售后中'}] as const;
  return <main className="min-h-[80dvh] bg-[var(--sw-background)] px-3 py-4 sm:px-5"><div className="mx-auto max-w-[1100px]"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black">我的订单</h1><p className="mt-1 text-xs text-slate-500">支付、履约、售后和退款状态均来自订单权威读模型。</p></div><button type="button" onClick={viewmodel.actions.invoices} className="min-h-11 rounded-xl border bg-white px-4 text-sm font-bold text-blue-700"><FileText size={16} className="mr-2 inline"/>电子发票</button></header>
    <div className="mt-4 flex gap-2 overflow-auto rounded-2xl border bg-white p-2">{tabs.map((tab) => <button type="button" key={tab.id} onClick={() => viewmodel.actions.filter(tab.id)} className={`min-h-11 whitespace-nowrap rounded-xl px-4 text-sm font-bold ${viewmodel.status === tab.id ? 'bg-blue-700 text-white' : 'text-slate-600 hover:bg-blue-50'}`}>{tab.name}</button>)}</div>
    <section className="mt-4 space-y-3">{viewmodel.visibleOrders.map((order) => <article key={order.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-center justify-between gap-2 border-b bg-slate-50 px-4 py-3 text-xs"><button type="button" onClick={() => viewmodel.actions.open(order.id)} className="font-black text-blue-700">{order.orderNo}</button><span>{new Date(order.createdAt).toLocaleString('zh-CN')}</span><b>{orderStatusText(order.status)}</b></header><button type="button" onClick={() => viewmodel.actions.open(order.id)} className="block w-full p-4 text-left">{order.items.map((line) => <div key={line.id} className="flex items-center gap-3 py-2"><span className="grid h-14 w-14 place-items-center rounded-xl bg-slate-100"><Package className="text-slate-400"/></span><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-bold">{line.title}</h2><p className="mt-1 text-xs text-slate-500">数量 {line.quantity} · {paymentStateText(order.paymentState)}</p></div><b>¥{formatMinor(line.payableMinor)}</b></div>)}</button><footer className="flex flex-wrap items-center justify-between gap-3 border-t px-4 py-3"><span className="flex items-center gap-2 text-xs text-slate-500"><Truck size={15}/>履约状态：{order.fulfillmentState}</span><div className="flex items-center gap-3"><b>实付 ¥{formatMinor(order.totalMinor)}</b><button type="button" onClick={() => viewmodel.actions.aftersale(order.id)} className="min-h-11 rounded-xl border px-4 text-xs font-bold">申请/查看售后</button></div></footer></article>)}{viewmodel.visibleOrders.length === 0 ? <div role="status" className="grid min-h-64 place-items-center rounded-3xl border border-dashed bg-white text-sm text-slate-500">当前筛选下暂无订单</div> : null}</section>
  </div></main>;
}
