import type { ConsoleContext } from '../../../entity/session/ConsoleSession';
import type { MallRecord, ThemePresetId } from './Mall';
import type { MallOpeningDraft } from './MallDraftType';
import { themePreset } from './ThemePreset';

export function initialMallDraft(context: ConsoleContext): MallOpeningDraft {
  const preset = themePreset('shop').theme;
  return Object.freeze({
    parentId: context.scope.kind === 'enterprise' ? context.scope.id : '',
    name: '',
    code: '',
    publicSlug: '',
    brandName: '',
    domainMode: 'platform',
    customDomain: '',
    ownerMembershipId: context.session.membership,
    timezone: 'Asia/Shanghai',
    currency: 'CNY',
    themePreset: preset.preset,
    primaryColor: preset.primaryColor,
    accentColor: preset.accentColor,
    logoObjectRef: '',
    faviconObjectRef: '',
    subjectType: 'enterprise',
    companyName: context.scope.kind === 'enterprise' ? (context.scope.name ?? '') : '',
    creditCode: '',
    legalRepresentative: '',
    contactName: context.profile.display_name,
    contactMobile: '',
    licenseObjectRef: '',
    storeType: 'general',
    primaryCategory: '',
    businessMode: 'selfoperated',
    businessRegion: '',
    businessAddress: '',
    servicePhone: '',
    certificateMode: 'managed',
    certificateObjectRef: '',
    miniProgramMode: 'later',
    miniProgramAppId: '',
    miniProgramOriginalId: '',
    officialAccountMode: 'later',
    officialAccountAppId: '',
    videoChannelId: '',
    paymentPlan: 'later',
    wechatMerchantId: '',
    deliveryMode: 'express',
    warehouseRegion: '',
    returnContact: '',
    returnAddress: '',
    invoiceMode: 'later',
    notificationContact: '',
    status: 'draft',
  });
}

export function selectTheme(draft: MallOpeningDraft, preset: ThemePresetId): MallOpeningDraft {
  const selected = themePreset(preset).theme;
  return Object.freeze({ ...draft, themePreset: preset, primaryColor: selected.primaryColor, accentColor: selected.accentColor });
}

export function mallOpeningDraft(record: MallRecord): MallOpeningDraft {
  return Object.freeze({
    parentId: record.parentId,
    name: record.name,
    code: record.code,
    publicSlug: record.publicSlug,
    brandName: record.brandName,
    domainMode: record.domain.mode,
    customDomain: record.domain.mode === 'custom' ? record.domain.customDomain : '',
    ownerMembershipId: record.ownerMembershipId,
    timezone: record.timezone,
    currency: record.currency,
    themePreset: record.theme.preset,
    primaryColor: record.theme.primaryColor,
    accentColor: record.theme.accentColor,
    logoObjectRef: record.theme.logoObjectRef ?? '',
    faviconObjectRef: record.theme.faviconObjectRef ?? '',
    subjectType: record.opening.subject.type,
    companyName: record.opening.subject.companyName ?? '',
    creditCode: record.opening.subject.creditCode ?? '',
    legalRepresentative: record.opening.subject.legalRepresentative ?? '',
    contactName: record.opening.subject.contactName ?? '',
    contactMobile: record.opening.subject.contactMobile ?? '',
    licenseObjectRef: record.opening.subject.licenseObjectRef ?? '',
    storeType: record.opening.business.storeType,
    primaryCategory: record.opening.business.primaryCategory ?? '',
    businessMode: record.opening.business.mode,
    businessRegion: record.opening.business.region ?? '',
    businessAddress: record.opening.business.address ?? '',
    servicePhone: record.opening.business.servicePhone ?? '',
    certificateMode: record.opening.certificateMode,
    certificateObjectRef: record.opening.certificateObjectRef ?? '',
    miniProgramMode: record.opening.channels.miniProgramMode,
    miniProgramAppId: record.opening.channels.miniProgramAppId ?? '',
    miniProgramOriginalId: record.opening.channels.miniProgramOriginalId ?? '',
    officialAccountMode: record.opening.channels.officialAccountMode,
    officialAccountAppId: record.opening.channels.officialAccountAppId ?? '',
    videoChannelId: record.opening.channels.videoChannelId ?? '',
    paymentPlan: record.opening.payment.plan,
    wechatMerchantId: record.opening.payment.wechatMerchantId ?? '',
    deliveryMode: record.opening.fulfillment.deliveryMode,
    warehouseRegion: record.opening.fulfillment.warehouseRegion ?? '',
    returnContact: record.opening.fulfillment.returnContact ?? '',
    returnAddress: record.opening.fulfillment.returnAddress ?? '',
    invoiceMode: record.opening.invoiceMode,
    notificationContact: record.opening.notificationContact ?? '',
    status: record.status,
  });
}
