// Generated by @shop/navigationgen. Do not edit.
export const NAVIGATION_CATALOG_HASH = '342e9bd457b8abd49ab0bc7c816a649742e46bd27ba8dd8fd8f1f5525b091d48' as const;
const SOURCE = [
  {
    "id": "distributioncontrol",
    "surface": "console",
    "scope": "distributor",
    "parent": null,
    "title": "智慧翼中控台",
    "icon": "control",
    "route": "/scopes/:scopeKind/:scopeId/control",
    "component": "control",
    "order": 10,
    "entry": "channel.distributors.read",
    "permissions": [
      "channel.distributor.read"
    ],
    "capabilities": [
      "channel.distributors.read"
    ],
    "requirements": [
      "MVPDISTRIBUTION"
    ],
    "empty": "hide"
  },
  {
    "id": "groupdashboard",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "经营驾驶舱",
    "icon": "dashboard",
    "route": "/scopes/:scopeKind/:scopeId/cockpit",
    "component": "cockpit",
    "order": 10,
    "entry": "reporting.dashboard.read",
    "permissions": [
      "reporting.dashboard.read"
    ],
    "capabilities": [
      "reporting.dashboard.read"
    ],
    "requirements": [
      "MVPGROUPDASHBOARD"
    ],
    "empty": "hide"
  },
  {
    "id": "groupcontrol",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "智慧翼中控台",
    "icon": "control",
    "route": "/scopes/:scopeKind/:scopeId/control",
    "component": "control",
    "order": 15,
    "entry": "runtime.health.dependency",
    "permissions": [
      "runtime.health.read"
    ],
    "capabilities": [
      "runtime.health.dependency"
    ],
    "requirements": [
      "MVPPLATFORM"
    ],
    "empty": "hide"
  },
  {
    "id": "groupapplication",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "築店 · 商城管理",
    "icon": "application",
    "route": "/scopes/:scopeKind/:scopeId/experience",
    "component": "experience",
    "order": 20,
    "entry": "experience.applications.read",
    "permissions": [
      "experience.application.read"
    ],
    "capabilities": [
      "experience.applications.read"
    ],
    "requirements": [
      "MVPGROUPAPPLICATION"
    ],
    "empty": "hide"
  },
  {
    "id": "groupproduct",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "商品治理台",
    "icon": "product",
    "route": "/scopes/:scopeKind/:scopeId/products",
    "component": "product",
    "order": 30,
    "entry": "catalog.pools.read",
    "permissions": [
      "catalog.pool.read"
    ],
    "capabilities": [
      "catalog.pools.read"
    ],
    "requirements": [
      "MVPGROUPPOOL"
    ],
    "empty": "hide"
  },
  {
    "id": "grouporder",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "订单管理系统",
    "icon": "order",
    "route": "/scopes/:scopeKind/:scopeId/orders",
    "component": "order",
    "order": 40,
    "entry": "order.orders.read",
    "permissions": [
      "order.read"
    ],
    "capabilities": [
      "order.orders.read"
    ],
    "requirements": [
      "MVPGROUPORDER"
    ],
    "empty": "hide"
  },
  {
    "id": "groupreferral",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "分销返佣系统",
    "icon": "referral",
    "route": "/scopes/:scopeKind/:scopeId/referral",
    "component": "referral",
    "order": 45,
    "entry": "referral.settings.read",
    "permissions": [
      "referral.setting.read"
    ],
    "capabilities": [
      "referral.settings.read"
    ],
    "requirements": [
      "MVPDISTRIBUTION"
    ],
    "empty": "hide"
  },
  {
    "id": "groupchannel",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "渠道接入系统",
    "icon": "channel",
    "route": "/scopes/:scopeKind/:scopeId/channels",
    "component": "channel",
    "order": 47,
    "entry": "channel.connections.read",
    "permissions": [
      "channel.connection.read"
    ],
    "capabilities": [
      "channel.connections.read"
    ],
    "requirements": [
      "MVPPROVIDER"
    ],
    "empty": "hide"
  },
  {
    "id": "groupvoucher",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "卡券治理台",
    "icon": "voucher",
    "route": "/scopes/:scopeKind/:scopeId/vouchers",
    "component": "voucher",
    "order": 50,
    "entry": "voucher.cardlibraries.read",
    "permissions": [
      "voucher.cardlibrary.read"
    ],
    "capabilities": [
      "voucher.cardlibraries.read"
    ],
    "requirements": [
      "MVPGROUPVOUCHER"
    ],
    "empty": "hide"
  },
  {
    "id": "groupfinance",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "财务与对账台",
    "icon": "finance",
    "route": "/scopes/:scopeKind/:scopeId/finance",
    "component": "finance",
    "order": 60,
    "entry": "finance.overview.read",
    "permissions": [
      "finance.overview.read"
    ],
    "capabilities": [
      "finance.overview.read"
    ],
    "requirements": [
      "MVPGROUPFINANCE"
    ],
    "empty": "hide"
  },
  {
    "id": "groupreporting",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "数据报表",
    "icon": "reporting",
    "route": "/scopes/:scopeKind/:scopeId/reporting",
    "component": "reporting",
    "order": 70,
    "entry": "reporting.sales.read",
    "permissions": [
      "reporting.sales.read"
    ],
    "capabilities": [
      "reporting.sales.read"
    ],
    "requirements": [
      "MVPGROUPREPORT"
    ],
    "empty": "hide"
  },
  {
    "id": "groupsupport",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "客服系统",
    "icon": "support",
    "route": "/scopes/:scopeKind/:scopeId/support",
    "component": "support",
    "order": 80,
    "entry": "support.cases.read",
    "permissions": [
      "support.case.read"
    ],
    "capabilities": [
      "support.cases.read"
    ],
    "requirements": [
      "MVPGROUPSUPPORT"
    ],
    "empty": "hide"
  },
  {
    "id": "groupsettings",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "会员与权限",
    "icon": "settings",
    "route": "/scopes/:scopeKind/:scopeId/settings",
    "component": "settings",
    "order": 90,
    "entry": "access.center.read",
    "permissions": [
      "access.center.read"
    ],
    "capabilities": [
      "access.center.read"
    ],
    "requirements": [
      "MVPGROUPSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "grouprisk",
    "surface": "console",
    "scope": "enterprise",
    "parent": null,
    "title": "系统治理台",
    "icon": "risk",
    "route": "/scopes/:scopeKind/:scopeId/settings/risk",
    "component": "risk",
    "order": 100,
    "entry": "risk.center.read",
    "permissions": [
      "risk.read"
    ],
    "capabilities": [
      "risk.center.read"
    ],
    "requirements": [
      "MVPGROUPSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "groupmessage",
    "surface": "console",
    "scope": "enterprise",
    "parent": "grouprisk",
    "title": "通知管理",
    "icon": "notification",
    "route": "/scopes/:scopeKind/:scopeId/settings/messages",
    "component": "notification",
    "order": 40,
    "entry": "notification.templates.read",
    "permissions": [
      "notification.template.read"
    ],
    "capabilities": [
      "notification.templates.read"
    ],
    "requirements": [
      "MVPGROUPSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "groupprovider",
    "surface": "console",
    "scope": "enterprise",
    "parent": "grouprisk",
    "title": "登录方式",
    "icon": "identity",
    "route": "/scopes/:scopeKind/:scopeId/settings/login",
    "component": "identityprovider",
    "order": 60,
    "entry": "identity.providers.read",
    "permissions": [
      "identity.provider.manage"
    ],
    "capabilities": [
      "identity.federation",
      "identity.providers.read"
    ],
    "requirements": [
      "MVPGROUPSETTING",
      "MVPIDENTITY"
    ],
    "empty": "hide"
  },
  {
    "id": "groupdirectory",
    "surface": "console",
    "scope": "enterprise",
    "parent": "grouprisk",
    "title": "通讯录同步",
    "icon": "directory",
    "route": "/scopes/:scopeKind/:scopeId/settings/directory",
    "component": "directory",
    "order": 70,
    "entry": "organization.directories.read",
    "permissions": [
      "organization.directory.read"
    ],
    "capabilities": [
      "identity.directory",
      "organization.directories.read"
    ],
    "requirements": [
      "MVPGROUPSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "groupadmin",
    "surface": "console",
    "scope": "enterprise",
    "parent": "groupsettings",
    "title": "权限中心",
    "icon": "access",
    "route": "/scopes/:scopeKind/:scopeId/settings/access",
    "component": "access",
    "order": 10,
    "entry": "access.center.read",
    "permissions": [
      "access.center.read"
    ],
    "capabilities": [
      "access.center.read"
    ],
    "requirements": [
      "MVPGROUPSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "groupmemberdata",
    "surface": "console",
    "scope": "enterprise",
    "parent": "groupsettings",
    "title": "成员管理",
    "icon": "member",
    "route": "/scopes/:scopeKind/:scopeId/settings/members",
    "component": "member",
    "order": 20,
    "entry": "member.members.read",
    "permissions": [
      "member.read"
    ],
    "capabilities": [
      "member.members.read"
    ],
    "requirements": [
      "MVPGROUPSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "grouppartner",
    "surface": "console",
    "scope": "enterprise",
    "parent": "groupsettings",
    "title": "供应商与门店",
    "icon": "partner",
    "route": "/scopes/:scopeKind/:scopeId/settings/partners",
    "component": "partner",
    "order": 30,
    "entry": "partner.partners.read",
    "permissions": [
      "partner.read"
    ],
    "capabilities": [
      "partner.partners.read"
    ],
    "requirements": [
      "MVPGROUPSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "malldashboard",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "经营驾驶舱",
    "icon": "dashboard",
    "route": "/scopes/:scopeKind/:scopeId/cockpit",
    "component": "cockpit",
    "order": 10,
    "entry": "reporting.dashboard.read",
    "permissions": [
      "reporting.dashboard.read"
    ],
    "capabilities": [
      "reporting.dashboard.read"
    ],
    "requirements": [
      "MVPMALLDASHBOARD"
    ],
    "empty": "hide"
  },
  {
    "id": "mallcontrol",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "智慧翼中控台",
    "icon": "control",
    "route": "/scopes/:scopeKind/:scopeId/control",
    "component": "control",
    "order": 15,
    "entry": "runtime.health.dependency",
    "permissions": [
      "runtime.health.read"
    ],
    "capabilities": [
      "runtime.health.dependency"
    ],
    "requirements": [
      "MVPPLATFORM"
    ],
    "empty": "hide"
  },
  {
    "id": "malldesign",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "築店 · 店铺装修",
    "icon": "application",
    "route": "/scopes/:scopeKind/:scopeId/experience",
    "component": "experience",
    "order": 20,
    "entry": "experience.applications.read",
    "permissions": [
      "experience.application.read"
    ],
    "capabilities": [
      "experience.applications.read"
    ],
    "requirements": [
      "MVPMALLDESIGN"
    ],
    "empty": "hide"
  },
  {
    "id": "mallproduct",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "商品治理台",
    "icon": "product",
    "route": "/scopes/:scopeKind/:scopeId/products",
    "component": "product",
    "order": 30,
    "entry": "catalog.pools.read",
    "permissions": [
      "catalog.pool.read"
    ],
    "capabilities": [
      "catalog.pools.read"
    ],
    "requirements": [
      "MVPMALLPOOL"
    ],
    "empty": "hide"
  },
  {
    "id": "mallorder",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "订单管理系统",
    "icon": "order",
    "route": "/scopes/:scopeKind/:scopeId/orders",
    "component": "order",
    "order": 40,
    "entry": "order.orders.read",
    "permissions": [
      "order.read"
    ],
    "capabilities": [
      "order.orders.read"
    ],
    "requirements": [
      "MVPMALLORDER"
    ],
    "empty": "hide"
  },
  {
    "id": "mallreferral",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "分销返佣系统",
    "icon": "referral",
    "route": "/scopes/:scopeKind/:scopeId/referral",
    "component": "referral",
    "order": 45,
    "entry": "referral.settings.read",
    "permissions": [
      "referral.setting.read"
    ],
    "capabilities": [
      "referral.settings.read"
    ],
    "requirements": [
      "MVPDISTRIBUTION"
    ],
    "empty": "hide"
  },
  {
    "id": "mallchannel",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "渠道接入系统",
    "icon": "channel",
    "route": "/scopes/:scopeKind/:scopeId/channels",
    "component": "channel",
    "order": 47,
    "entry": "channel.connections.read",
    "permissions": [
      "channel.connection.read"
    ],
    "capabilities": [
      "channel.connections.read"
    ],
    "requirements": [
      "MVPPROVIDER"
    ],
    "empty": "hide"
  },
  {
    "id": "mallvoucher",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "卡券治理台",
    "icon": "voucher",
    "route": "/scopes/:scopeKind/:scopeId/vouchers",
    "component": "voucher",
    "order": 50,
    "entry": "voucher.cardlibraries.read",
    "permissions": [
      "voucher.cardlibrary.read"
    ],
    "capabilities": [
      "voucher.cardlibraries.read"
    ],
    "requirements": [
      "MVPMALLVOUCHER"
    ],
    "empty": "hide"
  },
  {
    "id": "mallfinance",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "财务与对账台",
    "icon": "finance",
    "route": "/scopes/:scopeKind/:scopeId/finance",
    "component": "finance",
    "order": 60,
    "entry": "finance.overview.read",
    "permissions": [
      "finance.overview.read"
    ],
    "capabilities": [
      "finance.overview.read"
    ],
    "requirements": [
      "MVPMALLFINANCE"
    ],
    "empty": "hide"
  },
  {
    "id": "mallreporting",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "数据报表",
    "icon": "reporting",
    "route": "/scopes/:scopeKind/:scopeId/reporting",
    "component": "reporting",
    "order": 70,
    "entry": "reporting.sales.read",
    "permissions": [
      "reporting.sales.read"
    ],
    "capabilities": [
      "reporting.sales.read"
    ],
    "requirements": [
      "MVPMALLREPORT"
    ],
    "empty": "hide"
  },
  {
    "id": "mallsupport",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "客服系统",
    "icon": "support",
    "route": "/scopes/:scopeKind/:scopeId/support",
    "component": "support",
    "order": 80,
    "entry": "support.cases.read",
    "permissions": [
      "support.case.read"
    ],
    "capabilities": [
      "support.cases.read"
    ],
    "requirements": [
      "MVPMALLSUPPORT"
    ],
    "empty": "hide"
  },
  {
    "id": "mallsettings",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "会员与权限",
    "icon": "settings",
    "route": "/scopes/:scopeKind/:scopeId/settings",
    "component": "settings",
    "order": 90,
    "entry": "access.center.read",
    "permissions": [
      "access.center.read"
    ],
    "capabilities": [
      "access.center.read"
    ],
    "requirements": [
      "MVPMALLSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "mallrisk",
    "surface": "console",
    "scope": "mall",
    "parent": null,
    "title": "系统治理台",
    "icon": "risk",
    "route": "/scopes/:scopeKind/:scopeId/settings/risk",
    "component": "risk",
    "order": 100,
    "entry": "risk.center.read",
    "permissions": [
      "risk.read"
    ],
    "capabilities": [
      "risk.center.read"
    ],
    "requirements": [
      "MVPMALLSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "mallmessage",
    "surface": "console",
    "scope": "mall",
    "parent": "mallrisk",
    "title": "通知管理",
    "icon": "notification",
    "route": "/scopes/:scopeKind/:scopeId/settings/messages",
    "component": "notification",
    "order": 40,
    "entry": "notification.templates.read",
    "permissions": [
      "notification.template.read"
    ],
    "capabilities": [
      "notification.templates.read"
    ],
    "requirements": [
      "MVPMALLSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "mallprovider",
    "surface": "console",
    "scope": "mall",
    "parent": "mallrisk",
    "title": "登录方式",
    "icon": "identity",
    "route": "/scopes/:scopeKind/:scopeId/settings/login",
    "component": "identityprovider",
    "order": 60,
    "entry": "identity.providers.read",
    "permissions": [
      "identity.provider.manage"
    ],
    "capabilities": [
      "identity.federation",
      "identity.providers.read"
    ],
    "requirements": [
      "MVPMALLSETTING",
      "MVPIDENTITY"
    ],
    "empty": "hide"
  },
  {
    "id": "malldirectory",
    "surface": "console",
    "scope": "mall",
    "parent": "mallrisk",
    "title": "通讯录同步",
    "icon": "directory",
    "route": "/scopes/:scopeKind/:scopeId/settings/directory",
    "component": "directory",
    "order": 70,
    "entry": "organization.directories.read",
    "permissions": [
      "organization.directory.read"
    ],
    "capabilities": [
      "identity.directory",
      "organization.directories.read"
    ],
    "requirements": [
      "MVPMALLSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "malladmin",
    "surface": "console",
    "scope": "mall",
    "parent": "mallsettings",
    "title": "权限中心",
    "icon": "access",
    "route": "/scopes/:scopeKind/:scopeId/settings/access",
    "component": "access",
    "order": 10,
    "entry": "access.center.read",
    "permissions": [
      "access.center.read"
    ],
    "capabilities": [
      "access.center.read"
    ],
    "requirements": [
      "MVPMALLSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "mallmemberdata",
    "surface": "console",
    "scope": "mall",
    "parent": "mallsettings",
    "title": "成员管理",
    "icon": "member",
    "route": "/scopes/:scopeKind/:scopeId/settings/members",
    "component": "member",
    "order": 20,
    "entry": "member.members.read",
    "permissions": [
      "member.read"
    ],
    "capabilities": [
      "member.members.read"
    ],
    "requirements": [
      "MVPMALLSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "mallpartner",
    "surface": "console",
    "scope": "mall",
    "parent": "mallsettings",
    "title": "供应商与门店",
    "icon": "partner",
    "route": "/scopes/:scopeKind/:scopeId/settings/partners",
    "component": "partner",
    "order": 30,
    "entry": "partner.partners.read",
    "permissions": [
      "partner.read"
    ],
    "capabilities": [
      "partner.partners.read"
    ],
    "requirements": [
      "MVPMALLSETTING"
    ],
    "empty": "hide"
  },
  {
    "id": "platformcontrol",
    "surface": "console",
    "scope": "platform",
    "parent": null,
    "title": "智慧翼中控台",
    "icon": "control",
    "route": "/scopes/:scopeKind/:scopeId/control",
    "component": "control",
    "order": 10,
    "entry": "organization.layers.read",
    "permissions": [
      "organization.layer.read"
    ],
    "capabilities": [
      "organization.layers.read"
    ],
    "requirements": [
      "MVPPLATFORM"
    ],
    "empty": "hide"
  },
  {
    "id": "platformcatalog",
    "surface": "console",
    "scope": "platform",
    "parent": null,
    "title": "商品治理台",
    "icon": "product",
    "route": "/scopes/:scopeKind/:scopeId/products",
    "component": "product",
    "order": 20,
    "entry": "catalog.pools.read",
    "permissions": [
      "catalog.pool.read"
    ],
    "capabilities": [
      "catalog.pools.read"
    ],
    "requirements": [
      "MVPPLATFORM"
    ],
    "empty": "hide"
  },
  {
    "id": "platformvoucher",
    "surface": "console",
    "scope": "platform",
    "parent": null,
    "title": "卡券治理台",
    "icon": "voucher",
    "route": "/scopes/:scopeKind/:scopeId/vouchers",
    "component": "voucher",
    "order": 30,
    "entry": "voucher.cardlibraries.read",
    "permissions": [
      "voucher.cardlibrary.read"
    ],
    "capabilities": [
      "voucher.cardlibraries.read"
    ],
    "requirements": [
      "MVPPLATFORM"
    ],
    "empty": "hide"
  },
  {
    "id": "platformchannel",
    "surface": "console",
    "scope": "platform",
    "parent": null,
    "title": "渠道接入系统",
    "icon": "channel",
    "route": "/scopes/:scopeKind/:scopeId/channels",
    "component": "channel",
    "order": 40,
    "entry": "channel.connections.read",
    "permissions": [
      "channel.connection.read"
    ],
    "capabilities": [
      "channel.connections.read"
    ],
    "requirements": [
      "MVPPROVIDER"
    ],
    "empty": "hide"
  },
  {
    "id": "storehome",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "首页",
    "icon": "home",
    "route": "/",
    "component": "home",
    "order": 10,
    "entry": "storefront.bootstrap.read",
    "permissions": [],
    "capabilities": [
      "storefront.bootstrap.read"
    ],
    "requirements": [
      "MVPMALLDASHBOARD",
      "MVPMALLDESIGN"
    ],
    "empty": "hide"
  },
  {
    "id": "storecatalog",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "企业福利专区",
    "icon": "product",
    "route": "/products",
    "component": "catalog",
    "order": 20,
    "entry": "storefront.catalog.read",
    "permissions": [],
    "capabilities": [
      "storefront.catalog.read"
    ],
    "requirements": [
      "MVPMALLPOOL"
    ],
    "empty": "hide"
  },
  {
    "id": "storeproduct",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "商品详情",
    "icon": "product",
    "route": "/products/:productId",
    "component": "product",
    "order": 30,
    "entry": "storefront.catalog.read",
    "permissions": [],
    "capabilities": [
      "storefront.catalog.read"
    ],
    "requirements": [
      "MVPMALLPOOL"
    ],
    "empty": "hide"
  },
  {
    "id": "storecart",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "购物车",
    "icon": "cart",
    "route": "/cart",
    "component": "cart",
    "order": 40,
    "entry": "cart.current.read",
    "permissions": [
      "cart.read"
    ],
    "capabilities": [
      "cart.current.read"
    ],
    "requirements": [
      "MVPMALLORDER"
    ],
    "empty": "hide"
  },
  {
    "id": "storecheckout",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "确认结算",
    "icon": "cart",
    "route": "/checkout",
    "component": "checkout",
    "order": 50,
    "entry": "checkout.quotes.current.read",
    "permissions": [
      "checkout.create"
    ],
    "capabilities": [
      "checkout.quotes.current.read"
    ],
    "requirements": [
      "MVPMALLORDER"
    ],
    "empty": "hide"
  },
  {
    "id": "storepayment",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "支付结果",
    "icon": "finance",
    "route": "/payments/:paymentId/result",
    "component": "payment",
    "order": 60,
    "entry": "payment.intents.read",
    "permissions": [
      "payment.read"
    ],
    "capabilities": [
      "payment.intents.read"
    ],
    "requirements": [
      "MVPMALLORDER"
    ],
    "empty": "hide"
  },
  {
    "id": "storeorders",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "我的订单",
    "icon": "order",
    "route": "/orders",
    "component": "orders",
    "order": 70,
    "entry": "order.orders.read",
    "permissions": [
      "order.read"
    ],
    "capabilities": [
      "order.orders.read"
    ],
    "requirements": [
      "MVPMALLORDER"
    ],
    "empty": "hide"
  },
  {
    "id": "storeorder",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "订单详情",
    "icon": "order",
    "route": "/orders/:orderId",
    "component": "order",
    "order": 80,
    "entry": "order.orders.read",
    "permissions": [
      "order.read"
    ],
    "capabilities": [
      "order.orders.read"
    ],
    "requirements": [
      "MVPMALLORDER"
    ],
    "empty": "hide"
  },
  {
    "id": "storeaftersale",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "申请售后",
    "icon": "aftersale",
    "route": "/orders/:orderId/aftersales",
    "component": "aftersale",
    "order": 90,
    "entry": "order.aftersales.read",
    "permissions": [
      "order.aftersale.read"
    ],
    "capabilities": [
      "order.aftersales.read"
    ],
    "requirements": [
      "MVPMALLORDER"
    ],
    "empty": "hide"
  },
  {
    "id": "storevouchers",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "我的卡券",
    "icon": "voucher",
    "route": "/vouchers",
    "component": "vouchers",
    "order": 100,
    "entry": "voucher.bindings.read",
    "permissions": [
      "voucher.binding.read"
    ],
    "capabilities": [
      "voucher.bindings.read"
    ],
    "requirements": [
      "MVPMALLVOUCHER"
    ],
    "empty": "hide"
  },
  {
    "id": "storebenefits",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "福利账户",
    "icon": "finance",
    "route": "/benefits",
    "component": "benefits",
    "order": 110,
    "entry": "benefit.accounts.read",
    "permissions": [
      "benefit.read"
    ],
    "capabilities": [
      "benefit.accounts.read"
    ],
    "requirements": [
      "MVPMALLFINANCE"
    ],
    "empty": "hide"
  },
  {
    "id": "storeprofile",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "我的",
    "icon": "member",
    "route": "/profile",
    "component": "profile",
    "order": 120,
    "entry": "member.profile.read",
    "permissions": [
      "member.profile.read"
    ],
    "capabilities": [
      "member.profile.read"
    ],
    "requirements": [
      "MVPMALLPOOL",
      "MVPMALLORDER",
      "MVPMALLVOUCHER"
    ],
    "empty": "hide"
  },
  {
    "id": "storesecurity",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "安全中心",
    "icon": "security",
    "route": "/profile/security",
    "component": "security",
    "order": 130,
    "entry": "identity.sessions.read",
    "permissions": [
      "identity.session.read"
    ],
    "capabilities": [
      "identity.sessions.read"
    ],
    "requirements": [
      "MVPMALLSUPPORT"
    ],
    "empty": "hide"
  },
  {
    "id": "storesupport",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "客服中心",
    "icon": "support",
    "route": "/support",
    "component": "support",
    "order": 140,
    "entry": "support.cases.read",
    "permissions": [
      "support.case.read"
    ],
    "capabilities": [
      "support.cases.read"
    ],
    "requirements": [
      "MVPMALLSUPPORT"
    ],
    "empty": "hide"
  },
  {
    "id": "storesupportcase",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "客服会话",
    "icon": "support",
    "route": "/support/:caseId",
    "component": "supportcase",
    "order": 150,
    "entry": "support.messages.read",
    "permissions": [
      "support.message.read"
    ],
    "capabilities": [
      "support.messages.read"
    ],
    "requirements": [
      "MVPMALLSUPPORT"
    ],
    "empty": "hide"
  },
  {
    "id": "storenotifications",
    "surface": "storefront",
    "scope": "mall",
    "parent": null,
    "title": "消息通知",
    "icon": "notification",
    "route": "/notifications",
    "component": "notifications",
    "order": 160,
    "entry": "notification.notifications.read",
    "permissions": [
      "notification.read"
    ],
    "capabilities": [
      "notification.notifications.read"
    ],
    "requirements": [
      "MVPMALLSETTING"
    ],
    "empty": "hide"
  }
] as const;
export const NAVIGATION_CATALOG = Object.freeze(SOURCE.map((node) => Object.freeze({ ...node, permissions: Object.freeze([...node.permissions]), capabilities: Object.freeze([...node.capabilities]), requirements: Object.freeze([...node.requirements]) })));
export type NavigationNode = typeof NAVIGATION_CATALOG[number];
export type NavigationId = NavigationNode['id'];
export const NAVIGATION_BY_ID: ReadonlyMap<NavigationId, NavigationNode> = new Map(NAVIGATION_CATALOG.map((node) => [node.id, node]));
