// Generated by @shop/providergen from each extension Catalog.ts. Do not edit.
export type ProviderClient = 'console' | 'storefront' | 'miniapp' | 'store' | 'supplier';
export type ProviderConfigFieldKind = 'text' | 'url' | 'secretref' | 'endpoint';
export interface ProviderConfigField { readonly key: string; readonly label: string; readonly kind: ProviderConfigFieldKind; readonly required: boolean; readonly initial: string; readonly placeholder: string; readonly help: string; readonly operation?: string; }
export interface ProviderConfigForm { readonly schema: string; readonly healthOperation: string; readonly secretRefs: readonly string[]; readonly fields: readonly ProviderConfigField[]; }
export interface ProviderUiCatalog { readonly id: string; readonly name: string; readonly business: string; readonly clients: readonly ProviderClient[]; readonly settings: readonly string[]; readonly help: string; readonly transport: 'endpoint' | 'local'; readonly capabilities: readonly string[]; readonly form: ProviderConfigForm; }
export const PROVIDER_UI_CATALOGS: readonly ProviderUiCatalog[] = Object.freeze([
  {
    "id": "jdproduct",
    "name": "京东",
    "business": "综合实物商品",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "supplier"
    ],
    "settings": [
      "连接认证",
      "商品同步",
      "库存与价格",
      "订单履约",
      "账单与回调"
    ],
    "help": "连接京东商品、库存、订单、售后、物流和账单能力。",
    "transport": "endpoint",
    "capabilities": [
      "Catalog",
      "Price",
      "Inventory",
      "Order",
      "Cancel",
      "Return",
      "Logistics",
      "Refund",
      "Statement",
      "Webhook"
    ],
    "form": {
      "schema": "provider.jdproduct.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.catalog.pull",
          "label": "接口：商品目录 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/catalog/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "catalog.pull"
        },
        {
          "key": "endpoint.price.pull",
          "label": "接口：价格 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/price/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "price.pull"
        },
        {
          "key": "endpoint.inventory.pull",
          "label": "接口：库存 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/inventory/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "inventory.pull"
        },
        {
          "key": "endpoint.order.submit",
          "label": "接口：订单 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/order/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "order.submit"
        },
        {
          "key": "endpoint.order.cancel",
          "label": "接口：订单 · 取消",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/order/cancel",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "order.cancel"
        },
        {
          "key": "endpoint.logistics.pull",
          "label": "接口：物流 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/logistics/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "logistics.pull"
        },
        {
          "key": "endpoint.return.authorize",
          "label": "接口：退货 · 授权",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/return/authorize",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "return.authorize"
        },
        {
          "key": "endpoint.refund.submit",
          "label": "接口：退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "refund.submit"
        },
        {
          "key": "endpoint.statement.pull",
          "label": "接口：账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "statement.pull"
        }
      ]
    }
  },
  {
    "id": "jdfresh",
    "name": "京东生鲜",
    "business": "生鲜配送",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "supplier"
    ],
    "settings": [
      "连接认证",
      "区域可售",
      "温层与重量",
      "配送时段",
      "缺货替代"
    ],
    "help": "管理京东生鲜区域库存、配送时段、缺货替代与履约。",
    "transport": "endpoint",
    "capabilities": [
      "Catalog",
      "GeoStock",
      "TimeSlot",
      "Order",
      "Cancel",
      "Refund",
      "Delivery",
      "Statement",
      "Webhook"
    ],
    "form": {
      "schema": "provider.jdfresh.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.fresh.catalog.pull",
          "label": "接口：生鲜 · 商品目录 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/fresh/catalog/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "fresh.catalog.pull"
        },
        {
          "key": "endpoint.fresh.inventory.pull",
          "label": "接口：生鲜 · 库存 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/fresh/inventory/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "fresh.inventory.pull"
        },
        {
          "key": "endpoint.fresh.order.submit",
          "label": "接口：生鲜 · 订单 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/fresh/order/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "fresh.order.submit"
        },
        {
          "key": "endpoint.fresh.order.cancel",
          "label": "接口：生鲜 · 订单 · 取消",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/fresh/order/cancel",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "fresh.order.cancel"
        },
        {
          "key": "endpoint.fresh.delivery.pull",
          "label": "接口：生鲜 · 配送 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/fresh/delivery/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "fresh.delivery.pull"
        },
        {
          "key": "endpoint.fresh.refund.submit",
          "label": "接口：生鲜 · 退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/fresh/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "fresh.refund.submit"
        },
        {
          "key": "endpoint.fresh.statement.pull",
          "label": "接口：生鲜 · 账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/fresh/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "fresh.statement.pull"
        }
      ]
    }
  },
  {
    "id": "tmall",
    "name": "天猫超市",
    "business": "综合实物商品",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "supplier"
    ],
    "settings": [
      "连接认证",
      "商品同步",
      "库存与价格",
      "订单售后",
      "账单与回调"
    ],
    "help": "连接天猫商品、库存、订单、退款、物流和账单能力。",
    "transport": "endpoint",
    "capabilities": [
      "Catalog",
      "Price",
      "Inventory",
      "Order",
      "Cancel",
      "Return",
      "Logistics",
      "Refund",
      "Statement",
      "Webhook"
    ],
    "form": {
      "schema": "provider.tmall.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.catalog.pull",
          "label": "接口：商品目录 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/catalog/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "catalog.pull"
        },
        {
          "key": "endpoint.price.pull",
          "label": "接口：价格 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/price/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "price.pull"
        },
        {
          "key": "endpoint.inventory.pull",
          "label": "接口：库存 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/inventory/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "inventory.pull"
        },
        {
          "key": "endpoint.order.submit",
          "label": "接口：订单 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/order/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "order.submit"
        },
        {
          "key": "endpoint.order.cancel",
          "label": "接口：订单 · 取消",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/order/cancel",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "order.cancel"
        },
        {
          "key": "endpoint.logistics.pull",
          "label": "接口：物流 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/logistics/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "logistics.pull"
        },
        {
          "key": "endpoint.return.authorize",
          "label": "接口：退货 · 授权",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/return/authorize",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "return.authorize"
        },
        {
          "key": "endpoint.refund.submit",
          "label": "接口：退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "refund.submit"
        },
        {
          "key": "endpoint.statement.pull",
          "label": "接口：账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "statement.pull"
        }
      ]
    }
  },
  {
    "id": "supplier",
    "name": "自有供应商",
    "business": "标准供应商",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "supplier"
    ],
    "settings": [
      "商品目录",
      "库存报价",
      "订单履约",
      "退货退款",
      "供应商账单"
    ],
    "help": "通过平台受控接口管理自有供应商商品、库存、订单和账单。",
    "transport": "local",
    "capabilities": [
      "Catalog",
      "Price",
      "Inventory",
      "Order",
      "Shipment",
      "Return",
      "Refund",
      "Statement"
    ],
    "form": {
      "schema": "provider.supplier.v1",
      "healthOperation": "local",
      "secretRefs": [],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        }
      ]
    }
  },
  {
    "id": "cake",
    "name": "蛋糕",
    "business": "蛋糕预约配送",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "store",
      "supplier"
    ],
    "settings": [
      "品牌连接",
      "规格与门店",
      "配送范围",
      "预约时段",
      "核销与账单"
    ],
    "help": "管理蛋糕规格、门店范围、预约、祝福语、配送和核销。",
    "transport": "endpoint",
    "capabilities": [
      "Catalog",
      "GeoStore",
      "TimeSlot",
      "Order",
      "Cancel",
      "Delivery",
      "Refund",
      "Statement",
      "Verify",
      "Webhook"
    ],
    "form": {
      "schema": "provider.cake.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.cake.product.pull",
          "label": "接口：蛋糕 · 商品 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/cake/product/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "cake.product.pull"
        },
        {
          "key": "endpoint.cake.slot.pull",
          "label": "接口：蛋糕 · 时段 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/cake/slot/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "cake.slot.pull"
        },
        {
          "key": "endpoint.cake.order.submit",
          "label": "接口：蛋糕 · 订单 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/cake/order/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "cake.order.submit"
        },
        {
          "key": "endpoint.cake.order.cancel",
          "label": "接口：蛋糕 · 订单 · 取消",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/cake/order/cancel",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "cake.order.cancel"
        },
        {
          "key": "endpoint.cake.delivery.pull",
          "label": "接口：蛋糕 · 配送 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/cake/delivery/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "cake.delivery.pull"
        },
        {
          "key": "endpoint.cake.redeem.verify",
          "label": "接口：蛋糕 · 核销 · 核验",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/cake/redeem/verify",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "cake.redeem.verify"
        },
        {
          "key": "endpoint.cake.refund.submit",
          "label": "接口：蛋糕 · 退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/cake/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "cake.refund.submit"
        },
        {
          "key": "endpoint.cake.statement.pull",
          "label": "接口：蛋糕 · 账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/cake/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "cake.statement.pull"
        }
      ]
    }
  },
  {
    "id": "flower",
    "name": "鲜花",
    "business": "鲜花预约配送",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "store",
      "supplier"
    ],
    "settings": [
      "品牌连接",
      "花材规格",
      "城市与日期",
      "节日容量",
      "替代与账单"
    ],
    "help": "管理鲜花规格、配送城市、日期、卡片和缺货替代。",
    "transport": "endpoint",
    "capabilities": [
      "Catalog",
      "GeoDelivery",
      "TimeSlot",
      "Order",
      "Substitute",
      "Cancel",
      "Delivery",
      "Refund",
      "Statement",
      "Webhook"
    ],
    "form": {
      "schema": "provider.flower.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.flower.product.pull",
          "label": "接口：鲜花 · 商品 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/flower/product/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "flower.product.pull"
        },
        {
          "key": "endpoint.flower.slot.pull",
          "label": "接口：鲜花 · 时段 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/flower/slot/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "flower.slot.pull"
        },
        {
          "key": "endpoint.flower.order.submit",
          "label": "接口：鲜花 · 订单 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/flower/order/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "flower.order.submit"
        },
        {
          "key": "endpoint.flower.order.cancel",
          "label": "接口：鲜花 · 订单 · 取消",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/flower/order/cancel",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "flower.order.cancel"
        },
        {
          "key": "endpoint.flower.delivery.pull",
          "label": "接口：鲜花 · 配送 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/flower/delivery/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "flower.delivery.pull"
        },
        {
          "key": "endpoint.flower.refund.submit",
          "label": "接口：鲜花 · 退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/flower/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "flower.refund.submit"
        },
        {
          "key": "endpoint.flower.statement.pull",
          "label": "接口：鲜花 · 账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/flower/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "flower.statement.pull"
        }
      ]
    }
  },
  {
    "id": "book",
    "name": "图书",
    "business": "图书零售",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "supplier"
    ],
    "settings": [
      "连接认证",
      "ISBN 与出版社",
      "库存与价格",
      "订单物流",
      "账单与回调"
    ],
    "help": "管理图书 ISBN、出版社、套装、预售、库存和履约。",
    "transport": "endpoint",
    "capabilities": [
      "Catalog",
      "Price",
      "Inventory",
      "Order",
      "Cancel",
      "Return",
      "Shipment",
      "Refund",
      "Statement",
      "Webhook"
    ],
    "form": {
      "schema": "provider.book.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.book.catalog.pull",
          "label": "接口：图书 · 商品目录 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/catalog/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.catalog.pull"
        },
        {
          "key": "endpoint.book.price.pull",
          "label": "接口：图书 · 价格 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/price/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.price.pull"
        },
        {
          "key": "endpoint.book.inventory.pull",
          "label": "接口：图书 · 库存 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/inventory/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.inventory.pull"
        },
        {
          "key": "endpoint.book.order.submit",
          "label": "接口：图书 · 订单 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/order/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.order.submit"
        },
        {
          "key": "endpoint.book.order.cancel",
          "label": "接口：图书 · 订单 · 取消",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/order/cancel",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.order.cancel"
        },
        {
          "key": "endpoint.book.shipment.pull",
          "label": "接口：图书 · 发货 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/shipment/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.shipment.pull"
        },
        {
          "key": "endpoint.book.return.authorize",
          "label": "接口：图书 · 退货 · 授权",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/return/authorize",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.return.authorize"
        },
        {
          "key": "endpoint.book.return.submit",
          "label": "接口：图书 · 退货 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/return/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.return.submit"
        },
        {
          "key": "endpoint.book.statement.pull",
          "label": "接口：图书 · 账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/book/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "book.statement.pull"
        }
      ]
    }
  },
  {
    "id": "charge",
    "name": "虚拟卡券与直充",
    "business": "手机与油卡直充",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "supplier"
    ],
    "settings": [
      "连接认证",
      "充值品类",
      "号码规则",
      "结果查询",
      "回调与对账"
    ],
    "help": "管理手机、油卡等直充商品、号码校验和未知结果恢复。",
    "transport": "endpoint",
    "capabilities": [
      "Catalog",
      "Issue",
      "DirectCharge",
      "Query",
      "Refund",
      "Statement",
      "Verify",
      "Webhook"
    ],
    "form": {
      "schema": "provider.charge.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.charge.product.pull",
          "label": "接口：充值 · 商品 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/charge/product/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "charge.product.pull"
        },
        {
          "key": "endpoint.charge.submit",
          "label": "接口：充值 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/charge/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "charge.submit"
        },
        {
          "key": "endpoint.charge.query",
          "label": "接口：充值 · 查询",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/charge/query",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "charge.query"
        },
        {
          "key": "endpoint.charge.verify",
          "label": "接口：充值 · 核验",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/charge/verify",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "charge.verify"
        },
        {
          "key": "endpoint.charge.refund.submit",
          "label": "接口：充值 · 退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/charge/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "charge.refund.submit"
        },
        {
          "key": "endpoint.charge.statement.pull",
          "label": "接口：充值 · 账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/charge/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "charge.statement.pull"
        }
      ]
    }
  },
  {
    "id": "foodvoucher",
    "name": "食品提货券",
    "business": "餐饮电子提货券",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "store",
      "supplier"
    ],
    "settings": [
      "品牌连接",
      "券商品",
      "适用门店",
      "发码与核销",
      "退款与账单"
    ],
    "help": "管理餐饮券商品、适用门店、电子码发放、核销和退款。",
    "transport": "endpoint",
    "capabilities": [
      "Catalog",
      "GeoStore",
      "Issue",
      "Bind",
      "Verify",
      "Void",
      "Extend",
      "Refund",
      "Statement",
      "Webhook"
    ],
    "form": {
      "schema": "provider.foodvoucher.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.voucher.product.pull",
          "label": "接口：电子券 · 商品 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/voucher/product/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "voucher.product.pull"
        },
        {
          "key": "endpoint.voucher.issue",
          "label": "接口：电子券 · 发放",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/voucher/issue",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "voucher.issue"
        },
        {
          "key": "endpoint.voucher.void",
          "label": "接口：电子券 · 作废",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/voucher/void",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "voucher.void"
        },
        {
          "key": "endpoint.voucher.verify",
          "label": "接口：电子券 · 核验",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/voucher/verify",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "voucher.verify"
        },
        {
          "key": "endpoint.voucher.refund.submit",
          "label": "接口：电子券 · 退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/voucher/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "voucher.refund.submit"
        },
        {
          "key": "endpoint.voucher.statement.pull",
          "label": "接口：电子券 · 账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/voucher/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "voucher.statement.pull"
        }
      ]
    }
  },
  {
    "id": "movie",
    "name": "电影",
    "business": "电影选座出票",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "supplier"
    ],
    "settings": [
      "连接认证",
      "城市与影院",
      "影片场次",
      "锁座出票",
      "退款与对账"
    ],
    "help": "管理影院、影片、场次、座位、锁座、出票和退款。",
    "transport": "endpoint",
    "capabilities": [
      "Cinema",
      "Show",
      "SeatLock",
      "Order",
      "Issue",
      "Cancel",
      "Refund",
      "Statement",
      "Verify",
      "Webhook"
    ],
    "form": {
      "schema": "provider.movie.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.movie.show.pull",
          "label": "接口：电影 · 场次 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/movie/show/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "movie.show.pull"
        },
        {
          "key": "endpoint.movie.seat.pull",
          "label": "接口：电影 · 座位 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/movie/seat/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "movie.seat.pull"
        },
        {
          "key": "endpoint.movie.order.submit",
          "label": "接口：电影 · 订单 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/movie/order/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "movie.order.submit"
        },
        {
          "key": "endpoint.movie.order.cancel",
          "label": "接口：电影 · 订单 · 取消",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/movie/order/cancel",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "movie.order.cancel"
        },
        {
          "key": "endpoint.movie.verify",
          "label": "接口：电影 · 核验",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/movie/verify",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "movie.verify"
        },
        {
          "key": "endpoint.movie.refund.submit",
          "label": "接口：电影 · 退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/movie/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "movie.refund.submit"
        },
        {
          "key": "endpoint.movie.statement.pull",
          "label": "接口：电影 · 账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/movie/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "movie.statement.pull"
        }
      ]
    }
  },
  {
    "id": "meal",
    "name": "在线点餐",
    "business": "连锁餐饮点餐",
    "clients": [
      "console",
      "storefront",
      "miniapp",
      "store",
      "supplier"
    ],
    "settings": [
      "品牌连接",
      "套餐与门店",
      "预约时段",
      "电子凭证",
      "核销与退款"
    ],
    "help": "管理套餐组成、门店、预约、电子凭证、核销和退款。",
    "transport": "endpoint",
    "capabilities": [
      "Brand",
      "Store",
      "Menu",
      "Option",
      "Price",
      "Inventory",
      "Order",
      "Pickup",
      "Cancel",
      "Refund",
      "Statement",
      "Verify",
      "Webhook"
    ],
    "form": {
      "schema": "provider.meal.v1",
      "healthOperation": "health",
      "secretRefs": [
        "credential"
      ],
      "fields": [
        {
          "key": "region",
          "label": "部署区域",
          "kind": "text",
          "required": true,
          "initial": "cn",
          "placeholder": "例如：cn-east-1",
          "help": "用于区域路由、数据驻留和同步水位隔离。"
        },
        {
          "key": "baseUrl",
          "label": "服务地址",
          "kind": "url",
          "required": true,
          "initial": "",
          "placeholder": "https://provider.example.com",
          "help": "仅允许 HTTPS 地址，不得包含账号、口令、查询参数或片段。"
        },
        {
          "key": "secretRef",
          "label": "密钥引用",
          "kind": "secretref",
          "required": true,
          "initial": "",
          "placeholder": "secret/channel/credential",
          "help": "引用密钥管理系统中包含 credential 的安全条目；明文不会进入浏览器。"
        },
        {
          "key": "endpoint.health",
          "label": "接口：健康检查",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/health",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "health"
        },
        {
          "key": "endpoint.meal.menu.pull",
          "label": "接口：餐饮 · 菜单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/menu/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.menu.pull"
        },
        {
          "key": "endpoint.meal.price.pull",
          "label": "接口：餐饮 · 价格 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/price/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.price.pull"
        },
        {
          "key": "endpoint.meal.inventory.pull",
          "label": "接口：餐饮 · 库存 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/inventory/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.inventory.pull"
        },
        {
          "key": "endpoint.meal.order.submit",
          "label": "接口：餐饮 · 订单 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/order/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.order.submit"
        },
        {
          "key": "endpoint.meal.order.cancel",
          "label": "接口：餐饮 · 订单 · 取消",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/order/cancel",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.order.cancel"
        },
        {
          "key": "endpoint.meal.pickup.query",
          "label": "接口：餐饮 · 取餐 · 查询",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/pickup/query",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.pickup.query"
        },
        {
          "key": "endpoint.meal.pickup.verify",
          "label": "接口：餐饮 · 取餐 · 核验",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/pickup/verify",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.pickup.verify"
        },
        {
          "key": "endpoint.meal.refund.submit",
          "label": "接口：餐饮 · 退款 · 提交",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/refund/submit",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.refund.submit"
        },
        {
          "key": "endpoint.meal.statement.pull",
          "label": "接口：餐饮 · 账单 · 拉取",
          "kind": "endpoint",
          "required": true,
          "initial": "",
          "placeholder": "/meal/statement/pull",
          "help": "填写该能力在服务商侧的相对路径；不得包含域名、查询参数或密钥。",
          "operation": "meal.statement.pull"
        }
      ]
    }
  }
]);
const CATALOG_BY_ID: Readonly<Record<string, ProviderUiCatalog>> = Object.freeze(Object.fromEntries(PROVIDER_UI_CATALOGS.map((catalog) => [catalog.id, catalog])));
export function providerUiCatalog(id: string): ProviderUiCatalog { const catalog = CATALOG_BY_ID[id]; if (!catalog) throw new Error(`PROVIDER_UI_CATALOG_MISSING:${id}`); return catalog; }
