import { Dialog } from '@shop/design';
import type { VoucherActionViewModel } from '../viewmodel/VoucherActionViewModel';
import { DialogFooter } from './DialogFooter';

export function ProgramDialog({ model, onClose }: Readonly<{ model: VoucherActionViewModel; onClose: () => void }>) {
  if (model.action?.kind !== 'createprogram' && model.action?.kind !== 'editprogram') return null;
  const invalid = !model.name.trim() || Number(model.amount) <= 0 || model.days < 1 || model.days > 3650;
  return <Dialog open title={model.action.kind === 'createprogram' ? '新建卡券' : '编辑卡券方案'} eyebrow="卡券方案 · 版本管理" onClose={onClose} dismissable={!model.busy}><form onSubmit={(event) => { event.preventDefault(); model.actions.submit(); }}><div className="vouchercreatorbody"><label className="vouchercreatorfield">卡券名称<input aria-label="卡券名称" value={model.name} onChange={(event) => model.actions.name(event.target.value)} maxLength={80} /></label><div className="vouchercreatorgrid"><label className="vouchercreatorfield">面值（元）<input aria-label="面值（元）" inputMode="decimal" value={model.amount} onChange={(event) => model.actions.amount(event.target.value)} /></label><label className="vouchercreatorfield">有效天数<input aria-label="有效天数" type="number" min={1} max={3650} value={model.days} onChange={(event) => model.actions.days(Number(event.target.value))} /></label></div><label className="vouchercreatorfield">方案状态<select value={model.status} onChange={(event) => model.actions.status(event.target.value as typeof model.status)}><option value="draft">草稿</option><option value="active">启用</option><option value="paused">暂停</option><option value="retired">结束</option></select></label><label className="vouchercreatorchoice"><input aria-label="发行前需要审批" type="checkbox" checked={model.approvalRequired} onChange={(event) => model.actions.approvalRequired(event.target.checked)} /><span><strong>发行前需要审批</strong><small>开启后必须先完成备券审批，才能创建发行批次。</small></span></label>{model.error ? <p role="alert">{model.error}</p> : null}</div><DialogFooter busy={model.busy} disabled={invalid} label="保存方案" onClose={onClose} /></form></Dialog>;
}
