services:
  build:
    image: zdt-actions-runner:2.337.0
    platform: linux/amd64
    restart: unless-stopped
    command: ["run"]
    user: "1001:1001"
    volumes:
      - zdt-actions-build:/runner-state
    networks:
      - build-egress
    cpus: 6
    mem_limit: 6g
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=1g

  release:
    image: zdt-actions-runner:2.337.0
    platform: linux/amd64
    restart: unless-stopped
    command: ["run"]
    user: "1001:1001"
    volumes:
      - zdt-actions-release:/runner-state
    networks:
      - release-egress
    cpus: 2
    mem_limit: 2g
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=256m

volumes:
  zdt-actions-build:
    name: zdt-actions-build
    external: true
  zdt-actions-release:
    name: zdt-actions-release
    external: true

networks:
  build-egress:
    internal: false
  release-egress:
    internal: false
