import { defineModuleManifest } from '@shop/kernel';
import { REPORTING_CAPABILITIES } from './01_public_gongkai/ReportingCapabilities';

export const reportingManifest = defineModuleManifest({
  id: 'reporting',
  version: '1.0.0',
  kind: 'business',
  provides: [REPORTING_CAPABILITIES.read, REPORTING_CAPABILITIES.manage],
  requires: [],
  operations: [
    'reporting.dashboard.read',
    'reporting.sales.read',
    'reporting.products.read',
    'reporting.malls.read',
    'reporting.categories.read',
    'reporting.channels.read',
    'reporting.powderclass.read',
    'reporting.voucherconsumption.read',
    'reporting.exports.create',
    'reporting.exports.read',
  ],
  publishes: [],
  consumes: [
    'identity.session.created',
    'identity.member.registered',
    'access.version.changed',
    'catalog.listing.published',
    'inventory.stock.changed',
    'inventory.stock.reserved',
    'experience.published',
    'checkout.quote.confirmed',
    'voucher.issued',
    'benefit.granted',
    'benefit.expired',
    'benefit.revoked',
    'finance.entry.posted',
    'finance.settlement.approved',
    'finance.settlement.adjusted',
    'finance.withdrawal.paid',
    'invoice.issued',
    'invoice.red.issued',
    'support.message.sent',
    'support.ticket.assigned',
    'channel.sync.completed',
    'channel.webhook.applied',
    'channel.refund.changed',
    'notification.delivered',
    'risk.policy.activated',
    'order.placed',
    'order.paid',
    'order.cancelled',
    'fulfillment.shipped',
    'payment.refunded',
    'voucher.redeemed',
    'finance.period.closed',
  ],
  publicEntry: './index.ts',
  layers: ['public', 'domain', 'application', 'adapters', 'interface', 'tests'],
  entrypoints: {
    http: ['reportingRoutes', 'reportingOperatorReadOperations'],
    jobs: ['projection', 'export'],
  },
});
