import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { isAbsolute, resolve } from 'node:path';
import { parse, stringify } from 'yaml';

import { loadRequirementAuthority } from './Authority';
import { Workbook } from './WorkbookReader';

export type TraceStatus = 'Existing' | 'Designed' | 'Missing';

export interface TraceNode {
  readonly status: TraceStatus;
  readonly target: string;
  readonly evidence: readonly string[];
}

export interface OrderWorkbookEvidence {
  readonly authority: string;
  readonly logicalSource: string;
  readonly workbookSha256: string;
  readonly repositoryRelativePath: string;
  readonly sheet: string;
  readonly range: string;
  readonly cells: readonly string[];
}

export interface OrderRequirement {
  readonly id: string;
  readonly version: number;
  readonly title: string;
  readonly description: string;
  readonly wave: number;
  readonly priority: string;
  readonly workbookEvidence: readonly OrderWorkbookEvidence[];
  readonly roles: readonly string[];
  readonly scopeHierarchy: Readonly<{ kinds: readonly string[]; rule: string }>;
  readonly owner: string;
  readonly collaboratingModules: readonly string[];
  readonly uiRoute: string;
  readonly existingOperations: readonly string[];
  readonly plannedOperations: readonly string[];
  readonly operationStatus: TraceStatus;
  readonly operationCoverage: string;
  readonly dataObjectsAndProjections: readonly TraceNode[];
  readonly successDefinition: readonly string[];
  readonly exceptionsAndRejections: readonly string[];
  readonly performanceTarget: string;
  readonly securityPolicyStatement: string;
  readonly futureWorkPackages: readonly string[];
  readonly testPlans: Readonly<Record<TestKind, TraceNode>>;
  readonly runbookTarget: TraceNode;
  readonly releaseEvidenceTarget: TraceNode;
  readonly lifecycleStatus: 'Designed';
  readonly evidence: readonly string[];
  readonly trace: Readonly<Record<string, TraceNode | readonly TraceNode[]>>;
}

export interface OrderRequirementProfile {
  readonly source: string;
  readonly workbookSha256: string;
  readonly generated: true;
  readonly profile: string;
  readonly authority: string;
  readonly count: number;
  readonly chain: readonly string[];
  readonly productBaseline: Readonly<Record<string, string>>;
  readonly requirements: readonly OrderRequirement[];
}

interface OperationRecord {
  readonly id: string;
  readonly owner: string;
  readonly handler: string;
  readonly requirements: readonly string[];
}

const TEST_KINDS = Object.freeze(['Unit', 'Contract', 'Integration', 'Journey', 'Browser', 'Performance', 'Recovery'] as const);
type TestKind = typeof TEST_KINDS[number];

export const ORDER_REQUIREMENT_IDS: readonly string[] = Object.freeze(
  Array.from({ length: 14 }, (_, index) => 'OMS-' + String(index + 1).padStart(3, '0')),
);

const GENERATED_HEADER = '# Generated by @shop/requirementgen from 04_tools/tools/requirementgen/definitions/order.yml. Do not edit.\n';
const PLACEHOLDER_PATTERN = new RegExp('\\b(?:TO' + 'DO|TB' + 'D)\\b', 'i');

export async function loadOrderRequirementProfile(root: string): Promise<Readonly<OrderRequirementProfile>> {
  const authorityName = 'orderRequirements';
  const loaded = await loadRequirementAuthority(root, authorityName);
  const workbook = new Workbook(loaded.bytes);
  for (const [sheet, expectedRows] of Object.entries(loaded.authority.sheets)) {
    const actualRows = workbook.maxRow(sheet);
    if (actualRows !== expectedRows) throw new Error('ORDER_REQUIREMENT_SHEET_ROWS_INVALID:' + sheet + ':' + actualRows + ':' + expectedRows);
  }

  const definitionPath = resolve(root, '04_tools/tools/requirementgen/definitions/order.yml');
  const source = objectValue(parse(await readFile(definitionPath, 'utf8')), 'root');
  if (numberValue(source.version, 'version') !== 1) fail('version');
  if (stringValue(source.authority, 'authority') !== authorityName) fail('authority');
  const profile = stringValue(source.profile, 'profile');
  if (loaded.authority.profile !== profile) fail('profile');
  const chain = stringArray(source.chain, 'chain');
  const expectedChain = ['WorkbookCell', 'Requirement', 'UIRoute', 'Operation', 'Owner', 'Handler', 'RepositoryOrProjection', 'Test', 'Runbook', 'ReleaseEvidence', 'WorkPackage'];
  if (chain.join(',') !== expectedChain.join(',')) fail('chain');
  const productBaseline = stringRecord(source.productBaseline, 'productBaseline');
  const operations = await loadOperations(root);
  const operationById = new Map(operations.map((operation) => [operation.id, operation]));
  const definitions = arrayValue(source.requirements, 'requirements');
  const ids = definitions.map((value, index) => stringValue(objectValue(value, 'requirements:' + index).id, 'requirements:' + index + ':id'));
  validateOrderRequirementIds(ids);
  const requirements = definitions.map((value, index) => requirementValue(
    root,
    objectValue(value, 'requirements:' + index),
    'requirements:' + ids[index],
    loaded.authority.logicalSource,
    loaded.authority.repositoryRelativePath,
    loaded.authority.sha256,
    authorityName,
    workbook,
    operationById,
  ));
  const serialized = JSON.stringify(source);
  if (PLACEHOLDER_PATTERN.test(serialized)) throw new Error('ORDER_REQUIREMENT_PLACEHOLDER_FORBIDDEN');
  return deepFreeze({
    source: loaded.authority.logicalSource,
    workbookSha256: loaded.authority.sha256,
    generated: true,
    profile,
    authority: authorityName,
    count: requirements.length,
    chain,
    productBaseline,
    requirements,
  });
}

export function orderRequirementYaml(profile: Readonly<OrderRequirementProfile>): string {
  return GENERATED_HEADER + stringify(profile, { lineWidth: 0 });
}

export function validateOrderRequirementIds(ids: readonly string[]): void {
  if (ids.join(',') !== ORDER_REQUIREMENT_IDS.join(',') || new Set(ids).size !== ORDER_REQUIREMENT_IDS.length) {
    throw new Error('ORDER_REQUIREMENT_IDS_INVALID:' + ids.join(','));
  }
}

function requirementValue(
  root: string,
  source: Record<string, unknown>,
  location: string,
  logicalSource: string,
  repositoryRelativePath: string,
  workbookSha256: string,
  authority: string,
  workbook: Workbook,
  operationById: ReadonlyMap<string, OperationRecord>,
): OrderRequirement {
  const id = stringValue(source.id, location + ':id');
  const version = numberValue(source.version, location + ':version');
  if (version !== 1) fail(location + ':version');
  const wave = numberValue(source.wave, location + ':wave');
  if (wave !== 1 && wave !== 2) fail(location + ':wave');
  const priority = stringValue(source.priority, location + ':priority');
  if (!/^P[0-2]$/.test(priority)) fail(location + ':priority');
  const rawEvidence = arrayValue(source.workbookEvidence, location + ':workbookEvidence');
  if (rawEvidence.length === 0) fail(location + ':workbookEvidence');
  const workbookEvidence = rawEvidence.map((value, index): OrderWorkbookEvidence => {
    const evidence = objectValue(value, location + ':workbookEvidence:' + index);
    const sheet = stringValue(evidence.sheet, location + ':workbookEvidence:' + index + ':sheet');
    const range = stringValue(evidence.range, location + ':workbookEvidence:' + index + ':range');
    const cells = workbook.range(sheet, range).map(({ reference }) => reference);
    return deepFreeze({ authority, logicalSource, workbookSha256, repositoryRelativePath, sheet, range, cells });
  });
  const existingOperations = uniqueStrings(source.existingOperations, location + ':existingOperations');
  const plannedOperations = uniqueStrings(source.plannedOperations, location + ':plannedOperations');
  if (existingOperations.length === 0 && plannedOperations.length === 0) fail(location + ':operations');
  for (const operation of existingOperations) {
    const registered = operationById.get(operation);
    if (!registered) throw new Error('ORDER_REQUIREMENT_EXISTING_OPERATION_MISSING:' + id + ':' + operation);
    if (!registered.requirements.includes(id)) throw new Error('ORDER_REQUIREMENT_OPERATION_BACKLINK_MISSING:' + id + ':' + operation);
  }
  for (const operation of plannedOperations) {
    if (!/^[a-z]+(?:\.[a-z]+)+$/.test(operation)) throw new Error('ORDER_REQUIREMENT_PLANNED_OPERATION_INVALID:' + id + ':' + operation);
    if (operationById.has(operation)) throw new Error('ORDER_REQUIREMENT_PLANNED_OPERATION_REGISTERED:' + id + ':' + operation);
  }
  if (existingOperations.some((operation) => plannedOperations.includes(operation))) fail(location + ':operations:overlap');
  const operationStatus: TraceStatus = plannedOperations.length > 0 ? 'Designed' : 'Existing';
  const uiRouteEvidence = evidencePaths(root, source.uiRouteEvidence, location + ':uiRouteEvidence', true);
  const dataObjectsAndProjections = arrayValue(source.dataObjectsAndProjections, location + ':dataObjectsAndProjections')
    .map((value, index) => traceNodeValue(root, value, location + ':dataObjectsAndProjections:' + index));
  if (dataObjectsAndProjections.length === 0) fail(location + ':dataObjectsAndProjections');
  const testSource = objectValue(source.testPlans, location + ':testPlans');
  const testPlans = Object.fromEntries(TEST_KINDS.map((kind) => [kind, traceNode('Designed', stringValue(testSource[kind], location + ':testPlans:' + kind), [])])) as Record<TestKind, TraceNode>;
  const futureWorkPackages = uniqueStrings(source.futureWorkPackages, location + ':futureWorkPackages');
  if (futureWorkPackages.length === 0 || futureWorkPackages.some((workPackage) => !/^[A-H]\d{2}$/.test(workPackage))) fail(location + ':futureWorkPackages');
  const runbookTarget = traceNode('Designed', '05_docs_ziliao/docs_wendang/operations/' + slugValue(source.runbookSlug, location + ':runbookSlug') + '.md', []);
  const releaseEvidenceTarget = traceNode('Designed', 'evidence/releases/' + id + '.json', []);
  if (source.lifecycleStatus !== 'Designed') fail(location + ':lifecycleStatus');
  const owner = stringValue(source.owner, location + ':owner');
  const ownerDirectory = owner === 'order' ? 'order_dingdan' : owner;
  const ownerPath = '01_core_hexin/services/commerce/src/modules/' + ownerDirectory;
  evidencePaths(root, [ownerPath], location + ':owner', true);
  const operationTrace = [
    ...existingOperations.map((operation) => traceNode('Existing', operation, ['01_core_hexin/packages/contract/definitions/operations.yml'])),
    ...plannedOperations.map((operation) => traceNode('Designed', operation, [])),
  ];
  const handlerTrace = [
    ...existingOperations.map((operation) => {
      const record = operationById.get(operation)!;
      evidencePaths(root, [record.handler], location + ':handler:' + operation, true);
      return traceNode('Existing', operation + ' -> ' + record.handler, [record.handler]);
    }),
    ...plannedOperations.map((operation) => traceNode('Missing', operation + ' handler', [])),
  ];
  const evidence = unique([
    ...workbookEvidence.map(({ sheet, range }) => repositoryRelativePath + '#' + sheet + '!' + range),
    ...existingOperations.map((operation) => '01_core_hexin/packages/contract/definitions/operations.yml#' + operation),
    ...uiRouteEvidence,
    ...dataObjectsAndProjections.flatMap((target) => target.evidence),
  ]);
  const trace: Readonly<Record<string, TraceNode | readonly TraceNode[]>> = deepFreeze({
    workbookCell: workbookEvidence.map(({ sheet, range }) => traceNode('Existing', logicalSource + '#' + sheet + '!' + range, [repositoryRelativePath])),
    requirement: traceNode('Designed', id, []),
    uiRoute: traceNode('Existing', stringValue(source.uiRoute, location + ':uiRoute'), uiRouteEvidence),
    operation: operationTrace,
    owner: traceNode('Existing', owner, [ownerPath]),
    handler: handlerTrace,
    repositoryOrProjection: dataObjectsAndProjections,
    test: Object.values(testPlans),
    runbook: runbookTarget,
    releaseEvidence: releaseEvidenceTarget,
    workPackage: futureWorkPackages.map((workPackage) => traceNode('Designed', workPackage, [])),
  });
  return deepFreeze({
    id,
    version,
    title: stringValue(source.title, location + ':title'),
    description: stringValue(source.description, location + ':description'),
    wave,
    priority,
    workbookEvidence,
    roles: uniqueStrings(source.roles, location + ':roles'),
    scopeHierarchy: scopeValue(source.scopeHierarchy, location + ':scopeHierarchy'),
    owner,
    collaboratingModules: uniqueStrings(source.collaboratingModules, location + ':collaboratingModules'),
    uiRoute: stringValue(source.uiRoute, location + ':uiRoute'),
    existingOperations,
    plannedOperations,
    operationStatus,
    operationCoverage: stringValue(source.operationCoverage, location + ':operationCoverage'),
    dataObjectsAndProjections,
    successDefinition: nonEmptyStrings(source.successDefinition, location + ':successDefinition'),
    exceptionsAndRejections: nonEmptyStrings(source.exceptionsAndRejections, location + ':exceptionsAndRejections'),
    performanceTarget: stringValue(source.performanceTarget, location + ':performanceTarget'),
    securityPolicyStatement: stringValue(source.securityPolicyStatement, location + ':securityPolicyStatement'),
    futureWorkPackages,
    testPlans,
    runbookTarget,
    releaseEvidenceTarget,
    lifecycleStatus: 'Designed',
    evidence,
    trace,
  });
}

async function loadOperations(root: string): Promise<readonly OperationRecord[]> {
  const sharedHandler = '01_core_hexin/services/commerce/src/foundation/application/OperationHandler.ts';
  const document = objectValue(parse(await readFile(resolve(root, '01_core_hexin/packages/contract/definitions/operations.yml'), 'utf8')), 'operations');
  return arrayValue(document.operations, 'operations').map((value, index) => {
    const operation = objectValue(value, 'operations:' + index);
    return deepFreeze({
      id: stringValue(operation.id, 'operations:' + index + ':id'),
      owner: stringValue(operation.owner, 'operations:' + index + ':owner'),
      handler: operation.handler === undefined
        ? sharedHandler
        : stringValue(operation.handler, 'operations:' + index + ':handler'),
      requirements: stringArray(operation.requirements, 'operations:' + index + ':requirements'),
    });
  });
}

function traceNodeValue(root: string, value: unknown, location: string): TraceNode {
  const source = objectValue(value, location);
  const status = statusValue(source.status, location + ':status');
  const evidence = evidencePaths(root, source.evidence, location + ':evidence', status === 'Existing');
  if (status !== 'Existing' && evidence.length > 0) throw new Error('ORDER_REQUIREMENT_PREMATURE_EVIDENCE:' + location);
  return traceNode(status, stringValue(source.target, location + ':target'), evidence);
}

function traceNode(status: TraceStatus, target: string, evidence: readonly string[]): TraceNode {
  return deepFreeze({ status, target, evidence });
}

function scopeValue(value: unknown, location: string): Readonly<{ kinds: readonly string[]; rule: string }> {
  const source = objectValue(value, location);
  return deepFreeze({ kinds: nonEmptyStrings(source.kinds, location + ':kinds'), rule: stringValue(source.rule, location + ':rule') });
}

function statusValue(value: unknown, location: string): TraceStatus {
  if (value !== 'Existing' && value !== 'Designed' && value !== 'Missing') fail(location);
  return value;
}

function slugValue(value: unknown, location: string): string {
  const slug = stringValue(value, location);
  if (!/^[a-z]+(?:-[a-z]+)*$/.test(slug)) fail(location);
  return slug;
}

function evidencePaths(root: string, value: unknown, location: string, required: boolean): readonly string[] {
  const paths = uniqueStrings(value, location);
  if (required && paths.length === 0) fail(location);
  for (const path of paths) {
    if (isAbsolute(path) || path.split(/[\\/]/).includes('..')) throw new Error('ORDER_REQUIREMENT_EVIDENCE_PATH_INVALID:' + path);
    if (!existsSync(resolve(root, path))) throw new Error('ORDER_REQUIREMENT_EVIDENCE_MISSING:' + path);
  }
  return paths;
}

function stringRecord(value: unknown, location: string): Readonly<Record<string, string>> {
  const source = objectValue(value, location);
  const result = Object.fromEntries(Object.entries(source).map(([key, child]) => [key, stringValue(child, location + ':' + key)]));
  if (Object.keys(result).length === 0) fail(location);
  return deepFreeze(result);
}

function nonEmptyStrings(value: unknown, location: string): readonly string[] {
  const values = stringArray(value, location);
  if (values.length === 0) fail(location);
  return values;
}

function uniqueStrings(value: unknown, location: string): readonly string[] {
  const values = stringArray(value, location);
  if (new Set(values).size !== values.length) fail(location + ':duplicate');
  return values;
}

function stringArray(value: unknown, location: string): readonly string[] {
  return deepFreeze(arrayValue(value, location).map((child, index) => stringValue(child, location + ':' + index)));
}

function arrayValue(value: unknown, location: string): readonly unknown[] {
  if (!Array.isArray(value)) fail(location);
  return value;
}

function objectValue(value: unknown, location: string): Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) fail(location);
  return value as Record<string, unknown>;
}

function stringValue(value: unknown, location: string): string {
  if (typeof value !== 'string' || value.trim().length === 0) fail(location);
  return value;
}

function numberValue(value: unknown, location: string): number {
  if (!Number.isSafeInteger(value)) fail(location);
  return Number(value);
}

function unique(values: readonly string[]): readonly string[] {
  return Object.freeze([...new Set(values)]);
}

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
  }
  return value;
}

function fail(location: string): never {
  throw new Error('ORDER_REQUIREMENT_SOURCE_INVALID:' + location);
}
