import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parse } from 'yaml';

interface ProviderRecord {
  readonly id: string;
  readonly package: string;
  readonly factory: string;
  readonly core: string;
}

interface ProviderDocument {
  readonly generated?: boolean;
  readonly source?: string;
  readonly providers?: readonly ProviderRecord[];
}

const root = resolve(import.meta.dirname, '../../..');
const document = parse(await readFile(resolve(root, 'config/providers.yml'), 'utf8')) as ProviderDocument;
if (document.generated !== true || document.source !== 'config/requirements.yml#providers') throw new Error('PROVIDER_CONFIG_AUTHORITY_INVALID');
const providers = document.providers ?? [];
if (providers.length !== 11) throw new Error('PROVIDER_CONFIG_COUNT_INVALID:' + providers.length);
if (new Set(providers.map(({ id }) => id)).size !== providers.length) throw new Error('PROVIDER_CONFIG_ID_DUPLICATE');

for (const provider of providers) {
  if (!/^[a-z][a-z0-9]*$/.test(provider.id) || provider.package !== '@shop/provider' + provider.id || provider.factory !== provider.id[0]!.toUpperCase() + provider.id.slice(1) + 'Provider') {
    throw new Error('PROVIDER_CONFIG_RECORD_INVALID:' + provider.id);
  }
  const manifest = JSON.parse(await readFile(resolve(root, 'extensions/channel', provider.id, 'package.json'), 'utf8')) as {
    readonly name?: string;
    readonly dependencies?: Readonly<Record<string, string>>;
  };
  if (manifest.name !== provider.package) throw new Error('PROVIDER_PACKAGE_ID_MISMATCH:' + provider.id);
  if (provider.core !== 'local' && manifest.dependencies?.['@shop/provider' + provider.core] !== '1.0.0') throw new Error('PROVIDER_CORE_DEPENDENCY_MISSING:' + provider.id);
}

const target = resolve(root, 'services/commerce/src/bootstrap/ProviderFactories.ts');
const content = [
  '// Generated by @shop/providergen from config/providers.yml. Do not edit.',
  "import type { ProviderFactory } from '@shop/providercore';",
  ...providers.map((provider) => `import { ${provider.factory} } from '${provider.package}';`),
  '',
  'const FACTORY_BY_ID: Readonly<Record<string, ProviderFactory>> = Object.freeze({',
  ...providers.map((provider) => `  ${provider.id}: ${provider.factory},`),
  '});',
  '',
  'export const PROVIDER_FACTORIES: readonly ProviderFactory[] = Object.freeze(Object.values(FACTORY_BY_ID));',
  '',
  'export function providerFactory(id: string): ProviderFactory {',
  '  const factory = FACTORY_BY_ID[id];',
  '  if (!factory) throw new Error(`PROVIDER_FACTORY_MISSING:${id}`);',
  '  return factory;',
  '}',
  '',
].join('\n');

if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== content) throw new Error('GENERATED_PROVIDER_REGISTRY_DRIFT:' + target);
} else {
  await writeFile(target, content, 'utf8');
}
