// Generated by @shop/providergen from config/providers.yml. Do not edit.
import type { ProviderFactory } from '@shop/providercore';
import { JdproductProvider } from '@shop/providerjdproduct';
import { JdfreshProvider } from '@shop/providerjdfresh';
import { TmallProvider } from '@shop/providertmall';
import { SupplierProvider } from '@shop/providersupplier';
import { CakeProvider } from '@shop/providercake';
import { FlowerProvider } from '@shop/providerflower';
import { BookProvider } from '@shop/providerbook';
import { ChargeProvider } from '@shop/providercharge';
import { FoodvoucherProvider } from '@shop/providerfoodvoucher';
import { MovieProvider } from '@shop/providermovie';
import { MealProvider } from '@shop/providermeal';

const FACTORY_BY_ID: Readonly<Record<string, ProviderFactory>> = Object.freeze({
  jdproduct: JdproductProvider,
  jdfresh: JdfreshProvider,
  tmall: TmallProvider,
  supplier: SupplierProvider,
  cake: CakeProvider,
  flower: FlowerProvider,
  book: BookProvider,
  charge: ChargeProvider,
  foodvoucher: FoodvoucherProvider,
  movie: MovieProvider,
  meal: MealProvider,
});

export const PROVIDER_FACTORIES: readonly ProviderFactory[] = Object.freeze(Object.values(FACTORY_BY_ID));

export function providerFactory(id: string): ProviderFactory {
  const factory = FACTORY_BY_ID[id];
  if (!factory) throw new Error(`PROVIDER_FACTORY_MISSING:${id}`);
  return factory;
}
