export const applicationPreviewPage = Object.freeze({
  items: Object.freeze([
    Object.freeze({
      id: 'application:hongtai-benefits',
      scope_id: 'mall:hongtai-benefits',
      code: 'HONGTAI_BENEFITS',
      public_slug: 'benefits',
      name: '鸿泰惠民通',
      status: 'active',
      version: 18,
      head_sequence: 12,
      head_validation_state: 'valid',
      published_sequence: 12,
      domain: 'benefits.hongtai.example',
      mall_id: 'mall:hongtai-benefits',
      pool_id: 'pool:hongtai-core',
      updated_at: '2026-08-27T05:16:00.000Z',
    }),
    Object.freeze({
      id: 'application:hongtai-select',
      scope_id: 'mall:hongtai-select',
      code: 'HONGTAI_SELECT',
      public_slug: 'select',
      name: '鸿泰甄选',
      status: 'draft',
      version: 9,
      head_sequence: 7,
      head_validation_state: 'invalid',
      published_sequence: 5,
      domain: 'select.hongtai.example',
      mall_id: 'mall:hongtai-select',
      pool_id: 'pool:hongtai-select',
      updated_at: '2026-08-27T04:48:00.000Z',
    }),
    Object.freeze({
      id: 'application:employee-care',
      scope_id: 'enterprise:hongtai',
      code: 'EMPLOYEE_CARE',
      public_slug: 'employee-care',
      name: '鸿泰员工关怀商城',
      status: 'draft',
      version: 3,
      head_sequence: 2,
      head_validation_state: 'pending',
      published_sequence: null,
      domain: null,
      mall_id: null,
      pool_id: null,
      updated_at: '2026-08-27T03:32:00.000Z',
    }),
  ]),
  count: 3,
});
