const commonLabels: Readonly<Record<string, string>> = Object.freeze({
  active: '生效中',
  inactive: '未启用',
  enabled: '已启用',
  disabled: '已停用',
  invited: '待激活',
  pending: '待处理',
  draft: '草稿',
  published: '已发布',
  unpublished: '未发布',
  archived: '已归档',
  paused: '已暂停',
  available: '正常',
  degraded: '部分异常',
  ready: '已就绪',
  notready: '未就绪',
  open: '待处理',
  opened: '已创建',
  created: '已创建',
  processing: '处理中',
  queued: '排队中',
  running: '执行中',
  completed: '已完成',
  closed: '已关闭',
  cancelled: '已取消',
  exhausted: '已用尽',
  revoked: '已撤销',
  expired: '已过期',
  approved: '已通过',
  rejected: '已拒绝',
  applied: '已申请',
  reviewing: '审核中',
  returning: '退回中',
  received: '已收到',
  refunding: '退款中',
  resolved: '已完成',
  unpaid: '待付款',
  authorizing: '支付确认中',
  paid: '已付款',
  partially_refunded: '部分退款',
  refunded: '已退款',
  failed: '失败',
  awaitingpayment: '待付款',
  fulfilling: '履约中',
  shipped: '已发货',
  delivered: '已送达',
  unallocated: '待分配',
  allocated: '已分配',
  returned: '已退回',
  frozen: '已冻结',
  platform: '平台',
  distributor: '分销商',
  tenant: '租户',
  enterprise: '企业',
  mall: '商城',
  department: '部门',
  store: '门店',
  supplier: '供应商',
  brand: '品牌',
  channel: '渠道',
  markup: '加价规则',
  console: '管理控制台',
  storefront: '员工商城',
  system: '系统角色',
  custom: '自定义角色',
  owner: '所有者角色',
  allow: '允许',
  deny: '拒绝',
  inapp: '站内消息',
  wechat: '微信',
  wecomcorp: '企业微信',
  wecomsuite: '企业微信服务商',
  oidc: '统一身份登录',
  email: '邮件',
  sms: '短信',
  internal: '内部账户',
  mixed: '组合支付',
  welfare: '福利账户',
  meal: '餐补账户',
  allowance: '津贴账户',
  debit: '借方',
  credit: '贷方',
  difference: '存在差异',
  internal_reference_missing: '内部引用缺失',
  amount_mismatch: '金额不一致',
  resolutionpending: '等待处理',
  reconciled: '已核对',
  settled: '已结算',
  issued: '已开具',
  issuing: '开具中',
  submitted: '已申请',
  red: '已红冲',
  none: '暂无',
  clean: '安全检查通过',
  urgent: '紧急',
  high: '高',
  normal: '普通',
  low: '低',
  general: '通用服务',
  availableagent: '可接单',
  busy: '忙碌',
  offline: '离线',
  physical: '实物商品',
  virtual: '虚拟商品',
  service: '服务商品',
  fixed: '固定结算',
  commission: '佣金结算',
  full: '全量同步',
  incremental: '增量同步',
  event: '事件同步',
  reconcile: '差异核对',
  held: '使用中',
  redeemed: '已核销',
  reversed: '已冲正',
  partially_reversed: '部分冲正',
  void: '已作废',
  verified: '已验证',
  notrequired: '无需验证',
  waiting: '等待用户',
  requested: '已申请',
  disqualified: '已取消资格',
  realtime: '实时',
  daily: '按日',
  weekly: '按周',
  monthly: '按月',
  quarterly: '按季度',
  yearly: '按年',
  'asia/shanghai': '中国标准时间',
  yesterday: '昨天',
  '7days': '近 7 天',
  '30days': '近 30 天',
  count: '数量',
  minor: '金额',
  ratio: '比例',
  'sales.amount': '销售额',
  'sales.orders': '订单数',
  application: '商城应用',
  category: '分类',
  provider: '服务商',
  product: '商品',
  message: '消息',
  assigned: '已分配',
  reopened: '已重新打开',
  updated: '已更新',
  'sla.escalated': '服务时限已升级',
  'self service': '自助服务',
});

export function chineseDomainLabel(value: string | null | undefined, fallback = '待识别'): string {
  if (value === null || value === undefined || value.trim() === '') return '—';
  const key = value.trim().toLowerCase();
  return commonLabels[key] ?? fallback;
}

export function chineseDomainList(values: readonly string[], fallback = '待识别'): string {
  return values.map((value) => chineseDomainLabel(value, fallback)).join('、');
}

export function chineseReference(kind: string, value: string | null | undefined): string {
  if (!value) return '—';
  return `${kind} ${referenceNumber(value)}`;
}

export function chineseSectionLabel(section: string): string {
  return `智慧翼 · ${section}`;
}

function referenceNumber(value: string): string {
  let hash = 2166136261;
  for (const character of value) {
    hash ^= character.codePointAt(0) ?? 0;
    hash = Math.imul(hash, 16777619);
  }
  return String(hash >>> 0)
    .padStart(10, '0')
    .slice(-8)
    .replace(/(\d{4})(\d{4})/, '$1 $2');
}
