-- Generated by @shop/contractgen from the canonical operation and event catalogs.
-- Do not edit the generated current-schema artifact directly.
begin;

insert into runtime.operation(id,owner,method,path,contract_version) values
{{OPERATIONS}};

insert into runtime.event(type,version,owner,schema_ref) values
{{EVENTS}};

alter table runtime.outbox add constraint outbox_event_contract_fk foreign key(event_type,event_version) references runtime.event(type,version);
alter table runtime.inbox add constraint inbox_event_contract_fk foreign key(event_type,event_version) references runtime.event(type,version);

insert into access.permission(id,code,risk,status) values
{{PERMISSIONS}}
on conflict(code) do nothing;

insert into access.role(id,scope_id,name,status,version,kind) values('role:self','self','Self Service','active',1,'system')
on conflict(id) do nothing;
insert into access.rolepermission(role_id,permission_id,effect)
select 'role:self',permission.id,'allow' from access.permission permission where permission.code in(
  'identity.session.read','identity.session.manage','identity.credential.manage','identity.mobile.manage','identity.assurance.manage',
  'identity.link.read','identity.link.manage','cart.read','cart.manage','checkout.create','order.create','order.read',
  'order.receive','order.reminder.create','order.aftersale.read','order.aftersale.apply','payment.read','verification.issue',
  'benefit.read','invoice.profile.read','invoice.request.create','finance.invoice.read','finance.invoice.download','member.address.read','member.address.manage',
  'member.favorite.read','member.favorite.manage','member.profile.read','support.case.create','support.case.read',
  'support.message.send','support.message.read','notification.read','notification.ack','notification.preference.read',
  'notification.preference.manage','notification.endpoint.manage','fulfillment.read','voucher.binding.read','voucher.redemption.read')
  or permission.code='observability.clienterror.create'
on conflict do nothing;
insert into access.membershiprole(membership_id,role_id,effective_at)
select membership.id,'role:self','1970-01-01T00:00:00Z' from access.membership membership on conflict do nothing;

insert into capability.capability(id,kind,name,version,status) values
{{CAPABILITIES}};

{{CAPABILITYDEPENDENCYINSERT}}

insert into capability.operation(operation_id,capability_id,permission_code,audience,targets) values
{{OPERATIONCAPABILITIES}};

insert into capability.entitlement(id,scope_id,capability_id,state,quota,effective_at,expires_at,version)
select 'platform:'||capability.id,'organization-platform-root',capability.id,'enabled',null,'1970-01-01T00:00:00Z',null,0
from capability.capability capability where capability.kind in('operation','feature','entitlement');

create or replace function identity.resolve_session(p_token_hash text)
returns table(actor_id text,session_id text,membership_id text,credential_version bigint,access_version bigint,target text,assurance_level smallint,assurance_verified_at timestamptz)
language sql stable security definer set search_path=identity,member,pg_temp as $function$
  select session.principal_id,session.id,session.membership_id,session.credential_version,session.access_version,
    case session.client when 'operator' then 'console' else session.client end,session.assurance_level,
    case when session.assurance_level>=3 then assurance.verified_at else null end
  from identity.session session join identity.principal principal on principal.id=session.principal_id
  join member.profile profile on profile.principal_id=session.principal_id
  join access.membership membership on membership.id=session.membership_id and membership.member_id=profile.id
  left join lateral (select evidence.verified_at from identity.assurance evidence
    where evidence.principal_id=session.principal_id and evidence.level>=session.assurance_level
      and (evidence.expires_at is null or evidence.expires_at>clock_timestamp())
    order by evidence.level desc,evidence.verified_at desc limit 1) assurance on true
  where session.token_hash=p_token_hash and session.revoked_at is null and session.expires_at>clock_timestamp()
    and session.credential_version=principal.credential_version and principal.status='active' and membership.status='active'
    and (session.assurance_level<3 or assurance.verified_at is not null)
$function$;

create or replace function experience.resolve_storefront_entry(p_handle text)
returns table(
  application text,handle text,mall text,pool text,release text,version text,tenant text,
  application_status text,validation_state text,publication_state text,content_hash text,configuration_hash text,object_key text
)
language sql stable security definer set search_path=experience,organization,pg_temp set row_security=off as $function$
  select application.id,application.public_slug,application.mall_id,release.pool_id,release.id,version.id,tenant.id,
    application.status,version.validation_state,publication.state,publication.content_hash,version.configuration_hash,publication.object_key
  from experience.application application
  join lateral(select ancestor.id from organization.unitclosure closure
    join organization.organization ancestor on ancestor.id=closure.ancestor_id and ancestor.kind='tenant'
    where closure.descendant_id=application.mall_id order by closure.depth limit 1) tenant on true
  left join lateral(select item.id,item.version_id,item.pool_id from experience.release item where item.application_id=application.id
    and item.state='active' and item.effective_at<=clock_timestamp()
    order by item.effective_at desc,item.id desc limit 1) release on true
  left join experience.version version on version.id=release.version_id
  left join experience.publication publication on publication.release_id=release.id
  where application.public_slug=p_handle
$function$;
revoke all on function experience.resolve_storefront_entry(text) from public,anon,authenticated,service_role;
grant execute on function experience.resolve_storefront_entry(text) to shopapp,shopjob;

create or replace function access.scope_object(p_scope_id text)
returns jsonb language plpgsql stable security definer set search_path=organization,partner,member,pg_temp as $function$
declare value jsonb;
begin
  select jsonb_strip_nulls(jsonb_build_object(
      'kind',scope.kind,'id',scope.id,
      'tenant',(select ancestor.id from organization.unitclosure closure join organization.organization ancestor on ancestor.id=closure.ancestor_id where closure.descendant_id=scope.id and ancestor.kind='tenant' limit 1),
      'path',coalesce((select jsonb_agg(jsonb_build_object('kind',ancestor.kind,'id',ancestor.id) order by closure.depth desc)
        from organization.unitclosure closure join organization.organization ancestor on ancestor.id=closure.ancestor_id
        where closure.descendant_id=scope.id and closure.depth>0),'[]'::jsonb))) into value
    from organization.organization scope where scope.id=p_scope_id;
  if value is not null then return value; end if;
  select jsonb_strip_nulls(jsonb_build_object('kind',subject.kind,'id',subject.id,'tenant',tenant.id,'path',
      coalesce((select jsonb_agg(jsonb_build_object('kind',ancestor.kind,'id',ancestor.id) order by closure.depth desc)
        from organization.unitclosure closure join organization.organization ancestor on ancestor.id=closure.ancestor_id
        where closure.descendant_id=subject.scope_id),'[]'::jsonb))) into value
    from partner.partner subject
    left join organization.unitclosure tenantclosure on tenantclosure.descendant_id=subject.scope_id
    left join organization.organization tenant on tenant.id=tenantclosure.ancestor_id and tenant.kind='tenant'
    where subject.id=p_scope_id order by tenantclosure.depth asc limit 1;
  if value is not null then return value; end if;
  select jsonb_build_object('kind','owner','id',profile.id,'path','[]'::jsonb) into value from member.profile profile where profile.id=p_scope_id;
  if value is not null then return value; end if;
  if p_scope_id like 'self:%' then return jsonb_build_object('kind','self','id',substr(p_scope_id,6),'path','[]'::jsonb); end if;
  return null;
end
$function$;

create or replace function access.effective_permissions(p_membership_id text)
returns table(permission_code text,effect text)
language sql stable security definer set search_path=access,pg_temp as $function$
  with candidates as (
    select permission.code,mapping.effect
    from access.membershiprole assignment
    join access.role role on role.id=assignment.role_id and role.status='active'
    join access.rolepermission mapping on mapping.role_id=role.id
    join access.permission permission on permission.id=mapping.permission_id and permission.status='active'
    where assignment.membership_id=p_membership_id and assignment.effective_at<=clock_timestamp()
      and (assignment.expires_at is null or assignment.expires_at>clock_timestamp())
    union all
    select permission.code,override.effect
    from access.membershipoverride override
    join access.permission permission on permission.id=override.permission_id and permission.status='active'
    where override.membership_id=p_membership_id and override.revoked_at is null
      and override.effective_at<=clock_timestamp()
      and (override.expires_at is null or override.expires_at>clock_timestamp())
  ), resolved as (
    select code,bool_or(effect='deny') denied,bool_or(effect='allow') allowed from candidates group by code
  )
  select code,case when denied then 'deny' else 'allow' end
  from resolved where denied or allowed order by code
$function$;

create or replace function access.effective_scopes(p_membership_id text)
returns table(scope jsonb,effect text,effective_at timestamptz,expires_at timestamptz)
language sql stable security definer set search_path=access,pg_temp as $function$
  select coalesce(access.scope_object(grantrow.scope_id),jsonb_build_object(
      'kind',grantrow.scope_kind,'id',grantrow.scope_id,'path','[]'::jsonb)),
    grantrow.effect,grantrow.effective_at,grantrow.expires_at
  from access.scopegrant grantrow
  where grantrow.membership_id=p_membership_id and grantrow.effective_at<=clock_timestamp()
    and (grantrow.expires_at is null or grantrow.expires_at>clock_timestamp())
  order by grantrow.effect desc,grantrow.scope_path,grantrow.scope_id
$function$;

create or replace function access.resource_scope(p_operation text,p_resource text,p_membership_id text)
returns text language plpgsql stable security definer
set search_path=access,capability,member,organization,partner,catalog,pricing,inventory,experience,cart,checkout,ordering,fulfillment,verification,payment,voucher,benefit,finance,invoice,channel,support,notification,reporting,risk,audit,extension,pg_temp as $function$
declare resolved text;
begin
  if p_operation='organization.stores.manage' then
    select coalesce((select id from partner.partner where id=p_resource and kind='store'),
      (select organization_id from access.membership where id=p_membership_id)) into resolved;
  elsif p_operation='identity.invitations.create' then
    select organization_id into resolved from access.membership where id=p_membership_id;
  elsif p_operation='identity.invitations.revoke' then
    select organization_id into resolved from identity.invitation where id=p_resource;
  elsif p_operation='identity.members.manage' then
    select organization_id into resolved from access.membership where id=p_resource;
  elsif p_operation like 'identity.%' then
    select 'self:'||profile.principal_id into resolved from access.membership membership join member.profile profile on profile.id=membership.member_id where membership.id=p_membership_id;
  elsif exists(select 1 from capability.operation where operation_id=p_operation and audience='storefront')
      or p_operation like 'cart.%' or p_operation like 'checkout.%' or p_operation in(
      'order.orders.create','order.aftersales.apply','benefit.accounts.read','invoice.profiles.manage',
      'invoice.requests.create','invoice.requests.read','invoice.requests.cancel',
      'notification.notifications.read','notification.preferences.manage','notification.endpoints.manage') then
    select profile.id into resolved from access.membership membership join member.profile profile on profile.id=membership.member_id where membership.id=p_membership_id;
  elsif p_operation in('order.orders.read','order.aftersales.read','support.cases.read','support.messages.read')
      and exists(select 1 from access.membership where id=p_membership_id and client='storefront') then
    select profile.id into resolved from access.membership membership join member.profile profile on profile.id=membership.member_id where membership.id=p_membership_id;
  elsif p_resource is null then select organization_id into resolved from access.membership where id=p_membership_id;
  else
    select id into resolved from organization.organization where id=p_resource;
    if resolved is null then select id into resolved from partner.partner where id=p_resource; end if;
    if resolved is null then select id into resolved from member.profile where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from catalog.pool where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from catalog.sourcelisting where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from catalog.listing where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from catalog.importjob where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from pricing.pricebook where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from pricing.rule where id=p_resource; end if;
    if resolved is null then select mall_id into resolved from pricing.quote where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from inventory.stockitem where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from experience.application where id=p_resource; end if;
    if resolved is null then select mall_id into resolved from cart.cart where id=p_resource; end if;
    if resolved is null then select mall_id into resolved from checkout.session where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from ordering.orderrecord where id=p_resource; end if;
    if resolved is null then select orders.mall_id into resolved from fulfillment.fulfillmentorder fulfillment join ordering.orderrecord orders on orders.id=fulfillment.order_id where fulfillment.id=p_resource; end if;
    if resolved is null then select orders.mall_id into resolved from fulfillment.returnrecord returned join fulfillment.fulfillmentorder fulfillment on fulfillment.id=returned.fulfillment_id join ordering.orderrecord orders on orders.id=fulfillment.order_id where returned.id=p_resource; end if;
    if resolved is null then select scope_id into resolved from verification.session where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from verification.device where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from payment.recoverycase where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.product where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.credentialpool where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.stockrequest where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.issuebatch where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.voucher where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.redemption where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from benefit.plan where id=p_resource; end if;
    if resolved is null then select plan.scope_id into resolved from benefit.budget budget join benefit.plan plan on plan.id=budget.plan_id where budget.id=p_resource; end if;
    if resolved is null then select plan.scope_id into resolved from benefit.grantbatch batch join benefit.plan plan on plan.id=batch.plan_id where batch.id=p_resource; end if;
    if resolved is null then select finance.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select scope_id into resolved from channel.connection where id=p_resource; end if;
    if resolved is null then select support.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select notification.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select reporting.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select risk.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select scope_id into resolved from extension.installation where id=p_resource; end if;
    if resolved is null and p_operation in('access.roles.manage','access.scopes.manage','capability.assignments.manage','partner.partners.manage','qualification.policies.manage','experience.applications.update','notification.templates.manage','notification.announcements.manage','reporting.exports.create','risk.policies.manage','verification.devices.manage','voucher.products.create','benefit.plans.manage','benefit.budgets.manage')
      then select organization_id into resolved from access.membership where id=p_membership_id; end if;
  end if;
  if resolved is null then raise exception 'RESOURCE_SCOPE_NOT_FOUND'; end if;
  return resolved;
end $function$;

create or replace function capability.membership_operations(p_membership_id text)
returns table(operation_id text) language sql stable security definer
set search_path=capability,access,organization,pg_temp as $function$
  with subject as (
    select membership.organization_id,case membership.client when 'operator' then 'console' else membership.client end target
    from access.membership membership where membership.id=p_membership_id and membership.status='active'
  ), permissions as materialized (
    select permission_code,effect from access.effective_permissions(p_membership_id)
  )
  select operation.operation_id from subject
  join capability.operation operation on operation.audience=subject.target
  where exists(select 1 from organization.unitclosure closure
      join capability.entitlement entitlement on entitlement.scope_id=closure.ancestor_id and entitlement.capability_id=operation.capability_id
      where closure.descendant_id=subject.organization_id and entitlement.state='enabled'
        and entitlement.effective_at<=clock_timestamp() and (entitlement.expires_at is null or entitlement.expires_at>clock_timestamp()))
    and (operation.permission_code is null or exists(
      select 1 from permissions permission where permission.permission_code=operation.permission_code and permission.effect='allow'))
  order by operation.operation_id
$function$;

create or replace function capability.membership_authorization(p_membership_id text)
returns table(operation_ids text[],capability_version bigint)
language sql stable security definer set search_path=capability,access,organization,pg_temp as $function$
  with membership_scope as (
    select membership.organization_id from access.membership membership
    where membership.id=p_membership_id and membership.status='active'
  ), current_version as (
    select coalesce(max(greatest(entitlement.version,capability.version)),0)::bigint value
    from membership_scope membership
    join organization.unitclosure closure on closure.descendant_id=membership.organization_id
    join capability.entitlement entitlement on entitlement.scope_id=closure.ancestor_id
      and entitlement.state='enabled' and entitlement.effective_at<=clock_timestamp()
      and (entitlement.expires_at is null or entitlement.expires_at>clock_timestamp())
    join capability.capability capability on capability.id=entitlement.capability_id
  )
  select coalesce(array_agg(available.operation_id order by available.operation_id)
    filter(where available.operation_id is not null),'{}'::text[]),current_version.value
  from current_version left join capability.membership_operations(p_membership_id) available on true
  group by current_version.value
$function$;

create or replace function access.authorization_snapshot(p_membership_id text,p_target text,p_operation text,p_resource text)
returns table(membership_id text,membership_active boolean,access_version bigint,
  credential_version bigint,organization_id text,target text,role_assignments jsonb,
  permission_allows text[],permission_denies text[],scopes jsonb,resource_scope jsonb,
  operation_ids text[],capability_version bigint)
language sql stable security definer set search_path=access,capability,pg_temp as $function$
  with subject as materialized (
    select membership.id,membership.status='active' and principal.status='active' active,membership.access_version,
      principal.credential_version,membership.organization_id,
      case membership.client when 'operator' then 'console' else membership.client end target
    from access.membership membership join identity.principal principal on principal.id=membership.principal_id
    where membership.id=p_membership_id
      and case membership.client when 'operator' then 'console' else membership.client end=p_target
  ), roles as (
    select coalesce(jsonb_agg(jsonb_build_object('id',role.id,'kind',role.kind,'status',role.status,'version',role.version,
      'effectiveAt',assignment.effective_at,'expiresAt',assignment.expires_at,
      'active',role.status='active' and assignment.effective_at<=clock_timestamp()
        and (assignment.expires_at is null or assignment.expires_at>clock_timestamp()))
      order by role.id,assignment.effective_at),'[]'::jsonb) value
    from access.membershiprole assignment join access.role role on role.id=assignment.role_id
    where assignment.membership_id=p_membership_id
  ), permissions as materialized (
    select permission_code,effect from access.effective_permissions(p_membership_id)
  ), permission_set as (
    select coalesce(array_agg(permission_code order by permission_code) filter(where effect='allow'),'{}'::text[]) allows,
      coalesce(array_agg(permission_code order by permission_code) filter(where effect='deny'),'{}'::text[]) denies
    from permissions
  ), scope_set as (
    select coalesce(jsonb_agg(jsonb_build_object('scope',scope,'effect',effect,'effective',effective_at,'expires',expires_at)
      order by effect,scope->>'kind',scope->>'id'),'[]'::jsonb) value from access.effective_scopes(p_membership_id)
  ), capability_set as (
    select available.operation_ids,available.capability_version
    from capability.membership_authorization(p_membership_id) available
  )
  select subject.id,subject.active,subject.access_version,subject.credential_version,subject.organization_id,subject.target,
    roles.value,permission_set.allows,permission_set.denies,
    scope_set.value,access.scope_object(access.resource_scope(p_operation,p_resource,p_membership_id)),
    capability_set.operation_ids,capability_set.capability_version
  from subject cross join roles cross join permission_set cross join scope_set cross join capability_set
$function$;

create or replace function runtime.accept_inbox(p_consumer text,p_event_id text,p_event_type text,p_event_version integer,p_trace_id text,p_payload jsonb)
returns boolean language plpgsql security definer set search_path=runtime,pg_temp as $function$
begin
  insert into runtime.inbox(consumer,event_id,event_type,event_version,trace_id,payload,received_at)
  values(p_consumer,p_event_id,p_event_type,p_event_version,p_trace_id,p_payload,clock_timestamp()) on conflict do nothing;
  return found;
end $function$;

create or replace function runtime.accept_provider_webhook(p_provider text,p_external_id text,p_sha256 text,p_headers jsonb,p_payload text,p_trace_id text,p_event_type text,p_event_version integer,p_event_payload jsonb)
returns text language plpgsql security definer set search_path=runtime,pg_temp as $function$
begin
  insert into runtime.rawenvelope(provider,external_id,sha256,headers,payload,trace_id,received_at)
  values(p_provider,p_external_id,p_sha256,p_headers,p_payload,p_trace_id,clock_timestamp()) on conflict(provider,external_id) do nothing;
  if not found then
    if not exists(select 1 from runtime.rawenvelope where provider=p_provider and external_id=p_external_id and sha256=p_sha256) then raise exception 'PROVIDER_EVENT_ID_COLLISION'; end if;
    return 'replayed';
  end if;
  perform runtime.accept_inbox('provider.'||p_provider,p_provider||':'||p_external_id,p_event_type,p_event_version,p_trace_id,p_event_payload);
  return 'accepted';
end $function$;

create or replace function extension.enabled_installations()
returns setof extension.installation language sql stable security definer set search_path=extension,pg_temp as $function$
  select installation.* from extension.installation installation where installation.status='enabled' order by installation.extension_id,installation.scope_id
$function$;

create or replace function extension.runnable_installations()
returns setof extension.installation language sql stable security definer set search_path=extension,pg_temp as $function$
  select installation.* from extension.installation installation where installation.status in('testing','enabled','degraded') order by installation.extension_id,installation.scope_id
$function$;

create or replace function channel.supplier_enabled(p_scope text)
returns boolean language sql stable security definer set search_path=channel,pg_temp as $function$
  select exists(select 1 from channel.connection where provider='supplier' and scope_id=p_scope and status='enabled')
$function$;

create or replace function channel.pull_supplier_catalog(p_scope text,p_cursor text)
returns jsonb language sql stable security definer set search_path=channel,catalog,pg_temp as $function$
  with batch as (select external_id,source_version,source_payload from catalog.sourcelisting
    where provider='supplier' and scope_id=p_scope and status<>'retired' and (p_cursor is null or external_id>p_cursor)
    order by external_id limit 500)
  select jsonb_build_object('records',coalesce(jsonb_agg(jsonb_build_object('externalId',external_id,'version',source_version,'payload',source_payload) order by external_id),'[]'::jsonb),
    'errors','[]'::jsonb,'complete',(select count(*)<500 from batch))||(case when count(*)=500 then jsonb_build_object('nextCursor',max(external_id)) else '{}'::jsonb end) from batch
$function$;

create or replace function channel.pull_supplier_stock(p_scope text,p_keys jsonb)
returns jsonb language sql stable security definer set search_path=channel,catalog,inventory,pg_temp as $function$
  select jsonb_build_object('records',coalesce(jsonb_agg(jsonb_build_object('externalId',listing.external_id,'onhand',stock.onhand,'safety',stock.safety,'version',stock.version,'status',stock.status)),'[]'::jsonb))
  from jsonb_array_elements(p_keys) key join catalog.sourcelisting listing on listing.provider='supplier' and listing.scope_id=p_scope and listing.external_id=key->>'externalId'
  join inventory.stockitem stock on stock.sku_id=listing.sku_id and stock.scope_id=p_scope
$function$;

create or replace function channel.submit_supplier_order(p_scope text,p_key text,p_reference text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=channel,pg_temp as $function$
declare operation channel.provideroperation%rowtype; request_digest text;
begin
  if not exists(select 1 from channel.connection where provider='supplier' and scope_id=p_scope and status='enabled') then raise exception 'SUPPLIER_PROVIDER_DISABLED'; end if;
  request_digest=encode(digest(p_reference||':'||p_payload::text,'sha256'),'hex');
  insert into channel.provideroperation(id,provider,scope_id,kind,idempotency_key,internal_reference,external_reference,state,request_hash,response,created_at,updated_at)
  values('supplier-order:'||md5(p_scope||':'||p_key),'supplier',p_scope,'order',p_key,p_reference,p_reference,'succeeded',request_digest,
    jsonb_build_object('externalReference',p_reference,'state','accepted','rawReference','local:'||p_reference),clock_timestamp(),clock_timestamp())
  on conflict(provider,kind,idempotency_key) do nothing;
  select * into strict operation from channel.provideroperation where provider='supplier' and kind='order' and idempotency_key=p_key;
  if operation.request_hash<>request_digest then raise exception 'IDEMPOTENCY_PAYLOAD_MISMATCH'; end if;
  return operation.response;
end $function$;

create or replace function channel.cancel_supplier_order(p_scope text,p_key text,p_reference text,p_reason text)
returns jsonb language plpgsql security definer set search_path=channel,pg_temp as $function$
declare response jsonb; request_digest text;
begin
  request_digest=encode(digest(p_reference||':'||p_reason,'sha256'),'hex'); response=jsonb_build_object('externalReference',p_reference,'state','cancelled');
  insert into channel.provideroperation(id,provider,scope_id,kind,idempotency_key,internal_reference,external_reference,state,request_hash,response,created_at,updated_at)
  values('supplier-cancel:'||md5(p_scope||':'||p_key),'supplier',p_scope,'cancel',p_key,p_reference,p_reference,'succeeded',request_digest,response,clock_timestamp(),clock_timestamp())
  on conflict(provider,kind,idempotency_key) do update set updated_at=channel.provideroperation.updated_at
  where channel.provideroperation.request_hash=excluded.request_hash;
  if not found then raise exception 'IDEMPOTENCY_PAYLOAD_MISMATCH'; end if; return response;
end $function$;

create or replace function channel.pull_supplier_tracking(p_scope text,p_reference text)
returns jsonb language sql stable security definer set search_path=channel,ordering,fulfillment,pg_temp as $function$
  select jsonb_build_object('externalReference',p_reference,'milestones',coalesce(jsonb_agg(jsonb_build_object('kind',milestone.kind,'state',milestone.state,'occurredAt',milestone.occurred_at) order by milestone.occurred_at) filter(where milestone.id is not null),'[]'::jsonb))
  from fulfillment.fulfillmentorder target left join fulfillment.milestone milestone on milestone.fulfillment_id=target.id
  where target.external_reference=p_reference and exists(select 1 from ordering.orderrecord source where source.id=target.order_id and source.scope_id=p_scope)
$function$;

create or replace function channel.submit_supplier_refund(p_scope text,p_key text,p_request jsonb)
returns jsonb language plpgsql security definer set search_path=channel,pg_temp as $function$
declare response jsonb; request_digest text; reference text;
begin
  reference=p_request->>'reference'; if reference is null then raise exception 'SUPPLIER_REFUND_REFERENCE_REQUIRED'; end if;
  request_digest=encode(digest(p_request::text,'sha256'),'hex'); response=jsonb_build_object('externalReference','refund:'||reference,'state','submitted');
  insert into channel.provideroperation(id,provider,scope_id,kind,idempotency_key,internal_reference,external_reference,state,request_hash,response,created_at,updated_at)
  values('supplier-refund:'||md5(p_scope||':'||p_key),'supplier',p_scope,'refund',p_key,reference,'refund:'||reference,'submitted',request_digest,response,clock_timestamp(),clock_timestamp())
  on conflict(provider,kind,idempotency_key) do update set updated_at=channel.provideroperation.updated_at where channel.provideroperation.request_hash=excluded.request_hash;
  if not found then raise exception 'IDEMPOTENCY_PAYLOAD_MISMATCH'; end if; return response;
end $function$;

create or replace function channel.build_supplier_statement(p_scope text,p_period jsonb)
returns jsonb language sql stable security definer set search_path=channel,pg_temp as $function$
  select jsonb_build_object('objectRef',statement.object_ref,'sha256',statement.sha256) from channel.statement statement
  where statement.provider='supplier' and statement.period_start=(p_period->>'start')::date and statement.period_end=(p_period->>'end')::date
$function$;

insert into runtime.schemaversion(version,checksum) values('20260821032000','{{CONTRACTCHECKSUM}}');

commit;
