-- Generated by @shop/contractgen from the canonical operation and event catalogs.
-- Do not edit the generated current-schema artifact directly.
begin;

insert into runtime.operation(id,owner,method,path,contract_version) values
{{OPERATIONS}};

insert into runtime.event(type,version,owner,schema_ref) values
{{EVENTS}};

alter table runtime.outbox add constraint outbox_event_contract_fk foreign key(event_type,event_version) references runtime.event(type,version);
alter table runtime.inbox add constraint inbox_event_contract_fk foreign key(event_type,event_version) references runtime.event(type,version);

insert into access.permission(id,code,risk,status) values
{{PERMISSIONS}}
on conflict(code) do nothing;

insert into access.role(id,scope_id,name,status,version) values('role:self','self','Self Service','active',1)
on conflict(id) do nothing;
insert into access.rolepermission(role_id,permission_id,effect)
select 'role:self',permission.id,'allow' from access.permission permission where permission.code in(
  'identity.session.read','identity.session.manage','identity.credential.manage','identity.mobile.manage','identity.assurance.manage',
  'cart.read','cart.manage','checkout.create','order.create','order.read','order.aftersale.read','order.aftersale.apply',
  'referral.self.read','referral.self.manage','referral.withdrawals.create',
  'payment.create','verification.issue','benefit.read','invoice.profile.manage','invoice.profile.read','invoice.request.create','invoice.request.read','invoice.request.cancel',
  'support.case.create','support.case.read','support.message.send','support.message.read','notification.read','notification.preference.manage','notification.endpoint.manage')
  or permission.code='observability.clienterror.create'
on conflict do nothing;
insert into access.membershiprole(membership_id,role_id,effective_at)
select membership.id,'role:self','1970-01-01T00:00:00Z' from access.membership membership on conflict do nothing;

insert into capability.capability(id,kind,name,version,status) values
{{CAPABILITIES}};

insert into capability.operation(operation_id,capability_id,permission_code,audience) values
{{OPERATIONCAPABILITIES}};

insert into capability.entitlement(id,scope_id,capability_id,state,quota,effective_at,expires_at,version)
select 'platform:'||capability.id,'organization-platform-root',capability.id,'enabled',null,'1970-01-01T00:00:00Z',null,0
from capability.capability capability where capability.kind='operation';

create or replace function identity.resolve_session(p_token_hash text)
returns table(actor_id text,session_id text,membership_id text,credential_version bigint,access_version bigint,target text,assurance_level smallint,assurance_verified_at timestamptz)
language sql stable security definer set search_path=identity,member,pg_temp as $function$
  select session.principal_id,session.id,session.membership_id,session.credential_version,session.access_version,
    case session.client when 'operator' then 'console' else session.client end,session.assurance_level,
    case when session.assurance_level>=3 then assurance.verified_at else null end
  from identity.session session join identity.principal principal on principal.id=session.principal_id
  join member.profile profile on profile.principal_id=session.principal_id
  join access.membership membership on membership.id=session.membership_id and membership.member_id=profile.id
  left join lateral (select evidence.verified_at from identity.assurance evidence
    where evidence.principal_id=session.principal_id and evidence.level>=session.assurance_level
      and (evidence.expires_at is null or evidence.expires_at>clock_timestamp())
    order by evidence.level desc,evidence.verified_at desc limit 1) assurance on true
  where session.token_hash=p_token_hash and session.revoked_at is null and session.expires_at>clock_timestamp()
    and session.credential_version=principal.credential_version and principal.status='active' and membership.status='active'
    and (session.assurance_level<3 or assurance.verified_at is not null)
$function$;

create or replace function access.scope_object(p_scope_id text)
returns jsonb language plpgsql stable security definer set search_path=organization,partner,member,pg_temp as $function$
declare value jsonb;
begin
  select jsonb_strip_nulls(jsonb_build_object(
      'kind',scope.kind,'id',scope.id,
      'tenant',(select ancestor.id from organization.unitclosure closure join organization.organization ancestor on ancestor.id=closure.ancestor_id where closure.descendant_id=scope.id and ancestor.kind='tenant' limit 1),
      'path',coalesce((select jsonb_agg(jsonb_build_object('kind',ancestor.kind,'id',ancestor.id) order by closure.depth desc)
        from organization.unitclosure closure join organization.organization ancestor on ancestor.id=closure.ancestor_id
        where closure.descendant_id=scope.id and closure.depth>0),'[]'::jsonb))) into value
    from organization.organization scope where scope.id=p_scope_id;
  if value is not null then return value; end if;
  select jsonb_strip_nulls(jsonb_build_object('kind',subject.kind,'id',subject.id,'tenant',tenant.id,'path',
      coalesce((select jsonb_agg(jsonb_build_object('kind',ancestor.kind,'id',ancestor.id) order by closure.depth desc)
        from organization.unitclosure closure join organization.organization ancestor on ancestor.id=closure.ancestor_id
        where closure.descendant_id=subject.scope_id),'[]'::jsonb))) into value
    from partner.partner subject
    left join organization.unitclosure tenantclosure on tenantclosure.descendant_id=subject.scope_id
    left join organization.organization tenant on tenant.id=tenantclosure.ancestor_id and tenant.kind='tenant'
    where subject.id=p_scope_id order by tenantclosure.depth asc limit 1;
  if value is not null then return value; end if;
  select jsonb_build_object('kind','owner','id',profile.id,'path','[]'::jsonb) into value from member.profile profile where profile.id=p_scope_id;
  if value is not null then return value; end if;
  if p_scope_id like 'self:%' then return jsonb_build_object('kind','self','id',substr(p_scope_id,6),'path','[]'::jsonb); end if;
  return null;
end
$function$;

create or replace function access.resolve_membership(p_membership_id text)
returns table(id text,active boolean,access_version bigint,denies text[],grants jsonb)
language sql stable security definer set search_path=access,member,organization,pg_temp as $function$
  select membership.id,membership.status='active',membership.access_version,
    coalesce((select array_agg(distinct permission.code order by permission.code)
      from access.membershiprole assignment join access.rolepermission mapping on mapping.role_id=assignment.role_id and mapping.effect='deny'
      join access.permission permission on permission.id=mapping.permission_id
      where assignment.membership_id=membership.id and assignment.effective_at<=clock_timestamp() and (assignment.expires_at is null or assignment.expires_at>clock_timestamp())),array[]::text[]),
    coalesce((select jsonb_agg(jsonb_build_object(
      'scope',access.scope_object(scopegrant.scope_id),
      'permissions',coalesce((select jsonb_agg(distinct permission.code order by permission.code)
        from access.membershiprole assignment join access.rolepermission mapping on mapping.role_id=assignment.role_id and mapping.effect='allow'
        join access.permission permission on permission.id=mapping.permission_id
        where assignment.membership_id=membership.id and assignment.effective_at<=clock_timestamp() and (assignment.expires_at is null or assignment.expires_at>clock_timestamp())), '[]'::jsonb),
      'effective',scopegrant.effective_at,'expires',scopegrant.expires_at) order by scopegrant.scope_path)
      from access.scopegrant scopegrant where scopegrant.membership_id=membership.id and scopegrant.effect='allow'
        and scopegrant.effective_at<=clock_timestamp() and (scopegrant.expires_at is null or scopegrant.expires_at>clock_timestamp())), '[]'::jsonb)
  from access.membership membership where membership.id=p_membership_id
$function$;

create or replace function access.membership_version(p_membership_id text)
returns bigint language sql stable security definer set search_path=member,pg_temp as $function$
  select access_version from access.membership where id=p_membership_id and status='active'
$function$;

create or replace function access.resource_scope(p_operation text,p_resource text,p_membership_id text)
returns text language plpgsql stable security definer
set search_path=access,capability,member,organization,partner,catalog,pricing,inventory,experience,cart,checkout,ordering,fulfillment,verification,payment,voucher,benefit,finance,invoice,channel,support,notification,reporting,risk,audit,extension,pg_temp as $function$
declare resolved text;
begin
  if p_operation='organization.stores.manage' then
    select coalesce((select id from partner.partner where id=p_resource and kind='store'),
      (select organization_id from access.membership where id=p_membership_id)) into resolved;
  elsif p_operation='identity.invitations.create' then
    select organization_id into resolved from access.membership where id=p_membership_id;
  elsif p_operation='identity.invitations.revoke' then
    select organization_id into resolved from member.invite where id=p_resource;
  elsif p_operation like 'identity.%' then
    select 'self:'||profile.principal_id into resolved from access.membership membership join member.profile profile on profile.id=membership.member_id where membership.id=p_membership_id;
  elsif exists(select 1 from capability.operation where operation_id=p_operation and audience='member')
      or p_operation like 'cart.%' or p_operation like 'checkout.%' or p_operation in(
      'order.orders.create','order.aftersales.apply','payment.intents.create','benefit.accounts.read','invoice.profiles.manage',
      'invoice.requests.create','invoice.requests.read','invoice.requests.cancel',
      'notification.notifications.read','notification.preferences.manage','notification.endpoints.manage') then
    select profile.id into resolved from access.membership membership join member.profile profile on profile.id=membership.member_id where membership.id=p_membership_id;
  elsif p_operation in('order.orders.read','order.aftersales.read','support.cases.read','support.messages.read')
      and exists(select 1 from access.membership where id=p_membership_id and client='storefront') then
    select profile.id into resolved from access.membership membership join member.profile profile on profile.id=membership.member_id where membership.id=p_membership_id;
  elsif p_resource is null then select organization_id into resolved from access.membership where id=p_membership_id;
  else
    select id into resolved from organization.organization where id=p_resource;
    if resolved is null then select id into resolved from partner.partner where id=p_resource; end if;
    if resolved is null then select id into resolved from member.profile where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from catalog.pool where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from catalog.sourcelisting where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from catalog.listing where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from catalog.importjob where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from pricing.pricebook where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from pricing.rule where id=p_resource; end if;
    if resolved is null then select mall_id into resolved from pricing.quote where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from inventory.stockitem where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from experience.application where id=p_resource; end if;
    if resolved is null then select mall_id into resolved from cart.cart where id=p_resource; end if;
    if resolved is null then select mall_id into resolved from checkout.session where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from ordering.orderrecord where id=p_resource; end if;
    if resolved is null then select orders.mall_id into resolved from fulfillment.fulfillmentorder fulfillment join ordering.orderrecord orders on orders.id=fulfillment.order_id where fulfillment.id=p_resource; end if;
    if resolved is null then select orders.mall_id into resolved from fulfillment.returnrecord returned join fulfillment.fulfillmentorder fulfillment on fulfillment.id=returned.fulfillment_id join ordering.orderrecord orders on orders.id=fulfillment.order_id where returned.id=p_resource; end if;
    if resolved is null then select scope_id into resolved from verification.session where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from verification.device where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from payment.recoverycase where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.program where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.cardpool where id=p_resource; end if;
    if resolved is null then select scope_id into resolved from voucher.reserverequest where id=p_resource; end if;
    if resolved is null then select program.scope_id into resolved from voucher.issuebatch batch join voucher.program program on program.id=batch.program_id where batch.id=p_resource; end if;
    if resolved is null then select program.scope_id into resolved from voucher.voucher voucher join voucher.program program on program.id=voucher.program_id where voucher.id=p_resource; end if;
    if resolved is null then select program.scope_id into resolved from voucher.redemption redemption join voucher.voucher voucher on voucher.id=redemption.voucher_id join voucher.program program on program.id=voucher.program_id where redemption.id=p_resource; end if;
    if resolved is null then select scope_id into resolved from benefit.plan where id=p_resource; end if;
    if resolved is null then select plan.scope_id into resolved from benefit.budget budget join benefit.plan plan on plan.id=budget.plan_id where budget.id=p_resource; end if;
    if resolved is null then select plan.scope_id into resolved from benefit.grantbatch batch join benefit.plan plan on plan.id=batch.plan_id where batch.id=p_resource; end if;
    if resolved is null then select finance.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select scope_id into resolved from channel.connection where id=p_resource; end if;
    if resolved is null then select support.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select notification.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select reporting.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select risk.resource_scope(p_resource) into resolved; end if;
    if resolved is null then select scope_id into resolved from extension.installation where id=p_resource; end if;
    if resolved is null and p_operation in('access.roles.manage','access.scopes.manage','capability.assignments.manage','partner.partners.manage','qualification.policies.manage','experience.applications.update','notification.templates.manage','notification.announcements.manage','reporting.exports.create','risk.policies.manage','verification.devices.manage','voucher.programs.manage','benefit.plans.manage','benefit.budgets.manage')
      then select organization_id into resolved from access.membership where id=p_membership_id; end if;
  end if;
  if resolved is null then raise exception 'RESOURCE_SCOPE_NOT_FOUND'; end if;
  return resolved;
end $function$;

create or replace function access.resolve_scope(p_membership_id text,p_operation text,p_resource text)
returns table(scope jsonb) language sql stable security definer set search_path=access,pg_temp as $function$
  select access.scope_object(access.resource_scope(p_operation,p_resource,p_membership_id))
$function$;

create or replace function capability.membership_operations(p_membership_id text)
returns table(operation_id text) language sql stable security definer
set search_path=capability,access,member,organization,runtime,pg_temp as $function$
  select operation.operation_id from capability.operation operation
  where operation.audience<>'public'
    and exists(select 1 from access.membership membership join organization.unitclosure closure on closure.descendant_id=membership.organization_id
      join capability.entitlement entitlement on entitlement.scope_id=closure.ancestor_id and entitlement.capability_id=operation.capability_id
      where membership.id=p_membership_id and membership.status='active' and entitlement.state='enabled'
        and entitlement.effective_at<=clock_timestamp() and (entitlement.expires_at is null or entitlement.expires_at>clock_timestamp()))
    and (operation.permission_code is null or exists(
      select 1 from access.membershiprole assignment join access.rolepermission mapping on mapping.role_id=assignment.role_id and mapping.effect='allow'
      join access.permission permission on permission.id=mapping.permission_id and permission.code=operation.permission_code
      where assignment.membership_id=p_membership_id and assignment.effective_at<=clock_timestamp() and (assignment.expires_at is null or assignment.expires_at>clock_timestamp())))
    and not exists(select 1 from access.membershiprole assignment join access.rolepermission mapping on mapping.role_id=assignment.role_id and mapping.effect='deny'
      join access.permission permission on permission.id=mapping.permission_id and permission.code=operation.permission_code where assignment.membership_id=p_membership_id)
$function$;

create or replace function runtime.accept_inbox(p_consumer text,p_event_id text,p_event_type text,p_event_version integer,p_trace_id text,p_payload jsonb)
returns boolean language plpgsql security definer set search_path=runtime,pg_temp as $function$
begin
  insert into runtime.inbox(consumer,event_id,event_type,event_version,trace_id,payload,received_at)
  values(p_consumer,p_event_id,p_event_type,p_event_version,p_trace_id,p_payload,clock_timestamp()) on conflict do nothing;
  return found;
end $function$;

create or replace function runtime.acquire_lease(p_resource text,p_owner text,p_seconds integer)
returns text language plpgsql security definer set search_path=runtime,pg_temp as $function$
declare lease_token text;
begin
  if p_seconds not between 5 and 900 then raise exception 'LEASE_DURATION_INVALID'; end if;
  lease_token=encode(gen_random_bytes(24),'hex');
  insert into runtime.lease(resource,owner,token,acquired_at,deadline,version)
  values(p_resource,p_owner,lease_token,clock_timestamp(),clock_timestamp()+make_interval(secs=>p_seconds),0)
  on conflict(resource) do update set owner=excluded.owner,token=excluded.token,acquired_at=excluded.acquired_at,deadline=excluded.deadline,version=runtime.lease.version+1
  where runtime.lease.deadline<=clock_timestamp();
  if not found then return null; end if;
  return lease_token;
end $function$;

create or replace function runtime.release_lease(p_resource text,p_owner text,p_token text)
returns boolean language sql security definer set search_path=runtime,pg_temp as $function$
  delete from runtime.lease where resource=p_resource and owner=p_owner and token=p_token returning true
$function$;

create or replace function runtime.accept_provider_webhook(p_provider text,p_external_id text,p_sha256 text,p_headers jsonb,p_payload text,p_trace_id text,p_event_type text,p_event_version integer,p_event_payload jsonb)
returns text language plpgsql security definer set search_path=runtime,pg_temp as $function$
begin
  insert into runtime.rawenvelope(provider,external_id,sha256,headers,payload,trace_id,received_at)
  values(p_provider,p_external_id,p_sha256,p_headers,p_payload,p_trace_id,clock_timestamp()) on conflict(provider,external_id) do nothing;
  if not found then
    if not exists(select 1 from runtime.rawenvelope where provider=p_provider and external_id=p_external_id and sha256=p_sha256) then raise exception 'PROVIDER_EVENT_ID_COLLISION'; end if;
    return 'replayed';
  end if;
  perform runtime.accept_inbox('provider.'||p_provider,p_provider||':'||p_external_id,p_event_type,p_event_version,p_trace_id,p_event_payload);
  return 'accepted';
end $function$;

create or replace function extension.enabled_installations()
returns setof extension.installation language sql stable security definer set search_path=extension,pg_temp as $function$
  select installation.* from extension.installation installation where installation.status='enabled' order by installation.extension_id,installation.scope_id
$function$;

create or replace function extension.runnable_installations()
returns setof extension.installation language sql stable security definer set search_path=extension,pg_temp as $function$
  select installation.* from extension.installation installation where installation.status in('testing','enabled','degraded') order by installation.extension_id,installation.scope_id
$function$;

create or replace function channel.private_enabled(p_scope text)
returns boolean language sql stable security definer set search_path=channel,pg_temp as $function$
  select exists(select 1 from channel.connection where provider='private' and scope_id=p_scope and status='enabled')
$function$;

create or replace function channel.pull_private_catalog(p_scope text,p_cursor text)
returns jsonb language sql stable security definer set search_path=channel,catalog,pg_temp as $function$
  with batch as (select external_id,source_version,source_payload from catalog.sourcelisting
    where provider='private' and scope_id=p_scope and status<>'retired' and (p_cursor is null or external_id>p_cursor)
    order by external_id limit 500)
  select jsonb_build_object('records',coalesce(jsonb_agg(jsonb_build_object('externalId',external_id,'version',source_version,'payload',source_payload) order by external_id),'[]'::jsonb),
    'errors','[]'::jsonb,'complete',(select count(*)<500 from batch))||(case when count(*)=500 then jsonb_build_object('nextCursor',max(external_id)) else '{}'::jsonb end) from batch
$function$;

create or replace function channel.pull_private_stock(p_scope text,p_keys jsonb)
returns jsonb language sql stable security definer set search_path=channel,catalog,inventory,pg_temp as $function$
  select jsonb_build_object('records',coalesce(jsonb_agg(jsonb_build_object('externalId',listing.external_id,'onhand',stock.onhand,'safety',stock.safety,'version',stock.version,'status',stock.status)),'[]'::jsonb))
  from jsonb_array_elements(p_keys) key join catalog.sourcelisting listing on listing.provider='private' and listing.scope_id=p_scope and listing.external_id=key->>'externalId'
  join inventory.stockitem stock on stock.sku_id=listing.sku_id and stock.scope_id=p_scope
$function$;

create or replace function channel.submit_private_order(p_scope text,p_key text,p_reference text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=channel,pg_temp as $function$
declare operation channel.provideroperation%rowtype; request_digest text;
begin
  if not exists(select 1 from channel.connection where provider='private' and scope_id=p_scope and status='enabled') then raise exception 'PRIVATE_PROVIDER_DISABLED'; end if;
  request_digest=encode(digest(p_reference||':'||p_payload::text,'sha256'),'hex');
  insert into channel.provideroperation(id,provider,scope_id,kind,idempotency_key,internal_reference,external_reference,state,request_hash,response,created_at,updated_at)
  values('private-order:'||md5(p_scope||':'||p_key),'private',p_scope,'order',p_key,p_reference,p_reference,'succeeded',request_digest,
    jsonb_build_object('externalReference',p_reference,'state','accepted','rawReference','local:'||p_reference),clock_timestamp(),clock_timestamp())
  on conflict(provider,kind,idempotency_key) do nothing;
  select * into strict operation from channel.provideroperation where provider='private' and kind='order' and idempotency_key=p_key;
  if operation.request_hash<>request_digest then raise exception 'IDEMPOTENCY_PAYLOAD_MISMATCH'; end if;
  return operation.response;
end $function$;

create or replace function channel.cancel_private_order(p_scope text,p_key text,p_reference text,p_reason text)
returns jsonb language plpgsql security definer set search_path=channel,pg_temp as $function$
declare response jsonb; request_digest text;
begin
  request_digest=encode(digest(p_reference||':'||p_reason,'sha256'),'hex'); response=jsonb_build_object('externalReference',p_reference,'state','cancelled');
  insert into channel.provideroperation(id,provider,scope_id,kind,idempotency_key,internal_reference,external_reference,state,request_hash,response,created_at,updated_at)
  values('private-cancel:'||md5(p_scope||':'||p_key),'private',p_scope,'cancel',p_key,p_reference,p_reference,'succeeded',request_digest,response,clock_timestamp(),clock_timestamp())
  on conflict(provider,kind,idempotency_key) do update set updated_at=channel.provideroperation.updated_at
  where channel.provideroperation.request_hash=excluded.request_hash;
  if not found then raise exception 'IDEMPOTENCY_PAYLOAD_MISMATCH'; end if; return response;
end $function$;

create or replace function channel.pull_private_tracking(p_scope text,p_reference text)
returns jsonb language sql stable security definer set search_path=channel,ordering,fulfillment,pg_temp as $function$
  select jsonb_build_object('externalReference',p_reference,'milestones',coalesce(jsonb_agg(jsonb_build_object('kind',milestone.kind,'state',milestone.state,'occurredAt',milestone.occurred_at) order by milestone.occurred_at) filter(where milestone.id is not null),'[]'::jsonb))
  from fulfillment.fulfillmentorder target left join fulfillment.milestone milestone on milestone.fulfillment_id=target.id
  where target.external_reference=p_reference and exists(select 1 from ordering.orderrecord source where source.id=target.order_id and source.scope_id=p_scope)
$function$;

create or replace function channel.submit_private_refund(p_scope text,p_key text,p_request jsonb)
returns jsonb language plpgsql security definer set search_path=channel,pg_temp as $function$
declare response jsonb; request_digest text; reference text;
begin
  reference=p_request->>'reference'; if reference is null then raise exception 'PRIVATE_REFUND_REFERENCE_REQUIRED'; end if;
  request_digest=encode(digest(p_request::text,'sha256'),'hex'); response=jsonb_build_object('externalReference','refund:'||reference,'state','submitted');
  insert into channel.provideroperation(id,provider,scope_id,kind,idempotency_key,internal_reference,external_reference,state,request_hash,response,created_at,updated_at)
  values('private-refund:'||md5(p_scope||':'||p_key),'private',p_scope,'refund',p_key,reference,'refund:'||reference,'submitted',request_digest,response,clock_timestamp(),clock_timestamp())
  on conflict(provider,kind,idempotency_key) do update set updated_at=channel.provideroperation.updated_at where channel.provideroperation.request_hash=excluded.request_hash;
  if not found then raise exception 'IDEMPOTENCY_PAYLOAD_MISMATCH'; end if; return response;
end $function$;

create or replace function channel.build_private_statement(p_scope text,p_period jsonb)
returns jsonb language sql stable security definer set search_path=channel,pg_temp as $function$
  select jsonb_build_object('objectRef',statement.object_ref,'sha256',statement.sha256) from channel.statement statement
  where statement.provider='private' and statement.period_start=(p_period->>'start')::date and statement.period_end=(p_period->>'end')::date
$function$;

insert into runtime.schemaversion(version,checksum) values('20260821032000','{{CONTRACTCHECKSUM}}');

commit;
