server {
    listen 80;
    server_name fufu.wang accounts.fufu.wang console.fufu.wang api.fufu.wang;

    location ^~ /.well-known/acme-challenge/ {
        root /www/wwwroot/fufu-acme;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
