import { defineModuleManifest } from '@shop/kernel';
import { IDENTITY_CAPABILITIES } from './01_public_gongkai/IdentityCapabilities';

export const identityManifest = defineModuleManifest({
  id: 'identity',
  version: '1.0.0',
  kind: 'business',
  provides: [IDENTITY_CAPABILITIES.read, IDENTITY_CAPABILITIES.manage],
  requires: ['access.manage', 'member.manage', 'organization.manage'],
  operations: [
    'identity.sessions.create',
    'identity.tickets.exchange',
    'identity.session.read',
    'identity.session.delete',
    'identity.sessions.read',
    'identity.sessions.revoke',
    'identity.challenges.create',
    'identity.invitations.read',
    'identity.storefronts.read',
    'identity.invitations.create',
    'identity.invitations.revoke',
    'identity.members.create',
    'identity.members.manage',
    'identity.members.reset',
    'identity.password.change',
    'identity.password.verify',
    'identity.password.reset',
    'identity.mobile.challenge',
    'identity.mobile.manage',
    'identity.stepup.start',
    'identity.stepup.complete',
    'identity.wechat.session',
    'identity.wechat.bind',
  ],
  publishes: [
    'identity.session.created',
    'identity.session.revoked',
    'identity.challenge.started',
    'identity.member.registered',
    'identity.member.reset',
  ],
  consumes: [],
  publicEntry: './index.ts',
  layers: ['public', 'domain', 'application', 'adapters', 'interface', 'tests'],
  entrypoints: {
    http: ['fullIdentityOperations', 'registrationWechatIdentityOperations'],
    jobs: [],
  },
});
