/* GENERATED by 04_tools/scripts/build-web-tokens.mjs — do not edit by hand. */
/* Source of truth: 01_core_hexin/packages/design/src/tokens.json v1.2.0 */

export const token = Object.freeze({
  version: '1.2.0',
  color: Object.freeze({
    brand: '#1F5EFF',
    danger: '#B91C1C',
    warning: '#92400E',
    success: '#087A55',
    text: '#172033',
    muted: '#64748B',
    surface: '#FFFFFF',
    canvas: '#F5F7FA',
  }),
  radius: Object.freeze({ small: '8px', medium: '12px', large: '16px' }),
  space: Object.freeze({ small: '8px', medium: '16px', large: '24px' }),
});

export type Token = typeof token;
