export type ProductItemType = 'physical' | 'virtual_coupon' | 'movie_ticket' | 'supermarket' | 'life_service' | 'nearby_store' | 'unknown';
export type ProductView = Readonly<{
  id: string;
  skuId: string;
  title: string;
  subtitle: string;
  images: readonly string[];
  priceMarketMinor: number;
  priceMallMinor: number;
  priceWelfareMinor: number;
  currency: string;
  categoryId: string;
  categoryName: string;
  brand: string;
  tags: readonly string[];
  supplierId: string;
  supplierName: string;
  itemType: ProductItemType;
  allowedAccounts: readonly ('welfare' | 'meal' | 'wechat' | 'cash')[];
  stock: number;
  salesCount: number;
  rating: number;
  reviewCount: number;
  deliverySla: string;
  purchasable: boolean;
  version: string;
  updatedAt: string;
  skus: readonly Readonly<{ id: string; productId: string; priceMinor: number; compareMinor: number | null; currency: string; available: number; state: 'available' | 'unavailable'; priceVersion: string; inventoryVersion: string }>[];
  isEnterpriseExclusive?: boolean;
  isDailySpecial?: boolean;
  isHotRedeem?: boolean;
  isNewArrival?: boolean;
  qualificationReason?: string;
  specs?: readonly Readonly<{ name: string; options: readonly string[] }>[];
  params?: readonly Readonly<{ key: string; value: string }>[];
  descriptionHtml?: string;
  descriptionDetailText?: readonly string[];
  nearbyStoreInfo?: Readonly<{ storeName: string; address: string; distance: string; businessHours: string; phone: string }>;
}>;
export type PresentedProduct = ProductView &
  Readonly<{
    imageUrl: string;
    image: string;
    gallery: readonly string[];
    price: number;
    originalPrice: number;
    enterpriseSubsidyAmount: number;
    stockCount: number;
    description: string;
    parameters: Readonly<Record<string, string>>;
    specOptions: Readonly<Record<string, readonly string[]>>;
    allowMealCard: boolean;
    isEnterpriseSubsidized: boolean;
    welfarePrice: number;
    marketPrice: number;
    salesVolume: number;
    applicableStoreName: string;
    category: string;
  }>;
export type CategoryView = Readonly<{ id: string; name: string; iconName: string; hotKeywords: readonly string[]; icon: string; description: string; subCategories: readonly object[] }>;
export type ProfileView = Readonly<{
  id: string;
  employeeId: string;
  name: string;
  avatar: string;
  phone: string;
  jobTitle: string;
  department: string;
  enterpriseId: string;
  enterpriseName: string;
  currentMallId: string;
  welfareBalanceMinor: number;
  mealBalanceMinor: number;
  couponCount: number;
  assuranceLevel: 'account' | 'phone';
  phoneVerified: boolean;
  paymentEligible: boolean;
  accessVersion: number;
}>;
export type MallView = Readonly<{ id: string; membershipId?: string; enterpriseId: string; enterpriseName: string; mallName: string; logoText: string; badge: string; welcomeBanner: string }>;
export type AddressView = Readonly<{ id: string; recipient: string; mobile: string; province: string; city: string; district: string; detail: string; isDefault: boolean; tag?: string; version: number; status: 'active' | 'deleted' }>;
export type AddressDraft = Readonly<{ recipient: string; mobile: string; province: string; city: string; district: string; detail: string }>;
export type CartLineView = Readonly<{ id: string; listingId: string; skuId: string; lineVersion: number; product: ProductView; quantity: number; selectedSpec: Readonly<Record<string, string>>; selected: boolean }>;
export type OrderLineView = Readonly<{
  id: string;
  productId: string;
  listingId: string;
  skuId: string;
  title: string;
  image: string;
  unitMinor: number;
  totalMinor: number;
  discountMinor: number;
  payableMinor: number;
  quantity: number;
  categoryId: string;
  itemType: ProductItemType;
  provider: string | null;
  partner: string | null;
}>;
export type TimelineView = Readonly<{ id: string; kind: string; state: string; tracking: string | null; occurredAt: string; evidence: Readonly<Record<string, unknown>> }>;
export type OrderView = Readonly<{
  id: string;
  orderNo: string;
  createdAt: string;
  updatedAt: string;
  totalMinor: number;
  status: string;
  version: number;
  lifecycleState: string;
  fulfillmentState: string;
  lines: readonly OrderLineView[];
  timeline: readonly TimelineView[];
}>;
export type HomeView = Readonly<{ release: string; version: string; hash: string; effectiveAt: string; sections: readonly object[] }>;
export type NavigationView = Readonly<{ id: string; title: string; icon: string; route: string; component: string; order: number; disabled: boolean; children: readonly NavigationView[] }>;
