begin;

create table runtime.reconciliationevidence(
  id text primary key,
  source_count bigint not null,
  target_count bigint not null,
  source_amount bigint,
  target_amount bigint,
  difference bigint not null,
  checked_at timestamptz not null
);
create table runtime.reconciliationhash(
  id text primary key,
  source_hash char(64) not null,
  target_hash char(64) not null,
  checked_at timestamptz not null
);

insert into runtime.reconciliationevidence values
('organization',(select count(*) from public.tenants)+(select count(*) from public.enterprises)+(select count(*) from public.malls)+(select count(*) from public.departments)+(select count(*) from public.distributors)+1,(select count(*) from organization.organization),null,null,
 (select count(*) from organization.organization)-((select count(*) from public.tenants)+(select count(*) from public.enterprises)+(select count(*) from public.malls)+(select count(*) from public.departments)+(select count(*) from public.distributors)+1),clock_timestamp()),
('member',(select count(*) from public.members source where not exists(select 1 from public.member_login_aliases alias where alias.member_id=source.id and alias.provider='test')),
 (select count(*) from member.profile),null,null,(select count(*) from member.profile)-(select count(*) from public.members source where not exists(select 1 from public.member_login_aliases alias where alias.member_id=source.id and alias.provider='test')),clock_timestamp()),
('membership',(select count(*) from public.memberships source where exists(select 1 from member.profile profile where profile.id=source.member_id)),
 (select count(*) from member.membership),null,null,(select count(*) from member.membership)-(select count(*) from public.memberships source where exists(select 1 from member.profile profile where profile.id=source.member_id)),clock_timestamp()),
('product',(select count(*) from public.products where is_test=false),(select count(*) from catalog.product),null,null,(select count(*) from catalog.product)-(select count(*) from public.products where is_test=false),clock_timestamp()),
('sku',(select count(*) from public.skus source join public.products product on product.id=source.product_id where product.is_test=false),(select count(*) from catalog.sku),null,null,(select count(*) from catalog.sku)-(select count(*) from public.skus source join public.products product on product.id=source.product_id where product.is_test=false),clock_timestamp()),
('inventory',(select count(*) from inventory.stock_items source join public.products product on product.id=(select sku.product_id from public.skus sku where sku.id=source.sku_id) where product.is_test=false),(select count(*) from inventory.stockitem),(select coalesce(sum(source.onhand),0) from inventory.stock_items source join public.skus sku on sku.id=source.sku_id join public.products product on product.id=sku.product_id where product.is_test=false),(select coalesce(sum(onhand),0) from inventory.stockitem),(select coalesce(sum(onhand),0) from inventory.stockitem)-(select coalesce(sum(source.onhand),0) from inventory.stock_items source join public.skus sku on sku.id=source.sku_id join public.products product on product.id=sku.product_id where product.is_test=false),clock_timestamp()),
('order',(select count(*) from public.orders),(select count(*) from ordering.orderrecord),(select coalesce(sum(payable_cents),0) from public.orders),(select coalesce(sum(total_minor),0) from ordering.orderrecord),(select coalesce(sum(total_minor),0) from ordering.orderrecord)-(select coalesce(sum(payable_cents),0) from public.orders),clock_timestamp()),
('payment',(select count(*) from public.payments where status in('succeeded','refunded','closed')),(select count(*) from payment.payment),(select coalesce(sum(amount_cents),0) from public.payments where status in('succeeded','refunded','closed')),(select coalesce(sum(amount_minor),0) from payment.payment),(select coalesce(sum(amount_minor),0) from payment.payment)-(select coalesce(sum(amount_cents),0) from public.payments where status in('succeeded','refunded','closed')),clock_timestamp()),
('benefit',(select count(*) from public.welfare_accounts),(select count(*) from benefit.account),(select coalesce(sum(balance_cents),0) from public.welfare_accounts),(select coalesce(sum(amount_minor),0) from benefit.entry),(select coalesce(sum(amount_minor),0) from benefit.entry)-(select coalesce(sum(balance_cents),0) from public.welfare_accounts),clock_timestamp()),
('voucher',(select count(*) from public.vouchers),(select count(*) from voucher.voucher),(select coalesce(sum(remaining_cents),0) from public.vouchers),(select coalesce(sum(remaining_minor),0) from voucher.voucher),(select coalesce(sum(remaining_minor),0) from voucher.voucher)-(select coalesce(sum(remaining_cents),0) from public.vouchers),clock_timestamp()),
('financejournal',(select count(*) from public.finance_journals)+(select count(*) from public.account_ledgers),(select count(*) from finance.journal),null,null,(select count(*) from finance.journal)-((select count(*) from public.finance_journals)+(select count(*) from public.account_ledgers)),clock_timestamp()),
('financeentry',(select count(*) from public.finance_journal_entries)+2*(select count(*) from public.account_ledgers),(select count(*) from finance.entry),(select coalesce(sum(amount_cents),0) from public.finance_journal_entries)+2*(select coalesce(sum(amount_cents),0) from public.account_ledgers),(select coalesce(sum(amount_minor),0) from finance.entry),(select coalesce(sum(amount_minor),0) from finance.entry)-((select coalesce(sum(amount_cents),0) from public.finance_journal_entries)+2*(select coalesce(sum(amount_cents),0) from public.account_ledgers)),clock_timestamp()),
('audit',(select count(*) from public.audit_logs),(select count(*) from audit.record),null,null,(select count(*) from audit.record)-(select count(*) from public.audit_logs),clock_timestamp());

insert into runtime.reconciliationevidence(id,source_count,target_count,source_amount,target_amount,difference,checked_at) values
('identity.credential.password',(select count(*) from public.member_credentials source where exists(select 1 from identity.principal target where target.id=source.member_id)),(select count(*) from identity.credential where provider='password'),null,null,(select count(*) from identity.credential where provider='password')-(select count(*) from public.member_credentials source where exists(select 1 from identity.principal target where target.id=source.member_id)),clock_timestamp()),
('identity.credential.alias',(select count(*) from public.member_login_aliases source where source.provider<>'test' and exists(select 1 from identity.principal target where target.id=source.member_id)),(select count(*) from identity.credential where provider like 'alias.%'),null,null,(select count(*) from identity.credential where provider like 'alias.%')-(select count(*) from public.member_login_aliases source where source.provider<>'test' and exists(select 1 from identity.principal target where target.id=source.member_id)),clock_timestamp()),
('identity.federated',(select count(*) from public.member_wechat_identities source where source.member_id is null or exists(select 1 from identity.principal target where target.id=source.member_id)),(select count(*) from identity.federatedidentity),null,null,(select count(*) from identity.federatedidentity)-(select count(*) from public.member_wechat_identities source where source.member_id is null or exists(select 1 from identity.principal target where target.id=source.member_id)),clock_timestamp()),
('identity.session',(select count(*) from public.auth_sessions source where exists(select 1 from member.membership target where target.id=source.membership_id)),(select count(*) from identity.session),null,null,(select count(*) from identity.session)-(select count(*) from public.auth_sessions source where exists(select 1 from member.membership target where target.id=source.membership_id)),clock_timestamp()),
('identity.challenge',(select count(*) from public.phone_verification_challenges)+(select count(*) from public.wechat_binding_challenges)+(select count(*) from public.admin_step_up_challenges source where exists(select 1 from member.membership target where target.id=source.membership_id)),(select count(*) from identity.challenge),null,null,(select count(*) from identity.challenge)-((select count(*) from public.phone_verification_challenges)+(select count(*) from public.wechat_binding_challenges)+(select count(*) from public.admin_step_up_challenges source where exists(select 1 from member.membership target where target.id=source.membership_id))),clock_timestamp()),
('access.override',(select count(*) from public.membership_permission_overrides source where exists(select 1 from member.membership target where target.id=source.membership_id)),(select count(*) from access.membershipoverride),null,null,(select count(*) from access.membershipoverride)-(select count(*) from public.membership_permission_overrides source where exists(select 1 from member.membership target where target.id=source.membership_id)),clock_timestamp()),
('member.invite',(select count(*) from public.membership_registration_invites),(select count(*) from member.invite),null,null,(select count(*) from member.invite)-(select count(*) from public.membership_registration_invites),clock_timestamp()),
('member.import',(select count(*) from public.membership_import_jobs),(select count(*) from member.importjob),null,null,(select count(*) from member.importjob)-(select count(*) from public.membership_import_jobs),clock_timestamp()),
('partner.partner',(select count(*) from public.suppliers)+(select count(*) from public.brands)+(select count(*) from public.stores),(select count(*) from partner.partner),null,null,(select count(*) from partner.partner)-((select count(*) from public.suppliers)+(select count(*) from public.brands)+(select count(*) from public.stores)),clock_timestamp()),
('partner.relationship',(select count(*) from public.supplier_brand_bindings)+(select count(*) from public.brand_store_bindings),(select count(*) from partner.relationship),null,null,(select count(*) from partner.relationship)-((select count(*) from public.supplier_brand_bindings)+(select count(*) from public.brand_store_bindings)),clock_timestamp()),
('partner.agreement',(select count(*) from public.mall_supplier_agreements)+(select count(*) from public.mall_brand_authorizations),(select count(*) from partner.agreement),null,null,(select count(*) from partner.agreement)-((select count(*) from public.mall_supplier_agreements)+(select count(*) from public.mall_brand_authorizations)),clock_timestamp()),
('catalog.pool',(select count(*) from public.catalog_pools),(select count(*) from catalog.pool),null,null,(select count(*) from catalog.pool)-(select count(*) from public.catalog_pools),clock_timestamp()),
('catalog.poolitem',(select count(*) from public.catalog_pool_items source where exists(select 1 from catalog.sku target where target.id=source.sku_id)),(select count(*) from catalog.poolitem),null,null,(select count(*) from catalog.poolitem)-(select count(*) from public.catalog_pool_items source where exists(select 1 from catalog.sku target where target.id=source.sku_id)),clock_timestamp()),
('catalog.poolbinding',(select count(*) from public.mall_catalog_pool_bindings),(select count(*) from catalog.poolbinding),null,null,(select count(*) from catalog.poolbinding)-(select count(*) from public.mall_catalog_pool_bindings),clock_timestamp()),
('catalog.governance',(select count(*) from public.catalog_supplier_category_mappings)+(select count(*) from public.catalog_classification_rules)+(select count(*) from public.catalog_review_queue source join public.products product on product.id=source.product_id where product.is_test=false),(select count(*) from catalog.suppliercategory)+(select count(*) from catalog.classificationrule)+(select count(*) from catalog.review),null,null,((select count(*) from catalog.suppliercategory)+(select count(*) from catalog.classificationrule)+(select count(*) from catalog.review))-((select count(*) from public.catalog_supplier_category_mappings)+(select count(*) from public.catalog_classification_rules)+(select count(*) from public.catalog_review_queue source join public.products product on product.id=source.product_id where product.is_test=false)),clock_timestamp()),
('catalog.availability',(select count(*) from public.city_zones)+(select count(*) from public.city_zone_cities)+(select count(*) from public.city_zone_catalog_items source where (source.product_id is not null and exists(select 1 from catalog.product target where target.id=source.product_id)) or (source.sku_id is not null and exists(select 1 from catalog.sku target where target.id=source.sku_id))),(select count(*) from catalog.availabilityzone)+(select count(*) from catalog.availabilitycity)+(select count(*) from catalog.availabilityitem),null,null,((select count(*) from catalog.availabilityzone)+(select count(*) from catalog.availabilitycity)+(select count(*) from catalog.availabilityitem))-((select count(*) from public.city_zones)+(select count(*) from public.city_zone_cities)+(select count(*) from public.city_zone_catalog_items source where (source.product_id is not null and exists(select 1 from catalog.product target where target.id=source.product_id)) or (source.sku_id is not null and exists(select 1 from catalog.sku target where target.id=source.sku_id)))),clock_timestamp()),
('qualification.profile',(select count(*) from public.employee_qualification_profiles source join public.members legacy on legacy.user_id=source.user_id where exists(select 1 from member.profile target where target.id=legacy.id)),(select count(*) from qualification.profile),null,null,(select count(*) from qualification.profile)-(select count(*) from public.employee_qualification_profiles source join public.members legacy on legacy.user_id=source.user_id where exists(select 1 from member.profile target where target.id=legacy.id)),clock_timestamp()),
('qualification.policy',(select count(*) from public.entitlement_policies)+(select count(*) from public.purchase_limit_templates),(select count(*) from qualification.policy),null,null,(select count(*) from qualification.policy)-((select count(*) from public.entitlement_policies)+(select count(*) from public.purchase_limit_templates)),clock_timestamp()),
('qualification.change',(select count(*) from public.qualification_change_requests),(select count(*) from qualification.changerequest),null,null,(select count(*) from qualification.changerequest)-(select count(*) from public.qualification_change_requests),clock_timestamp()),
('inventory.command',(select count(*) from inventory.commands),(select count(*) from inventory.command),null,null,(select count(*) from inventory.command)-(select count(*) from inventory.commands),clock_timestamp()),
('inventory.observation',(select count(*) from inventory.observations source where exists(select 1 from inventory.stockitem target where target.id=source.stock_item_id)),(select count(*) from inventory.observation),null,null,(select count(*) from inventory.observation)-(select count(*) from inventory.observations source where exists(select 1 from inventory.stockitem target where target.id=source.stock_item_id)),clock_timestamp()),
('inventory.sync',(select count(*) from inventory.sync_states),(select count(*) from inventory.syncstate),null,null,(select count(*) from inventory.syncstate)-(select count(*) from inventory.sync_states),clock_timestamp()),
('inventory.cutover',(select count(*) from inventory.cutover_records source where exists(select 1 from inventory.stockitem target where target.id=source.stock_item_id))+(select count(*) from inventory.cutover_reviews source where exists(select 1 from inventory.stockitem target where target.id=source.stock_item_id)),(select count(*) from inventory.cutoverreview),null,null,(select count(*) from inventory.cutoverreview)-((select count(*) from inventory.cutover_records source where exists(select 1 from inventory.stockitem target where target.id=source.stock_item_id))+(select count(*) from inventory.cutover_reviews source where exists(select 1 from inventory.stockitem target where target.id=source.stock_item_id))),clock_timestamp()),
('checkout.address',(select count(*) from public.delivery_addresses source join public.members legacy on legacy.user_id=source.user_id where exists(select 1 from member.profile target where target.id=legacy.id)),(select count(*) from checkout.address),null,null,(select count(*) from checkout.address)-(select count(*) from public.delivery_addresses source join public.members legacy on legacy.user_id=source.user_id where exists(select 1 from member.profile target where target.id=legacy.id)),clock_timestamp()),
('ordering.aftersale',(select count(*) from public.after_sales),(select count(*) from ordering.aftersale),null,null,(select count(*) from ordering.aftersale)-(select count(*) from public.after_sales),clock_timestamp()),
('ordering.review',(select count(*) from public.after_sale_review_actions),(select count(*) from ordering.reviewaction),null,null,(select count(*) from ordering.reviewaction)-(select count(*) from public.after_sale_review_actions),clock_timestamp()),
('verification.session',(select count(*) from public.member_code_challenges source where exists(select 1 from member.profile target where target.id=source.member_id))+(select count(*) from public.voucher_redemptions),(select count(*) from verification.session),null,null,(select count(*) from verification.session)-((select count(*) from public.member_code_challenges source where exists(select 1 from member.profile target where target.id=source.member_id))+(select count(*) from public.voucher_redemptions)),clock_timestamp()),
('fulfillment.order',(select count(*) from public.fulfillment_orders),(select count(*) from fulfillment.fulfillmentorder),null,null,(select count(*) from fulfillment.fulfillmentorder)-(select count(*) from public.fulfillment_orders),clock_timestamp()),
('fulfillment.line',(select count(*) from public.fulfillment_order_items),(select count(*) from fulfillment.line),null,null,(select count(*) from fulfillment.line)-(select count(*) from public.fulfillment_order_items),clock_timestamp()),
('payment.attempt',(select count(*) from public.payments source where not exists(select 1 from public.wechat_payment_attempts attempt where attempt.payment_id=source.id))+(select count(*) from public.wechat_payment_attempts),(select count(*) from payment.attempt),null,null,(select count(*) from payment.attempt)-((select count(*) from public.payments source where not exists(select 1 from public.wechat_payment_attempts attempt where attempt.payment_id=source.id))+(select count(*) from public.wechat_payment_attempts)),clock_timestamp()),
('payment.observation',(select count(*) from public.wechat_payment_observations where attempt_id is not null),(select count(*) from payment.observation),null,null,(select count(*) from payment.observation)-(select count(*) from public.wechat_payment_observations where attempt_id is not null),clock_timestamp()),
('payment.effect',(select count(*) from public.payment_event_effects),(select count(*) from payment.effect),null,null,(select count(*) from payment.effect)-(select count(*) from public.payment_event_effects),clock_timestamp()),
('payment.recovery',(select count(*) from public.payment_operations_alerts)+(select count(*) from public.payment_recovery_requests),(select count(*) from payment.recoverycase)+(select count(*) from payment.recoveryrequest),null,null,((select count(*) from payment.recoverycase)+(select count(*) from payment.recoveryrequest))-((select count(*) from public.payment_operations_alerts)+(select count(*) from public.payment_recovery_requests)),clock_timestamp()),
('voucher.request',(select count(*) from public.voucher_reserve_requests)+(select count(*) from public.voucher_approval_actions),(select count(*) from voucher.reserverequest)+(select count(*) from voucher.approval),null,null,((select count(*) from voucher.reserverequest)+(select count(*) from voucher.approval))-((select count(*) from public.voucher_reserve_requests)+(select count(*) from public.voucher_approval_actions)),clock_timestamp()),
('notification.dispatch',(select count(*) from public.notification_dispatches),(select count(*) from notification.dispatch),null,null,(select count(*) from notification.dispatch)-(select count(*) from public.notification_dispatches),clock_timestamp()),
('runtime.outbox',(select count(*) from public.payment_outbox where topic in('order.payment_succeeded','order.payment_terminal'))+(select count(*) from public.wechat_refund_event_outbox where event_type='RefundSucceeded'),(select count(*) from runtime.outbox),null,null,(select count(*) from runtime.outbox)-((select count(*) from public.payment_outbox where topic in('order.payment_succeeded','order.payment_terminal'))+(select count(*) from public.wechat_refund_event_outbox where event_type='RefundSucceeded')),clock_timestamp()),
('runtime.inbox',(select count(*) from public.payment_event_inbox)+(select count(*) from public.wechat_refund_event_inbox)+(select count(*) from public.wechat_refund_notification_inbox),(select count(*) from runtime.inbox),null,null,(select count(*) from runtime.inbox)-((select count(*) from public.payment_event_inbox)+(select count(*) from public.wechat_refund_event_inbox)+(select count(*) from public.wechat_refund_notification_inbox)),clock_timestamp()),
('runtime.deadletter',(select count(*) from public.payment_outbox where topic='order.payment_reconciliation_required')+(select count(*) from public.wechat_refund_event_outbox where event_type='RefundClosed'),(select count(*) from runtime.deadletter),null,null,(select count(*) from runtime.deadletter)-((select count(*) from public.payment_outbox where topic='order.payment_reconciliation_required')+(select count(*) from public.wechat_refund_event_outbox where event_type='RefundClosed')),clock_timestamp());

insert into runtime.reconciliationevidence(id,source_count,target_count,source_amount,target_amount,difference,checked_at) values
('channel.distributor',(select count(*) from public.distributors)+(select count(*) from public.distributor_tenants),(select count(*) from channel.distributor)+(select count(*) from channel.tenantbinding),null,null,((select count(*) from channel.distributor)+(select count(*) from channel.tenantbinding))-((select count(*) from public.distributors)+(select count(*) from public.distributor_tenants)),clock_timestamp()),
('payment.capture',(select count(*) from public.payment_intents),(select count(*) from payment.capture),(select coalesce(sum(amount_cents),0) from public.payment_intents),(select coalesce(sum(amount_minor),0) from payment.capture),(select coalesce(sum(amount_minor),0) from payment.capture)-(select coalesce(sum(amount_cents),0) from public.payment_intents),clock_timestamp());

insert into runtime.reconciliationhash(id,source_hash,target_hash,checked_at) values
('organization',
  (select encode(digest(coalesce(string_agg(id||':'||kind||':'||coalesce(parent_id,'')||':'||status,'|' order by id),''),'sha256'),'hex') from (
    select 'organization-platform-root' id,'platform' kind,null::text parent_id,'active' status
    union all select tenant.id,'tenant',coalesce((select binding.distributor_id from public.distributor_tenants binding where binding.tenant_id=tenant.id and binding.status='active'),'organization-platform-root'),tenant.status from public.tenants tenant
    union all select id,'enterprise',tenant_id,status from public.enterprises
    union all select id,'mall',enterprise_id,status from public.malls
    union all select id,'department',coalesce(parent_id,enterprise_id),'active' from public.departments
    union all select id,'distributor','organization-platform-root',case status when 'active' then 'active' when 'draft' then 'draft' else 'disabled' end from public.distributors
  ) source),
  (select encode(digest(coalesce(string_agg(id||':'||kind||':'||coalesce(parent_id,'')||':'||status,'|' order by id),''),'sha256'),'hex') from organization.organization),clock_timestamp()),
('product',
  (select encode(digest(coalesce(string_agg(id||':'||supplier_id||':'||category_code||':'||coalesce(brand_id,'')||':'||case status when 'active' then 'active' when 'inactive' then 'archived' else 'draft' end,'|' order by id),''),'sha256'),'hex') from public.products where is_test=false),
  (select encode(digest(coalesce(string_agg(id||':'||owner_partner_id||':'||(select code from catalog.category category where category.id=product.category_id)||':'||coalesce(brand_id,'')||':'||status,'|' order by id),''),'sha256'),'hex') from catalog.product product),clock_timestamp()),
('inventory',
  (select encode(digest(coalesce(string_agg(source.id||':'||source.sku_id||':'||source.location_id||':'||source.onhand||':'||source.safety||':'||source.version,'|' order by source.id),''),'sha256'),'hex') from inventory.stock_items source where exists(select 1 from inventory.stockitem target where target.id=source.id)),
  (select encode(digest(coalesce(string_agg(id||':'||sku_id||':'||location_id||':'||onhand||':'||safety||':'||version,'|' order by id),''),'sha256'),'hex') from inventory.stockitem),clock_timestamp()),
('order',
  (select encode(digest(coalesce(string_agg(id||':'||order_no||':'||payable_cents||':'||created_at::text,'|' order by id),''),'sha256'),'hex') from public.orders),
  (select encode(digest(coalesce(string_agg(id||':'||order_number||':'||total_minor||':'||created_at::text,'|' order by id),''),'sha256'),'hex') from ordering.orderrecord),clock_timestamp()),
('payment',
  (select encode(digest(coalesce(string_agg(id||':'||amount_cents||':'||status,'|' order by id),''),'sha256'),'hex') from public.payments where status in('succeeded','refunded','closed')),
  (select encode(digest(coalesce(string_agg(id||':'||amount_minor||':'||case state when 'captured' then 'succeeded' when 'refunded' then 'refunded' else 'closed' end,'|' order by id),''),'sha256'),'hex') from payment.payment),clock_timestamp()),
('voucher',
  (select encode(digest(coalesce(string_agg(id||':'||initial_cents||':'||remaining_cents||':'||version,'|' order by id),''),'sha256'),'hex') from public.vouchers),
  (select encode(digest(coalesce(string_agg(id||':'||initial_minor||':'||remaining_minor||':'||version,'|' order by id),''),'sha256'),'hex') from voucher.voucher),clock_timestamp()),
('financeentry',
  (select encode(digest(coalesce(string_agg(id::text||':'||side||':'||amount_cents,'|' order by id::text),''),'sha256'),'hex') from public.finance_journal_entries),
  (select encode(digest(coalesce(string_agg(replace(id,'','')||':'||side||':'||amount_minor,'|' order by id),''),'sha256'),'hex') from finance.entry where id not like 'legacy-ledger-%'),clock_timestamp());

insert into runtime.reconciliationhash(id,source_hash,target_hash,checked_at)
select 'organization.closure',
  encode(digest(coalesce(string_agg(ancestor_target.organization_id||':'||descendant_target.organization_id||':'||source.depth,'|' order by ancestor_target.organization_id,descendant_target.organization_id),''),'sha256'),'hex'),
  (select encode(digest(coalesce(string_agg(target.ancestor_id||':'||target.descendant_id||':'||target.depth,'|' order by target.ancestor_id,target.descendant_id),''),'sha256'),'hex') from organization.unitclosure target),clock_timestamp()
from public.org_unit_closure source
join public.org_units ancestor on ancestor.id=source.ancestor_id
join public.org_units descendant on descendant.id=source.descendant_id
join organization.sourcebinding ancestor_target on ancestor_target.source_type=case when ancestor.kind='platform' then 'orgunit' else ancestor.source_type end
  and ancestor_target.source_id=case when ancestor.kind='platform' then ancestor.id else ancestor.source_id end
join organization.sourcebinding descendant_target on descendant_target.source_type=case when descendant.kind='platform' then 'orgunit' else descendant.source_type end
  and descendant_target.source_id=case when descendant.kind='platform' then descendant.id else descendant.source_id end;

do $$
begin
  if exists(select 1 from runtime.reconciliationevidence where difference<>0) then raise exception 'DOMAIN_RECONCILIATION_DIFFERENCE'; end if;
  if exists(select 1 from runtime.reconciliationhash where source_hash<>target_hash) then raise exception 'DOMAIN_RECONCILIATION_HASH_DIFFERENCE'; end if;
  if exists(select 1 from organization.organization where parent_id is not null and not exists(select 1 from organization.organization parent where parent.id=organization.organization.parent_id)) then raise exception 'ORGANIZATION_ORPHAN'; end if;
  if exists(select provider,objecttype,externalid from channel.externalobject group by provider,objecttype,externalid having count(*)>1) then raise exception 'EXTERNAL_OBJECT_DUPLICATE'; end if;
  if exists(select order_number from ordering.orderrecord group by order_number having count(*)>1) then raise exception 'ORDER_NUMBER_DUPLICATE'; end if;
  if exists(select code_fingerprint from voucher.voucher group by code_fingerprint having count(*)>1) then raise exception 'VOUCHER_FINGERPRINT_DUPLICATE'; end if;
  if exists(select journal_id from finance.entry group by journal_id having sum(case when side='debit' then amount_minor else -amount_minor end)<>0) then raise exception 'FINANCE_LEDGER_UNBALANCED'; end if;
  if exists(select 1 from benefit.account account where (select coalesce(sum(entry.amount_minor),0) from benefit.entry entry where entry.account_id=account.id)<>(select balance_cents from public.welfare_accounts source where source.id=account.id)) then raise exception 'BENEFIT_BALANCE_DIFFERENCE'; end if;
  if exists(select 1 from voucher.redemption redemption join voucher.reversal reversal on reversal.redemption_id=redemption.id where reversal.amount_minor<>redemption.amount_minor) then raise exception 'VOUCHER_REVERSAL_AMOUNT_DIFFERENCE'; end if;
  if exists(select 1 from member.membership source where not exists(select 1 from organization.organization target where target.id=source.organization_id)) then raise exception 'MEMBERSHIP_ORGANIZATION_ORPHAN'; end if;
  if exists(select 1 from identity.federatedidentity source where source.principal_id is not null and not exists(select 1 from identity.principal target where target.id=source.principal_id)) then raise exception 'FEDERATED_PRINCIPAL_ORPHAN'; end if;
  if exists(select 1 from identity.federatedidentity source where source.membership_id is not null and not exists(select 1 from member.membership target where target.id=source.membership_id)) then raise exception 'FEDERATED_MEMBERSHIP_ORPHAN'; end if;
  if exists(select 1 from catalog.product source where source.owner_partner_id is not null and not exists(select 1 from partner.partner target where target.id=source.owner_partner_id)) then raise exception 'PRODUCT_PARTNER_ORPHAN'; end if;
  if exists(select 1 from catalog.product source where source.brand_id is not null and not exists(select 1 from partner.brand target where target.id=source.brand_id)) then raise exception 'PRODUCT_BRAND_ORPHAN'; end if;
  if exists(select 1 from ordering.orderrecord source where not exists(select 1 from member.profile target where target.id=source.member_id)) then raise exception 'ORDER_MEMBER_ORPHAN'; end if;
  if exists(select 1 from fulfillment.line source where not exists(select 1 from ordering.line target where target.id=source.order_line_id)) then raise exception 'FULFILLMENT_LINE_ORPHAN'; end if;
  if exists(select 1 from public.user_roles source join public.memberships legacy on legacy.context_user_id=source.user_id and legacy.tenant_id=source.tenant_id
    join member.membership membership on membership.id=legacy.id where not exists(select 1 from access.membershiprole target where target.membership_id=membership.id and target.role_id=source.role_id)) then raise exception 'LEGACY_USER_ROLE_UNMAPPED'; end if;
end $$;

do $$ declare item record; begin
  for item in select tablename from pg_tables where schemaname='runtime' loop
    execute format('alter table runtime.%I enable row level security',item.tablename);
  end loop;
end $$;

commit;
