/* GENERATED by scripts/build-web-tokens.mjs — do not edit by hand. */
/* Source of truth: packages/design/src/tokens.json v1.0.0 */

export const token = Object.freeze({
  color: Object.freeze({
    brand: '#1F5EFF',
    brandDark: '#143A8F',
    danger: '#B91C1C',
    warning: '#92400E',
    success: '#087A55',
    text: '#172033',
    muted: '#64748B',
    surface: '#FFFFFF',
    canvas: '#F5F7FA',
  }),
  radius: Object.freeze({ small: '8px', medium: '12px', large: '16px' }),
  space: Object.freeze({ small: '8px', medium: '16px', large: '24px' }),
});

export type Token = typeof token;
