import { defineModuleManifest } from '@shop/kernel';
import { FINANCE_CAPABILITIES } from './01_public_gongkai/FinanceCapabilities';

export const financeManifest = defineModuleManifest({
  id: 'finance',
  version: '1.0.0',
  kind: 'business',
  provides: [FINANCE_CAPABILITIES.read, FINANCE_CAPABILITIES.manage],
  requires: ['reporting'],
  operations: [
    'finance.audit.read',
    'finance.backfills.decide',
    'finance.backfills.read',
    'finance.entries.read',
    'finance.holds.read',
    'finance.overview.read',
    'finance.policies.manage',
    'finance.policies.preview',
    'finance.policies.read',
    'finance.periods.manage',
    'finance.periods.read',
    'finance.reconciliationrepairs.decide',
    'finance.reconciliationrepairs.preview',
    'finance.reconciliationrepairs.read',
    'finance.reconciliationrepairs.reverse',
    'finance.reconciliationrepairs.submit',
    'finance.reconciliations.manage',
    'finance.reconciliations.read',
    'finance.settlements.adjust',
    'finance.settlements.decide',
    'finance.settlements.read',
    'finance.statements.export',
    'finance.statements.read',
    'finance.withdrawals.create',
    'finance.withdrawals.decide',
    'finance.withdrawals.read',
    'finance.withdrawals.recover',
    'invoice.operatorprofiles.read',
    'invoice.profiles.manage',
    'invoice.profiles.read',
    'invoice.requests.cancel',
    'invoice.requests.create',
    'invoice.requests.decide',
    'invoice.requests.read',
    'invoice.requests.red',
  ],
  publishes: [
    'finance.settlement.approved',
    'finance.settlement.adjusted',
    'finance.period.closed',
  ],
  consumes: [],
  publicEntry: './index.ts',
  layers: ['public', 'domain', 'application', 'adapters', 'interface', 'tests'],
  entrypoints: {
    http: ['financeRoutes'],
    jobs: ['reconciliation', 'settlement', 'invoice'],
  },
});
