import { deadLetter, registerJob, retry, retry3, retry5, worker, type JobCatalogEntry } from './JobPolicy';

export const CORE_JOB_CATALOG = Object.freeze([
  registerJob({
    id: 'sessionrevocation',
    owner: 'identity',
    queue: 'identity',
    concurrency: 16,
    timeout: 15_000,
    retry,
    lease: 30,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/sessionrevocation.md',
    worker,
  }),
  registerJob({
    id: 'ownershipexpiry',
    owner: 'access',
    queue: 'governance',
    concurrency: 4,
    timeout: 15_000,
    retry,
    lease: 30,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/ownershipexpiry.md',
    worker,
  }),
  registerJob({
    id: 'qualificationexpiry',
    owner: 'qualification',
    queue: 'governance',
    concurrency: 8,
    timeout: 30_000,
    retry,
    lease: 60,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/qualificationexpiry.md',
    worker,
  }),
  registerJob({ id: 'approvalescalation', owner: 'approval', queue: 'governance', concurrency: 4, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/approval.md', worker }),
  registerJob({ id: 'catalogsync', owner: 'catalog', queue: 'channel', concurrency: 8, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/catalogsync.md', worker }),
  registerJob({ id: 'pricesync', owner: 'pricing', queue: 'channel', concurrency: 8, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/pricesync.md', worker }),
  registerJob({ id: 'inventorysync', owner: 'inventory', queue: 'channel', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/inventorysync.md', worker }),
  registerJob({
    id: 'experiencepublish',
    owner: 'experience',
    queue: 'experience',
    concurrency: 8,
    timeout: 30_000,
    retry,
    lease: 60,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/experiencepublish.md',
    worker,
  }),
  registerJob({
    id: 'experienceprovision',
    owner: 'experience',
    queue: 'experience',
    concurrency: 8,
    timeout: 30_000,
    retry,
    lease: 60,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/experienceprovision.md',
    worker,
  }),
  registerJob({ id: 'navigation', owner: 'navigation', queue: 'navigation', concurrency: 16, timeout: 15_000, retry, lease: 30, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/navigation.md', worker }),
  registerJob({ id: 'statementsync', owner: 'finance', queue: 'channel', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/statementsync.md', worker }),
  registerJob({ id: 'channelwebhook', owner: 'channel', queue: 'channel', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/channelwebhook.md', worker }),
  registerJob({ id: 'orderexpiry', owner: 'checkout', queue: 'transaction', concurrency: 16, timeout: 15_000, retry, lease: 30, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/orderexpiry.md', worker }),
  registerJob({
    id: 'reservationexpiry',
    owner: 'inventory',
    queue: 'transaction',
    concurrency: 16,
    timeout: 15_000,
    retry,
    lease: 30,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/reservationexpiry.md',
    worker,
  }),
  registerJob({
    id: 'marketingbudgetexpiry',
    owner: 'marketing',
    queue: 'transaction',
    concurrency: 16,
    timeout: 15_000,
    retry,
    lease: 30,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/marketingbudgetexpiry.md',
    worker,
  }),
  registerJob({ id: 'paymentquery', owner: 'payment', queue: 'payment', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/paymentquery.md', worker }),
  registerJob({ id: 'paymentrefund', owner: 'payment', queue: 'payment', concurrency: 8, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/paymentrefund.md', worker }),
  registerJob({ id: 'paymentcancel', owner: 'payment', queue: 'payment', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/paymentcancel.md', worker }),
  registerJob({ id: 'fulfillmentevent', owner: 'fulfillment', queue: 'fulfillment', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/fulfillmentevent.md', worker }),
  registerJob({ id: 'fulfillment', owner: 'fulfillment', queue: 'fulfillment', concurrency: 16, timeout: 45_000, retry, lease: 90, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/fulfillment.md', worker }),
  registerJob({ id: 'tracking', owner: 'fulfillment', queue: 'fulfillment', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/tracking.md', worker }),
  registerJob({ id: 'benefitgrant', owner: 'benefit', queue: 'benefit', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/benefitgrant.md', worker }),
  registerJob({ id: 'benefitexpiry', owner: 'benefit', queue: 'benefit', concurrency: 8, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/benefitexpiry.md', worker }),
  registerJob({ id: 'credentialgenerate', owner: 'voucher', queue: 'batch', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/credentialgenerate.md', worker }),
  registerJob({ id: 'voucherissue', owner: 'voucher', queue: 'batch', concurrency: 8, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/voucherissue.md', worker }),
  registerJob({ id: 'voucheraction', owner: 'voucher', queue: 'batch', concurrency: 8, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/voucheraction.md', worker }),
  registerJob({ id: 'voucherexport', owner: 'voucher', queue: 'export', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/voucherexport.md', worker }),
  registerJob({ id: 'referralevent', owner: 'referral', queue: 'referral', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/referralevent.md', worker }),
  registerJob({
    id: 'referralsettlement',
    owner: 'referral',
    queue: 'referral',
    concurrency: 8,
    timeout: 120_000,
    retry,
    lease: 180,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/referralsettlement.md',
    worker,
  }),
  registerJob({ id: 'reconciliation', owner: 'finance', queue: 'finance', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/reconciliation.md', worker }),
  registerJob({ id: 'settlement', owner: 'finance', queue: 'finance', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/settlement.md', worker }),
  registerJob({ id: 'invoice', owner: 'finance', queue: 'finance', concurrency: 4, timeout: 60_000, retry, lease: 90, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/invoice.md', worker }),
] satisfies readonly JobCatalogEntry[]);
