import { deadLetter, registerJob, retry, retry3, retry5, worker, type JobCatalogEntry } from './JobPolicy';

export const WORKFLOW_JOB_CATALOG = Object.freeze([
  registerJob({
    id: 'identitynotification',
    owner: 'notification',
    queue: 'identity',
    concurrency: 16,
    timeout: 15_000,
    retry,
    lease: 30,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/notification.md',
    worker,
  }),
  registerJob({
    id: 'notification',
    owner: 'notification',
    queue: 'notification',
    concurrency: 32,
    timeout: 15_000,
    retry,
    lease: 30,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/notification.md',
    worker,
  }),
  registerJob({ id: 'projection', owner: 'reporting', queue: 'projection', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/projection.md', worker }),
  registerJob({ id: 'export', owner: 'reporting', queue: 'export', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/export.md', worker }),
  registerJob({ id: 'riskscan', owner: 'risk', queue: 'risk', concurrency: 8, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/riskscan.md', worker }),
  registerJob({ id: 'cleanup', owner: 'runtime', queue: 'maintenance', concurrency: 2, timeout: 60_000, retry, lease: 90, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/cleanup.md', worker }),
  registerJob({ id: 'memberimport', owner: 'member', queue: 'import', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/memberimport.md', worker }),
  registerJob({ id: 'financeimport', owner: 'finance', queue: 'import', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/financeimport.md', worker }),
  registerJob({ id: 'catalogimport', owner: 'catalog', queue: 'import', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/catalogimport.md', worker }),
  registerJob({ id: 'orderimport', owner: 'order', queue: 'import', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/orderimport.md', worker }),
  registerJob({ id: 'orderevent', owner: 'order', queue: 'transaction', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/orderevent.md', worker }),
  registerJob({
    id: 'inventoryimport',
    owner: 'inventory',
    queue: 'import',
    concurrency: 4,
    timeout: 120_000,
    retry,
    lease: 180,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/inventoryimport.md',
    worker,
  }),
  registerJob({ id: 'credentialimport', owner: 'voucher', queue: 'import', concurrency: 4, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/credentialimport.md', worker }),
  registerJob({ id: 'supportsla', owner: 'support', queue: 'support', concurrency: 8, timeout: 15_000, retry, lease: 30, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/supportsla.md', worker }),
  registerJob({ id: 'supportscan', owner: 'support', queue: 'support', concurrency: 8, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/supportscan.md', worker }),
  registerJob({ id: 'supportrelay', owner: 'support', queue: 'support', concurrency: 16, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/supportrelay.md', worker }),
  registerJob({ id: 'supportreassign', owner: 'support', queue: 'support', concurrency: 4, timeout: 30_000, retry, lease: 60, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/supportreassign.md', worker }),
  registerJob({ id: 'auditarchive', owner: 'audit', queue: 'maintenance', concurrency: 2, timeout: 120_000, retry, lease: 180, idempotency: 'jobid', deadLetter, runbook: 'docs/operations/auditarchive.md', worker }),
  registerJob({
    id: 'extensionhealth',
    owner: 'extension',
    queue: 'maintenance',
    concurrency: 8,
    timeout: 30_000,
    retry,
    lease: 60,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/extensionhealth.md',
    worker,
  }),
  registerJob({
    id: 'directorysync',
    owner: 'organization',
    queue: 'identity',
    concurrency: 8,
    timeout: 120_000,
    retry,
    lease: 180,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/directorysync.md',
    worker,
  }),
  registerJob({
    id: 'directoryreconcile',
    owner: 'organization',
    queue: 'maintenance',
    concurrency: 2,
    timeout: 300_000,
    retry: retry5,
    lease: 360,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/directoryreconcile.md',
    worker,
  }),
  registerJob({
    id: 'federationcleanup',
    owner: 'identity',
    queue: 'maintenance',
    concurrency: 2,
    timeout: 60_000,
    retry,
    lease: 90,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/federationcleanup.md',
    worker,
  }),
  registerJob({
    id: 'providerhealth',
    owner: 'identity',
    queue: 'identity',
    concurrency: 8,
    timeout: 30_000,
    retry: retry3,
    lease: 60,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/providerhealth.md',
    worker,
  }),
  registerJob({
    id: 'invitationcleanup',
    owner: 'identity',
    queue: 'maintenance',
    concurrency: 2,
    timeout: 60_000,
    retry,
    lease: 90,
    idempotency: 'jobid',
    deadLetter,
    runbook: 'docs/operations/invitationcleanup.md',
    worker,
  }),
] satisfies readonly JobCatalogEntry[]);
