import { journey } from './JourneyHarness';
journey('MVPGROUPSUPPORT', {
  workstation: 'groupsupport',
  operations: [
    'support.accounts.manage',
    'support.accounts.read',
    'support.agents.manage',
    'support.agents.read',
    'support.assignments.manage',
    'support.attachments.create',
    'support.cases.close',
    'support.cases.create',
    'support.cases.read',
    'support.cases.reopen',
    'support.cases.update',
    'support.events.read',
    'support.history.read',
    'support.messages.read',
    'support.messages.send',
    'support.readstates.manage',
    'support.rules.manage',
    'support.rules.read',
    'support.slas.manage',
    'support.slas.read',
  ],
  tables: ['support.case', 'support.message', 'support.assignment', 'support.sla'],
  event: 'support.message.sent',
});
