export const IDEAL_JOURNEYS = [
  journey('J01', '密码注册登录', 'MVPIDENTITY', 'identity', 'password registration'),
  journey('J02', '邀请注册登录', 'MVPIDENTITY', 'identity', 'invitation registration'),
  journey('J03', '手机验证码', 'MVPIDENTITY', 'identity', 'mobile challenge'),
  journey('J04', '多成员身份切换', 'MVPIDENTITY', 'identity', 'multiple memberships'),
  journey('J05', '联合身份绑定', 'MVPIDENTITY', 'identity', 'federation link'),
  journey('J06', '会话与设备撤销', 'MVPIDENTITY', 'identity', 'session devices'),
  journey('J07', '创建成员', 'MVPGROUPSETTING', 'governance', 'create member'),
  journey('J08', '成员导入', 'MVPGROUPSETTING', 'governance', 'member import'),
  journey('J09', '角色授权与拒绝', 'MVPGROUPSETTING', 'governance', 'role grant deny'),
  journey('J10', '所有权转移', 'MVPGROUPSETTING', 'governance', 'owner transfer'),
  journey('J11', '审批模板', 'MVPGROUPSETTING', 'governance', 'approval template'),
  journey('J12', '审批任务', 'MVPGROUPVOUCHER', 'governance', 'approval task'),
  journey('J13', '创建商城', 'MVPGROUPAPPLICATION', 'experience', 'create mall'),
  journey('J14', '复制应用', 'MVPGROUPAPPLICATION', 'experience', 'copy application'),
  journey('J15', '商城主题发布', 'MVPMALLDESIGN', 'experience', 'shop theme'),
  journey('J16', '团购主题发布', 'MVPMALLDESIGN', 'experience', 'market theme'),
  journey('J17', '政企主题发布', 'MVPMALLDESIGN', 'experience', 'governance theme'),
  journey('J18', '发布失败恢复', 'MVPMALLDESIGN', 'experience', 'publish recovery'),
  journey('J19', '商品新建编辑归档', 'MVPGROUPPOOL', 'salechain', 'product create edit archive'),
  journey('J20', '商品导入', 'MVPGROUPPOOL', 'salechain', 'product import'),
  journey('J21', '库存导入', 'MVPMALLPOOL', 'salechain', 'stock import'),
  journey('J22', '经营资格治理', 'MVPMALLSETTING', 'salechain', 'qualification'),
  journey('J23', '报价规则', 'MVPMALLPOOL', 'salechain', 'pricing'),
  journey('J24', '商品池发布', 'MVPGROUPPOOL', 'salechain', 'pool publication'),
  journey('J25', '匿名消费者购买', 'MVPMALLORDER', 'transaction', 'anonymous purchase'),
  journey('J26', '福利支付购买', 'MVPMALLORDER', 'transaction', 'benefit purchase'),
  journey('J27', '卡券组合支付', 'MVPMALLVOUCHER', 'transaction', 'voucher tender'),
  journey('J28', '迟到支付恢复', 'MVPGROUPORDER', 'transaction', 'delayed payment'),
  journey('J29', '渠道履约', 'MVPGROUPORDER', 'transaction', 'channel fulfillment'),
  journey('J30', '售后退款', 'MVPMALLORDER', 'transaction', 'aftersale refund'),
  journey('J31', '外部订单导入', 'MVPGROUPORDER', 'transaction', 'order import'),
  journey('J32', '凭证批量生成', 'MVPGROUPVOUCHER', 'voucher', 'credential generation'),
  journey('J33', '凭证安全导入导出', 'MVPGROUPVOUCHER', 'voucher', 'credential import export'),
  journey('J34', '备券申请', 'MVPGROUPVOUCHER', 'voucher', 'stock request'),
  journey('J35', '发行订单', 'MVPGROUPVOUCHER', 'voucher', 'issue order'),
  journey('J36', '卡券生命周期', 'MVPMALLVOUCHER', 'voucher', 'lifecycle'),
  journey('J37', '卡券核销退款', 'MVPMALLVOUCHER', 'voucher', 'redemption refund'),
  journey('J38', '财务账单导入', 'MVPGROUPFINANCE', 'finance', 'statement import'),
  journey('J39', '对账差异修复', 'MVPGROUPFINANCE', 'finance', 'reconciliation repair'),
  journey('J40', '结算提现发票', 'MVPMALLFINANCE', 'finance', 'settlement withdrawal invoice'),
  journey('J41', '一期渠道矩阵', 'MVPPROVIDER', 'channel', 'provider matrix'),
  journey('J42', '客服会话', 'MVPGROUPSUPPORT', 'support', 'conversation'),
  journey('J43', '范围报表导出', 'MVPGROUPREPORT', 'reporting', 'scoped report export'),
  journey('J44', '全部可见动作无占位', 'MVPPLATFORM', 'placeholder', 'all visible actions'),
] as const;

export type IdealJourney = (typeof IDEAL_JOURNEYS)[number];
export type IdealJourneyId = IdealJourney['id'];

function journey<
  const Id extends `J${number}`,
  const Requirement extends `MVP${string}`,
  const Suite extends string,
  const Scenario extends string,
>(id: Id, title: string, requirement: Requirement, suite: Suite, scenario: Scenario) {
  return Object.freeze({
    id,
    title,
    requirement,
    suite,
    scenario,
    test: `tests/e2e/${suite}.spec.ts`,
    status: 'planned' as const,
  });
}
