import { storefrontJourney } from './StorefrontJourneyHarness';
storefrontJourney('storefront member asset journey', {
  operations: [
    'member.addresses.read',
    'member.addresses.manage',
    'invoice.profiles.read',
    'invoice.requests.create',
    'voucher.search.read',
    'voucher.vouchers.get',
    'voucher.vouchers.timeline',
    'benefit.accounts.read',
    'benefit.ledgers.read',
    'referral.members.apply',
    'referral.earnings.read',
    'referral.links.read',
    'referral.withdrawals.read',
    'referral.withdrawals.create',
    'notification.notifications.read',
    'notification.preferences.read',
    'notification.preferences.manage',
  ],
  routes: ['/profile', '/vouchers', '/benefits', '/notifications'],
  sources: [
    'apps/storefront/src/feature/account/infrastructure/AccountGateway.ts',
    'apps/storefront/src/feature/voucher/infrastructure/VoucherGateway.ts',
    'apps/storefront/src/feature/benefit/infrastructure/BenefitGateway.ts',
    'apps/storefront/src/feature/referral/infrastructure/ReferralGateway.ts',
    'apps/storefront/src/feature/notification/infrastructure/NotificationGateway.ts',
  ],
  markers: [/addresses/, /voucher/, /accounts/, /ledger/, /withdraw/, /preference/],
});
