// Generated from packages/contract/definitions/events.yml. Do not edit.
import { COMMERCE_EVENTS } from '@shop/contract';

export const EVENT_SCHEMA_TYPES = Object.freeze([
  'identity.session.created',
  'identity.session.revoked',
  'identity.challenge.started',
  'identity.member.registered',
  'identity.member.reset',
  'access.version.changed',
  'catalog.listing.published',
  'inventory.stock.changed',
  'inventory.stock.reserved',
  'experience.published',
  'checkout.quote.created',
  'checkout.quote.confirmed',
  'order.placed',
  'order.paid',
  'order.received',
  'order.cancelled',
  'payment.succeeded',
  'payment.refunded',
  'payment.late.detected',
  'payment.attempt.failed',
  'payment.provider.observed',
  'payment.autorefund.requested',
  'payment.recovery.opened',
  'fulfillment.shipped',
  'voucher.issued',
  'voucher.issue.failed',
  'voucher.import.failed',
  'voucher.status.failed',
  'voucher.redeemed',
  'benefit.granted',
  'benefit.expired',
  'benefit.expiry.reminded',
  'benefit.revoked',
  'benefit.grant.failed',
  'benefit.revoke.failed',
  'benefit.expiry.failed',
  'finance.entry.posted',
  'finance.reconciliation.difference',
  'finance.settlement.approved',
  'finance.settlement.adjusted',
  'finance.period.closed',
  'finance.withdrawal.paid',
  'finance.withdrawal.uncertain',
  'invoice.issued',
  'invoice.red.issued',
  'support.message.sent',
  'support.ticket.assigned',
  'support.sla.escalated',
  'channel.sync.completed',
  'channel.webhook.applied',
  'channel.refund.changed',
  'notification.delivered',
  'risk.policy.activated',
  'catalog.listing.unpublished',
  'risk.case.opened',
  'risk.case.resolved',
  'risk.transaction.blocked',
  'extension.enabled',
  'extension.disabled',
  'extension.degraded',
] as const);

export const EVENT_HANDLERS = new Map<string, readonly string[]>([
  ["identity.session.created", Object.freeze(["projection"])],
  ["identity.session.revoked", Object.freeze(["projection"])],
  ["identity.challenge.started", Object.freeze([])],
  ["identity.member.registered", Object.freeze(["projection"])],
  ["identity.member.reset", Object.freeze(["projection"])],
  ["access.version.changed", Object.freeze(["projection"])],
  ["catalog.listing.published", Object.freeze(["projection"])],
  ["inventory.stock.changed", Object.freeze(["projection"])],
  ["inventory.stock.reserved", Object.freeze(["projection"])],
  ["experience.published", Object.freeze(["experiencepublish","projection"])],
  ["checkout.quote.created", Object.freeze([])],
  ["checkout.quote.confirmed", Object.freeze(["projection"])],
  ["order.placed", Object.freeze(["projection","reconciliation","referral"])],
  ["order.paid", Object.freeze(["projection","referral"])],
  ["order.received", Object.freeze(["referral"])],
  ["order.cancelled", Object.freeze(["projection","reconciliation","referral"])],
  ["payment.succeeded", Object.freeze(["notification","reconciliation"])],
  ["payment.refunded", Object.freeze(["projection","notification","reconciliation","referral"])],
  ["payment.late.detected", Object.freeze(["notification","reconciliation"])],
  ["payment.attempt.failed", Object.freeze([])],
  ["payment.provider.observed", Object.freeze([])],
  ["payment.autorefund.requested", Object.freeze(["notification","reconciliation"])],
  ["payment.recovery.opened", Object.freeze(["notification"])],
  ["fulfillment.shipped", Object.freeze(["projection","notification"])],
  ["voucher.issued", Object.freeze(["projection"])],
  ["voucher.issue.failed", Object.freeze(["notification"])],
  ["voucher.import.failed", Object.freeze(["notification"])],
  ["voucher.status.failed", Object.freeze(["notification"])],
  ["voucher.redeemed", Object.freeze(["projection"])],
  ["benefit.granted", Object.freeze(["projection","notification"])],
  ["benefit.expired", Object.freeze(["projection","notification"])],
  ["benefit.expiry.reminded", Object.freeze(["notification"])],
  ["benefit.revoked", Object.freeze(["projection","notification"])],
  ["benefit.grant.failed", Object.freeze(["notification"])],
  ["benefit.revoke.failed", Object.freeze(["notification"])],
  ["benefit.expiry.failed", Object.freeze(["notification"])],
  ["finance.entry.posted", Object.freeze(["projection"])],
  ["finance.reconciliation.difference", Object.freeze(["notification"])],
  ["finance.settlement.approved", Object.freeze(["projection","notification"])],
  ["finance.settlement.adjusted", Object.freeze(["projection","notification"])],
  ["finance.period.closed", Object.freeze(["projection","notification"])],
  ["finance.withdrawal.paid", Object.freeze(["projection","notification"])],
  ["finance.withdrawal.uncertain", Object.freeze(["notification"])],
  ["invoice.issued", Object.freeze(["projection","notification"])],
  ["invoice.red.issued", Object.freeze(["projection","notification"])],
  ["support.message.sent", Object.freeze(["projection","notification"])],
  ["support.ticket.assigned", Object.freeze(["projection","notification"])],
  ["support.sla.escalated", Object.freeze(["notification"])],
  ["channel.sync.completed", Object.freeze(["projection"])],
  ["channel.webhook.applied", Object.freeze(["projection"])],
  ["channel.refund.changed", Object.freeze(["projection","notification"])],
  ["notification.delivered", Object.freeze(["projection"])],
  ["risk.policy.activated", Object.freeze(["projection"])],
  ["catalog.listing.unpublished", Object.freeze(["notification"])],
  ["risk.case.opened", Object.freeze(["notification"])],
  ["risk.case.resolved", Object.freeze(["notification"])],
  ["risk.transaction.blocked", Object.freeze(["notification"])],
  ["extension.enabled", Object.freeze(["projection"])],
  ["extension.disabled", Object.freeze(["projection"])],
  ["extension.degraded", Object.freeze(["projection","notification"])],
]);

const versions = new Map<string, number>(COMMERCE_EVENTS.map((event) => [event.type, event.version]));

export function eventVersion(type: string): number {
  const version = versions.get(type);
  if (version === undefined) throw new Error('EVENT_SCHEMA_UNKNOWN');
  return version;
}
