// Generated from packages/contract/definitions/events.yml. Do not edit.
export const EVENT_SCHEMA_TYPES = Object.freeze([
  "identity.federation.linked",
  "identity.federation.rejected",
  "identity.provider.changed",
  "organization.directory.changed",
  "organization.directory.synced",
  "organization.membership.changed",
  "capability.changed",
  "navigation.catalog.changed",
  "identity.session.created",
  "identity.session.revoked",
  "identity.membership.switched",
  "identity.challenge.started",
  "identity.member.registered",
  "identity.invitation.issued",
  "identity.invitation.reserved",
  "identity.invitation.redeemed",
  "identity.invitation.revoked",
  "identity.invitation.expired",
  "identity.invitation.failed",
  "identity.enrollment.completed",
  "identity.link.required",
  "access.version.changed",
  "access.membership.invited",
  "access.membership.activated",
  "access.owner.transferred",
  "catalog.listing.published",
  "inventory.stock.changed",
  "inventory.stock.reserved",
  "experience.published",
  "checkout.quote.created",
  "checkout.quote.confirmed",
  "order.placed",
  "order.paid",
  "order.cancelled",
  "payment.captured",
  "aftersale.applied",
  "aftersale.changed",
  "return.inspected",
  "refund.completed",
  "payment.late.detected",
  "payment.attempt.failed",
  "payment.provider.observed",
  "payment.autorefund.requested",
  "payment.recovery.opened",
  "fulfillment.shipped",
  "voucher.issued",
  "voucher.issue.failed",
  "voucher.import.failed",
  "voucher.status.failed",
  "voucher.redeemed",
  "benefit.granted",
  "benefit.expired",
  "benefit.expiry.reminded",
  "benefit.revoked",
  "benefit.grant.failed",
  "benefit.revoke.failed",
  "benefit.expiry.failed",
  "finance.entry.posted",
  "finance.reconciliation.difference",
  "finance.settlement.approved",
  "finance.settlement.adjusted",
  "finance.period.closed",
  "finance.withdrawal.paid",
  "finance.withdrawal.uncertain",
  "invoice.issued",
  "invoice.red.issued",
  "support.message.sent",
  "support.ticket.assigned",
  "support.sla.escalated",
  "channel.sync.completed",
  "channel.webhook.applied",
  "channel.refund.changed",
  "notification.delivered",
  "risk.policy.activated",
  "catalog.listing.unpublished",
  "risk.case.opened",
  "risk.case.resolved",
  "risk.transaction.blocked",
  "extension.enabled",
  "extension.disabled",
  "extension.degraded",
  "order.export.requested",
  "finance.export.requested",
  "identity.member.reset",
  "order.received",
  "referral.setting.changed",
  "referral.product.changed",
  "referral.member.applied",
  "referral.member.approved",
  "referral.member.disqualified",
  "referral.binding.created",
  "referral.commission.created",
  "referral.commission.settled",
  "referral.commission.reversed",
  "referral.withdrawal.requested",
  "referral.withdrawal.paid",
  "referral.withdrawal.failed",
] as const);
const versions: ReadonlyMap<string, number> = new Map([
  ["identity.federation.linked", 1],
  ["identity.federation.rejected", 1],
  ["identity.provider.changed", 1],
  ["organization.directory.changed", 1],
  ["organization.directory.synced", 1],
  ["organization.membership.changed", 1],
  ["capability.changed", 1],
  ["navigation.catalog.changed", 1],
  ["identity.session.created", 1],
  ["identity.session.revoked", 1],
  ["identity.membership.switched", 1],
  ["identity.challenge.started", 1],
  ["identity.member.registered", 1],
  ["identity.invitation.issued", 1],
  ["identity.invitation.reserved", 1],
  ["identity.invitation.redeemed", 1],
  ["identity.invitation.revoked", 1],
  ["identity.invitation.expired", 1],
  ["identity.invitation.failed", 1],
  ["identity.enrollment.completed", 1],
  ["identity.link.required", 1],
  ["access.version.changed", 1],
  ["access.membership.invited", 1],
  ["access.membership.activated", 1],
  ["access.owner.transferred", 1],
  ["catalog.listing.published", 1],
  ["inventory.stock.changed", 1],
  ["inventory.stock.reserved", 1],
  ["experience.published", 1],
  ["checkout.quote.created", 1],
  ["checkout.quote.confirmed", 1],
  ["order.placed", 1],
  ["order.paid", 1],
  ["order.cancelled", 1],
  ["payment.captured", 1],
  ["aftersale.applied", 1],
  ["aftersale.changed", 1],
  ["return.inspected", 1],
  ["refund.completed", 1],
  ["payment.late.detected", 1],
  ["payment.attempt.failed", 1],
  ["payment.provider.observed", 1],
  ["payment.autorefund.requested", 1],
  ["payment.recovery.opened", 1],
  ["fulfillment.shipped", 1],
  ["voucher.issued", 1],
  ["voucher.issue.failed", 1],
  ["voucher.import.failed", 1],
  ["voucher.status.failed", 1],
  ["voucher.redeemed", 1],
  ["benefit.granted", 1],
  ["benefit.expired", 1],
  ["benefit.expiry.reminded", 1],
  ["benefit.revoked", 1],
  ["benefit.grant.failed", 1],
  ["benefit.revoke.failed", 1],
  ["benefit.expiry.failed", 1],
  ["finance.entry.posted", 1],
  ["finance.reconciliation.difference", 1],
  ["finance.settlement.approved", 1],
  ["finance.settlement.adjusted", 1],
  ["finance.period.closed", 1],
  ["finance.withdrawal.paid", 1],
  ["finance.withdrawal.uncertain", 1],
  ["invoice.issued", 1],
  ["invoice.red.issued", 1],
  ["support.message.sent", 1],
  ["support.ticket.assigned", 1],
  ["support.sla.escalated", 1],
  ["channel.sync.completed", 1],
  ["channel.webhook.applied", 1],
  ["channel.refund.changed", 1],
  ["notification.delivered", 1],
  ["risk.policy.activated", 1],
  ["catalog.listing.unpublished", 1],
  ["risk.case.opened", 1],
  ["risk.case.resolved", 1],
  ["risk.transaction.blocked", 1],
  ["extension.enabled", 1],
  ["extension.disabled", 1],
  ["extension.degraded", 1],
  ["order.export.requested", 1],
  ["finance.export.requested", 1],
  ["identity.member.reset", 1],
  ["order.received", 1],
  ["referral.setting.changed", 1],
  ["referral.product.changed", 1],
  ["referral.member.applied", 1],
  ["referral.member.approved", 1],
  ["referral.member.disqualified", 1],
  ["referral.binding.created", 1],
  ["referral.commission.created", 1],
  ["referral.commission.settled", 1],
  ["referral.commission.reversed", 1],
  ["referral.withdrawal.requested", 1],
  ["referral.withdrawal.paid", 1],
  ["referral.withdrawal.failed", 1],
]);
export function eventVersion(type: string): number { const version=versions.get(type); if(version===undefined) throw new Error('EVENT_SCHEMA_UNKNOWN'); return version; }
